// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module rv32_ooo_tick_fpu_compute (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        fpu_rs_s1_val,
        fpu_rs_s2_val,
        fpu_rs_s3_val,
        fpu_rs_r4op,
        fpu_rs_f7,
        fpu_rs_f3,
        fpu_rs_rs2f,
        ap_return
);

parameter    ap_ST_fsm_state1 = 78'd1;
parameter    ap_ST_fsm_state2 = 78'd2;
parameter    ap_ST_fsm_state3 = 78'd4;
parameter    ap_ST_fsm_state4 = 78'd8;
parameter    ap_ST_fsm_state5 = 78'd16;
parameter    ap_ST_fsm_state6 = 78'd32;
parameter    ap_ST_fsm_state7 = 78'd64;
parameter    ap_ST_fsm_state8 = 78'd128;
parameter    ap_ST_fsm_state9 = 78'd256;
parameter    ap_ST_fsm_state10 = 78'd512;
parameter    ap_ST_fsm_state11 = 78'd1024;
parameter    ap_ST_fsm_state12 = 78'd2048;
parameter    ap_ST_fsm_state13 = 78'd4096;
parameter    ap_ST_fsm_state14 = 78'd8192;
parameter    ap_ST_fsm_state15 = 78'd16384;
parameter    ap_ST_fsm_state16 = 78'd32768;
parameter    ap_ST_fsm_state17 = 78'd65536;
parameter    ap_ST_fsm_state18 = 78'd131072;
parameter    ap_ST_fsm_state19 = 78'd262144;
parameter    ap_ST_fsm_state20 = 78'd524288;
parameter    ap_ST_fsm_state21 = 78'd1048576;
parameter    ap_ST_fsm_state22 = 78'd2097152;
parameter    ap_ST_fsm_state23 = 78'd4194304;
parameter    ap_ST_fsm_state24 = 78'd8388608;
parameter    ap_ST_fsm_state25 = 78'd16777216;
parameter    ap_ST_fsm_state26 = 78'd33554432;
parameter    ap_ST_fsm_state27 = 78'd67108864;
parameter    ap_ST_fsm_state28 = 78'd134217728;
parameter    ap_ST_fsm_state29 = 78'd268435456;
parameter    ap_ST_fsm_state30 = 78'd536870912;
parameter    ap_ST_fsm_state31 = 78'd1073741824;
parameter    ap_ST_fsm_state32 = 78'd2147483648;
parameter    ap_ST_fsm_state33 = 78'd4294967296;
parameter    ap_ST_fsm_state34 = 78'd8589934592;
parameter    ap_ST_fsm_state35 = 78'd17179869184;
parameter    ap_ST_fsm_state36 = 78'd34359738368;
parameter    ap_ST_fsm_state37 = 78'd68719476736;
parameter    ap_ST_fsm_state38 = 78'd137438953472;
parameter    ap_ST_fsm_state39 = 78'd274877906944;
parameter    ap_ST_fsm_state40 = 78'd549755813888;
parameter    ap_ST_fsm_state41 = 78'd1099511627776;
parameter    ap_ST_fsm_state42 = 78'd2199023255552;
parameter    ap_ST_fsm_state43 = 78'd4398046511104;
parameter    ap_ST_fsm_state44 = 78'd8796093022208;
parameter    ap_ST_fsm_state45 = 78'd17592186044416;
parameter    ap_ST_fsm_state46 = 78'd35184372088832;
parameter    ap_ST_fsm_state47 = 78'd70368744177664;
parameter    ap_ST_fsm_state48 = 78'd140737488355328;
parameter    ap_ST_fsm_state49 = 78'd281474976710656;
parameter    ap_ST_fsm_state50 = 78'd562949953421312;
parameter    ap_ST_fsm_state51 = 78'd1125899906842624;
parameter    ap_ST_fsm_state52 = 78'd2251799813685248;
parameter    ap_ST_fsm_state53 = 78'd4503599627370496;
parameter    ap_ST_fsm_state54 = 78'd9007199254740992;
parameter    ap_ST_fsm_state55 = 78'd18014398509481984;
parameter    ap_ST_fsm_state56 = 78'd36028797018963968;
parameter    ap_ST_fsm_state57 = 78'd72057594037927936;
parameter    ap_ST_fsm_state58 = 78'd144115188075855872;
parameter    ap_ST_fsm_state59 = 78'd288230376151711744;
parameter    ap_ST_fsm_state60 = 78'd576460752303423488;
parameter    ap_ST_fsm_state61 = 78'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 78'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 78'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 78'd9223372036854775808;
parameter    ap_ST_fsm_state65 = 78'd18446744073709551616;
parameter    ap_ST_fsm_state66 = 78'd36893488147419103232;
parameter    ap_ST_fsm_state67 = 78'd73786976294838206464;
parameter    ap_ST_fsm_state68 = 78'd147573952589676412928;
parameter    ap_ST_fsm_state69 = 78'd295147905179352825856;
parameter    ap_ST_fsm_state70 = 78'd590295810358705651712;
parameter    ap_ST_fsm_state71 = 78'd1180591620717411303424;
parameter    ap_ST_fsm_state72 = 78'd2361183241434822606848;
parameter    ap_ST_fsm_state73 = 78'd4722366482869645213696;
parameter    ap_ST_fsm_state74 = 78'd9444732965739290427392;
parameter    ap_ST_fsm_state75 = 78'd18889465931478580854784;
parameter    ap_ST_fsm_state76 = 78'd37778931862957161709568;
parameter    ap_ST_fsm_state77 = 78'd75557863725914323419136;
parameter    ap_ST_fsm_state78 = 78'd151115727451828646838272;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] fpu_rs_s1_val;
input  [31:0] fpu_rs_s2_val;
input  [31:0] fpu_rs_s3_val;
input  [2:0] fpu_rs_r4op;
input  [6:0] fpu_rs_f7;
input  [2:0] fpu_rs_f3;
input  [4:0] fpu_rs_rs2f;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[31:0] ap_return;

(* fsm_encoding = "none" *) reg   [77:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [22:0] mask_table_q0;
wire   [22:0] one_half_minus_one_table_q0;
wire   [5:0] index_table_q0;
wire   [31:0] grp_fu_343_p2;
reg   [31:0] reg_490;
wire    ap_CS_fsm_state4;
wire   [2:0] fpu_rs_r4op_load_load_fu_539_p1;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state72;
wire   [31:0] grp_fu_339_p2;
reg   [31:0] reg_495;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state77;
wire   [6:0] fpu_rs_f7_load_load_fu_549_p1;
wire    ap_CS_fsm_state76;
reg    ap_predicate_pred187_state77;
reg    ap_predicate_pred198_state77;
wire   [22:0] x_fp_sig_1_fu_504_p1;
reg   [22:0] x_fp_sig_1_reg_1870;
wire   [30:0] t_9_fu_508_p1;
reg   [30:0] t_9_reg_1876;
wire   [31:0] a_fu_512_p1;
reg   [31:0] a_reg_1883;
wire   [31:0] b_fu_525_p1;
reg   [31:0] b_reg_1898;
wire   [31:0] c_fu_535_p1;
reg   [31:0] c_reg_1910;
wire   [0:0] icmp_ln386_1_fu_543_p2;
reg   [0:0] icmp_ln386_1_reg_1919;
wire   [0:0] grp_fu_392_p2;
reg   [0:0] xor_ln362_reg_1929;
reg   [0:0] xor_ln361_reg_1934;
wire   [2:0] fpu_rs_f3_load_load_fu_553_p1;
wire   [31:0] bitcast_ln327_fu_572_p1;
wire   [0:0] grp_fu_398_p2;
reg   [0:0] icmp_ln397_reg_1956;
reg   [0:0] icmp_ln392_reg_1961;
wire   [0:0] grp_fu_412_p2;
reg   [0:0] icmp_ln388_1_reg_1965;
wire   [0:0] icmp_ln388_2_fu_582_p2;
reg   [0:0] icmp_ln388_2_reg_1970;
reg   [0:0] icmp_ln387_1_reg_1975;
wire   [0:0] icmp_ln387_2_fu_592_p2;
reg   [0:0] icmp_ln387_2_reg_1980;
reg   [0:0] icmp_ln386_2_reg_1985;
wire   [0:0] icmp_ln386_3_fu_602_p2;
reg   [0:0] icmp_ln386_3_reg_1990;
wire   [0:0] grp_fu_385_p3;
reg   [0:0] x_fp_sign_reg_1995;
wire   [0:0] icmp_ln25_fu_642_p2;
reg   [0:0] icmp_ln25_reg_2000;
wire   [0:0] icmp_ln25_1_fu_654_p2;
reg   [0:0] icmp_ln25_1_reg_2006;
wire   [0:0] icmp_ln18_fu_660_p2;
reg   [0:0] icmp_ln18_reg_2012;
wire   [0:0] icmp_ln18_2_fu_666_p2;
reg   [0:0] icmp_ln18_2_reg_2018;
wire   [0:0] icmp_ln18_3_fu_672_p2;
reg   [0:0] icmp_ln18_3_reg_2024;
wire   [0:0] ymaggreater_1_fu_698_p3;
reg   [0:0] ymaggreater_1_reg_2030;
reg   [0:0] tmp_23_reg_2036;
reg   [0:0] tmp_24_reg_2042;
wire   [31:0] bitcast_ln362_fu_734_p1;
wire    ap_CS_fsm_state2;
wire   [31:0] bitcast_ln361_fu_745_p1;
wire   [31:0] empty_27_fu_750_p1;
wire    ap_CS_fsm_state9;
wire   [31:0] empty_26_fu_754_p1;
wire   [31:0] empty_25_fu_758_p1;
wire    ap_CS_fsm_state17;
wire   [31:0] empty_fu_762_p1;
wire   [2:0] fpclassify_result_i_i_fu_826_p11;
reg   [2:0] fpclassify_result_i_i_reg_2077;
wire    ap_CS_fsm_state18;
wire   [31:0] select_ln66_fu_850_p3;
wire    ap_CS_fsm_state19;
wire   [31:0] select_ln65_fu_858_p3;
wire   [31:0] select_ln63_cast_cast_fu_873_p3;
wire   [31:0] select_ln60_fu_881_p3;
wire   [31:0] select_ln68_fu_889_p3;
wire   [31:0] bitcast_ln397_fu_904_p1;
wire    ap_CS_fsm_state27;
wire   [0:0] grp_fu_357_p2;
reg   [0:0] cmp_i_i8_reg_2111;
wire    ap_CS_fsm_state28;
wire   [0:0] grp_fu_433_p2;
reg   [0:0] or_ln39_reg_2116;
wire    ap_CS_fsm_state29;
wire    ap_CS_fsm_state31;
wire   [31:0] dc_7_fu_1050_p9;
reg   [31:0] dc_7_reg_2142;
wire    ap_CS_fsm_state32;
wire   [31:0] result_2_fu_1196_p3;
wire    ap_CS_fsm_state33;
reg   [0:0] or_ln47_reg_2152;
wire    ap_CS_fsm_state34;
wire    ap_CS_fsm_state36;
reg   [7:0] xs_exp_1_reg_2178;
wire    ap_CS_fsm_state37;
wire   [22:0] trunc_ln342_1_fu_1366_p1;
reg   [22:0] trunc_ln342_1_reg_2184;
wire   [31:0] val_fu_1457_p3;
wire    ap_CS_fsm_state38;
wire   [0:0] and_ln388_1_fu_1480_p2;
reg   [0:0] and_ln388_1_reg_2194;
wire    ap_CS_fsm_state39;
wire   [0:0] and_ln387_1_fu_1501_p2;
reg   [0:0] and_ln387_1_reg_2199;
wire   [0:0] and_ln386_1_fu_1522_p2;
reg   [0:0] and_ln386_1_reg_2204;
wire   [31:0] zext_ln388_fu_1528_p1;
wire    ap_CS_fsm_state46;
wire   [31:0] zext_ln387_fu_1531_p1;
wire   [31:0] zext_ln386_fu_1534_p1;
wire   [0:0] and_ln25_2_fu_1551_p2;
reg   [0:0] and_ln25_2_reg_2224;
wire    ap_CS_fsm_state47;
wire   [0:0] or_ln25_2_fu_1557_p2;
reg   [0:0] or_ln25_2_reg_2230;
wire   [31:0] empty_33_fu_1748_p1;
wire    ap_CS_fsm_state51;
wire   [31:0] or_ln_fu_1840_p3;
wire    ap_CS_fsm_state52;
wire   [31:0] grp_fu_380_p2;
reg   [31:0] tmp_reg_2246;
wire    ap_CS_fsm_state59;
wire   [31:0] empty_32_fu_1848_p1;
wire    ap_CS_fsm_state60;
wire   [31:0] grp_fu_347_p2;
reg   [31:0] div_reg_2256;
wire    ap_CS_fsm_state68;
wire   [31:0] empty_30_fu_1855_p1;
wire    ap_CS_fsm_state73;
wire   [31:0] empty_29_fu_1859_p1;
wire    ap_CS_fsm_state78;
wire   [31:0] empty_28_fu_1863_p1;
reg   [31:0] ap_phi_mux_agg_result_0_phi_fu_268_p62;
reg   [31:0] agg_result_0_reg_261;
wire   [31:0] empty_31_fu_1851_p1;
wire    ap_CS_fsm_state69;
reg    ap_predicate_pred187_state78;
reg    ap_predicate_pred198_state78;
wire   [0:0] grp_fu_438_p2;
wire    ap_CS_fsm_state35;
wire   [0:0] and_ln48_fu_1204_p2;
wire   [0:0] or_ln38_fu_914_p2;
wire    ap_CS_fsm_state30;
wire   [0:0] and_ln40_fu_919_p2;
wire   [0:0] icmp_ln401_fu_562_p2;
wire   [63:0] zext_ln46_fu_924_p1;
wire   [63:0] zext_ln46_1_fu_1209_p1;
reg    mask_table_ce0_local;
reg   [4:0] mask_table_address0_local;
reg    one_half_minus_one_table_ce0_local;
reg   [4:0] one_half_minus_one_table_address0_local;
reg    index_table_ce0_local;
reg   [4:0] index_table_address0_local;
reg   [31:0] grp_fu_339_p0;
reg   [31:0] grp_fu_339_p1;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state74;
reg    ap_predicate_pred187_state74;
reg    ap_predicate_pred198_state74;
reg   [31:0] grp_fu_343_p0;
reg   [31:0] grp_fu_343_p1;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state70;
wire   [31:0] grp_fu_347_p1;
wire    ap_CS_fsm_state24;
reg   [31:0] grp_fu_357_p0;
reg   [31:0] grp_fu_357_p1;
wire   [7:0] grp_fu_403_p4;
wire   [7:0] grp_fu_418_p4;
wire   [0:0] grp_fu_427_p2;
wire   [7:0] grp_fu_460_p3;
wire   [31:0] zext_ln313_fu_568_p1;
wire   [22:0] trunc_ln388_fu_578_p1;
wire   [22:0] trunc_ln387_fu_588_p1;
wire   [22:0] trunc_ln386_fu_598_p1;
wire   [7:0] y_fp_exp_fu_624_p3;
wire   [7:0] x_fp_exp_fu_608_p3;
wire   [7:0] or_ln25_fu_636_p2;
wire   [22:0] y_fp_sig_fu_632_p1;
wire   [22:0] or_ln25_1_fu_648_p2;
wire   [0:0] ymaggreater_fu_678_p2;
wire   [0:0] xor_ln39_fu_684_p2;
wire   [0:0] y_fp_sign_fu_616_p3;
wire   [0:0] select_ln39_fu_690_p3;
wire   [31:0] xor_ln377_fu_714_p2;
wire   [31:0] xor_ln1_fu_728_p3;
wire   [31:0] xor_ln_fu_739_p3;
wire   [0:0] grp_fu_367_p2;
wire   [0:0] grp_fu_372_p2;
wire   [0:0] and_ln538_2_fu_772_p2;
wire   [0:0] grp_fu_362_p2;
wire   [0:0] xor_ln538_fu_786_p2;
wire   [0:0] or_ln538_1_fu_798_p2;
wire   [0:0] and_ln538_1_fu_766_p2;
wire   [0:0] xor_ln538_1_fu_804_p2;
wire   [0:0] and_ln538_3_fu_792_p2;
wire   [0:0] and_ln538_4_fu_810_p2;
wire   [2:0] fpclassify_result_i_i_fu_826_p8;
wire   [2:0] fpclassify_result_i_i_fu_826_p9;
wire   [2:0] fpclassify_result_i_i_fu_826_p10;
wire   [0:0] grp_fu_444_p3;
wire   [0:0] quiet_fu_866_p3;
wire   [31:0] grp_fu_351_p1;
wire   [31:0] grp_fu_354_p1;
wire   [31:0] select_ln397_fu_897_p3;
wire   [0:0] and_ln39_fu_908_p2;
wire   [4:0] grp_fu_451_p4;
wire   [0:0] grp_fu_473_p2;
wire   [31:0] t_7_fu_936_p3;
wire  signed [31:0] tmp_49_fu_956_p2;
wire   [23:0] zext_ln42_fu_948_p1;
wire   [0:0] tmp_49_fu_956_p3;
wire   [23:0] one_half_1_fu_963_p2;
wire   [23:0] one_half_2_fu_969_p3;
wire   [31:0] zext_ln42_1_fu_977_p1;
wire   [31:0] data_4_fu_981_p2;
wire   [22:0] trunc_ln301_fu_986_p1;
wire   [22:0] xor_ln77_fu_990_p2;
wire   [8:0] tmp_44_i1_fu_1002_p4;
wire   [22:0] xs_sig_1_fu_996_p2;
wire   [31:0] t_8_fu_1012_p3;
wire   [0:0] grp_fu_467_p2;
wire   [0:0] and_ln34_fu_931_p2;
wire   [0:0] or_ln34_fu_1024_p2;
wire   [0:0] grp_fu_479_p2;
wire   [0:0] xor_ln34_fu_1030_p2;
wire   [0:0] and_ln37_fu_1036_p2;
wire   [31:0] dc_7_fu_1050_p2;
wire   [31:0] dc_7_fu_1050_p6;
wire   [31:0] dc_7_fu_1050_p7;
wire   [1:0] dc_7_fu_1050_p8;
wire   [31:0] data_fu_1069_p1;
wire   [22:0] trunc_ln342_fu_1088_p1;
wire   [24:0] mantissa_fu_1092_p4;
wire   [7:0] xs_exp_fu_1080_p3;
wire   [8:0] zext_ln317_fu_1106_p1;
wire   [8:0] add_ln317_fu_1110_p2;
wire   [7:0] sub_ln18_fu_1124_p2;
wire   [0:0] tmp_51_fu_1116_p3;
wire  signed [8:0] sext_ln18_fu_1130_p1;
wire   [8:0] select_ln18_fu_1134_p3;
wire  signed [31:0] sext_ln18_1_fu_1142_p1;
wire   [78:0] zext_ln15_fu_1102_p1;
wire   [78:0] zext_ln18_fu_1146_p1;
wire   [78:0] lshr_ln18_fu_1150_p2;
wire   [78:0] shl_ln18_fu_1156_p2;
wire   [31:0] tmp_7_fu_1162_p4;
wire   [31:0] tmp_8_fu_1172_p4;
wire   [31:0] val_2_fu_1182_p3;
wire   [0:0] xs_sign_fu_1072_p3;
wire   [31:0] result_1_fu_1190_p2;
wire   [31:0] t_5_fu_1221_p3;
wire  signed [31:0] tmp_53_fu_1241_p2;
wire   [23:0] zext_ln42_2_fu_1233_p1;
wire   [0:0] tmp_53_fu_1241_p3;
wire   [23:0] one_half_4_fu_1248_p2;
wire   [23:0] one_half_5_fu_1254_p3;
wire   [31:0] zext_ln42_3_fu_1262_p1;
wire   [31:0] data_6_fu_1266_p2;
wire   [22:0] trunc_ln301_1_fu_1271_p1;
wire   [22:0] xor_ln77_1_fu_1275_p2;
wire   [8:0] tmp_44_i_fu_1287_p4;
wire   [22:0] xs_sig_2_fu_1281_p2;
wire   [31:0] t_6_fu_1297_p3;
wire   [0:0] and_ln34_1_fu_1216_p2;
wire   [0:0] or_ln34_1_fu_1309_p2;
wire   [0:0] xor_ln34_1_fu_1315_p2;
wire   [0:0] and_ln37_1_fu_1321_p2;
wire   [31:0] dc_8_fu_1335_p2;
wire   [31:0] dc_8_fu_1335_p6;
wire   [31:0] dc_8_fu_1335_p7;
wire   [1:0] dc_8_fu_1335_p8;
wire   [31:0] dc_8_fu_1335_p9;
wire   [31:0] data_7_fu_1354_p1;
wire   [24:0] mantissa_1_fu_1370_p4;
wire   [8:0] zext_ln317_1_fu_1383_p1;
wire   [8:0] add_ln317_1_fu_1386_p2;
wire   [7:0] sub_ln71_fu_1400_p2;
wire   [0:0] tmp_54_fu_1392_p3;
wire  signed [8:0] sext_ln71_fu_1405_p1;
wire   [8:0] select_ln71_fu_1409_p3;
wire  signed [31:0] sext_ln71_1_fu_1417_p1;
wire   [78:0] zext_ln68_fu_1379_p1;
wire   [78:0] zext_ln71_fu_1421_p1;
wire   [78:0] lshr_ln71_fu_1425_p2;
wire   [78:0] shl_ln71_fu_1431_p2;
wire   [31:0] tmp_9_fu_1437_p4;
wire   [31:0] tmp_10_fu_1447_p4;
wire   [0:0] or_ln388_fu_1465_p2;
wire   [0:0] or_ln388_1_fu_1470_p2;
wire   [0:0] and_ln388_fu_1474_p2;
wire   [0:0] or_ln387_fu_1486_p2;
wire   [0:0] or_ln387_1_fu_1491_p2;
wire   [0:0] and_ln387_fu_1495_p2;
wire   [0:0] or_ln386_fu_1507_p2;
wire   [0:0] or_ln386_1_fu_1512_p2;
wire   [0:0] and_ln386_fu_1516_p2;
wire   [0:0] and_ln25_1_fu_1541_p2;
wire   [0:0] grp_fu_485_p2;
wire   [0:0] xor_ln25_fu_1545_p2;
wire   [0:0] and_ln25_fu_1537_p2;
wire   [0:0] icmp_ln18_1_fu_1563_p2;
wire   [22:0] x_fp_sig_fu_1577_p4;
wire   [31:0] t_fu_1586_p4;
wire   [0:0] and_ln18_fu_1568_p2;
wire   [0:0] and_ln18_1_fu_1573_p2;
wire   [0:0] and_ln18_2_fu_1609_p2;
wire   [0:0] xor_ln25_1_fu_1620_p2;
wire   [0:0] and_ln18_4_fu_1625_p2;
wire   [0:0] and_ln18_6_fu_1637_p2;
wire   [0:0] xor_ln18_fu_1642_p2;
wire   [0:0] and_ln18_8_fu_1653_p2;
wire   [0:0] and_ln18_7_fu_1648_p2;
wire   [0:0] xor_ln18_1_fu_1657_p2;
wire   [0:0] or_ln18_fu_1669_p2;
wire   [0:0] or_ln18_1_fu_1674_p2;
wire   [0:0] xor_ln18_3_fu_1686_p2;
wire   [0:0] or_ln18_2_fu_1692_p2;
wire   [0:0] and_ln18_3_fu_1615_p2;
wire   [0:0] and_ln18_5_fu_1631_p2;
wire   [0:0] and_ln18_9_fu_1663_p2;
wire   [0:0] xor_ln18_2_fu_1680_p2;
wire   [0:0] and_ln18_10_fu_1698_p2;
wire   [31:0] res_fu_1595_p1;
wire   [31:0] res_31_fu_1718_p6;
wire   [31:0] res_31_fu_1718_p8;
wire   [31:0] res_31_fu_1718_p13;
wire   [4:0] res_31_fu_1718_p14;
wire   [31:0] res_31_fu_1718_p15;
wire   [0:0] xor_ln376_fu_1759_p2;
wire   [0:0] icmp_ln374_fu_1779_p2;
wire   [0:0] icmp_ln374_1_fu_1784_p2;
wire   [31:0] sign_3_fu_1799_p2;
wire   [31:0] sign_3_fu_1799_p4;
wire   [31:0] sign_3_fu_1799_p6;
wire   [31:0] sign_3_fu_1799_p9;
wire   [2:0] sign_3_fu_1799_p10;
wire   [31:0] sign_3_fu_1799_p11;
wire   [30:0] trunc_ln379_fu_1823_p1;
wire   [0:0] tmp_33_fu_1832_p3;
wire   [30:0] or_ln379_fu_1827_p2;
reg   [1:0] grp_fu_339_opcode;
reg   [4:0] grp_fu_357_opcode;
reg   [31:0] ap_return_preg;
reg   [77:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
wire    ap_ST_fsm_state43_blk;
wire    ap_ST_fsm_state44_blk;
wire    ap_ST_fsm_state45_blk;
wire    ap_ST_fsm_state46_blk;
wire    ap_ST_fsm_state47_blk;
wire    ap_ST_fsm_state48_blk;
wire    ap_ST_fsm_state49_blk;
wire    ap_ST_fsm_state50_blk;
wire    ap_ST_fsm_state51_blk;
wire    ap_ST_fsm_state52_blk;
wire    ap_ST_fsm_state53_blk;
wire    ap_ST_fsm_state54_blk;
wire    ap_ST_fsm_state55_blk;
wire    ap_ST_fsm_state56_blk;
wire    ap_ST_fsm_state57_blk;
wire    ap_ST_fsm_state58_blk;
wire    ap_ST_fsm_state59_blk;
wire    ap_ST_fsm_state60_blk;
wire    ap_ST_fsm_state61_blk;
wire    ap_ST_fsm_state62_blk;
wire    ap_ST_fsm_state63_blk;
wire    ap_ST_fsm_state64_blk;
wire    ap_ST_fsm_state65_blk;
wire    ap_ST_fsm_state66_blk;
wire    ap_ST_fsm_state67_blk;
wire    ap_ST_fsm_state68_blk;
wire    ap_ST_fsm_state69_blk;
wire    ap_ST_fsm_state70_blk;
wire    ap_ST_fsm_state71_blk;
wire    ap_ST_fsm_state72_blk;
wire    ap_ST_fsm_state73_blk;
wire    ap_ST_fsm_state74_blk;
wire    ap_ST_fsm_state75_blk;
wire    ap_ST_fsm_state76_blk;
wire    ap_ST_fsm_state77_blk;
wire    ap_ST_fsm_state78_blk;
wire  signed [2:0] fpclassify_result_i_i_fu_826_p1;
wire   [2:0] fpclassify_result_i_i_fu_826_p3;
wire   [2:0] fpclassify_result_i_i_fu_826_p5;
wire   [2:0] fpclassify_result_i_i_fu_826_p7;
wire   [0:0] tmp_49_fu_956_p0;
wire  signed [1:0] dc_7_fu_1050_p1;
wire   [1:0] dc_7_fu_1050_p3;
wire   [1:0] dc_7_fu_1050_p5;
wire   [0:0] tmp_53_fu_1241_p0;
wire  signed [1:0] dc_8_fu_1335_p1;
wire   [1:0] dc_8_fu_1335_p3;
wire   [1:0] dc_8_fu_1335_p5;
wire  signed [4:0] res_31_fu_1718_p1;
wire   [4:0] res_31_fu_1718_p3;
wire   [4:0] res_31_fu_1718_p5;
wire   [4:0] res_31_fu_1718_p7;
wire   [4:0] res_31_fu_1718_p9;
wire   [4:0] res_31_fu_1718_p11;
wire  signed [2:0] sign_3_fu_1799_p1;
wire   [2:0] sign_3_fu_1799_p3;
wire   [2:0] sign_3_fu_1799_p5;
wire   [2:0] sign_3_fu_1799_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 78'd1;
#0 ap_return_preg = 32'd0;
end

rv32_ooo_tick_fpu_compute_mask_table_ROM_AUTO_1R #(
    .DataWidth( 23 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
mask_table_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mask_table_address0_local),
    .ce0(mask_table_ce0_local),
    .q0(mask_table_q0)
);

rv32_ooo_tick_fpu_compute_one_half_minus_one_table_ROM_AUTO_1R #(
    .DataWidth( 23 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
one_half_minus_one_table_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(one_half_minus_one_table_address0_local),
    .ce0(one_half_minus_one_table_ce0_local),
    .q0(one_half_minus_one_table_q0)
);

rv32_ooo_tick_fpu_compute_index_table_ROM_AUTO_1R #(
    .DataWidth( 6 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
index_table_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(index_table_address0_local),
    .ce0(index_table_ce0_local),
    .q0(index_table_q0)
);

rv32_ooo_tick_faddfsub_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
faddfsub_32ns_32ns_32_4_full_dsp_1_U56(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_339_p0),
    .din1(grp_fu_339_p1),
    .opcode(grp_fu_339_opcode),
    .ce(1'b1),
    .dout(grp_fu_339_p2)
);

rv32_ooo_tick_fmul_32ns_32ns_32_3_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_max_dsp_1_U57(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_343_p0),
    .din1(grp_fu_343_p1),
    .ce(1'b1),
    .dout(grp_fu_343_p2)
);

rv32_ooo_tick_fdiv_32ns_32ns_32_9_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 9 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fdiv_32ns_32ns_32_9_no_dsp_1_U58(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(a_fu_512_p1),
    .din1(grp_fu_347_p1),
    .ce(1'b1),
    .dout(grp_fu_347_p2)
);

rv32_ooo_tick_uitofp_32ns_32_4_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
uitofp_32ns_32_4_no_dsp_1_U59(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(fpu_rs_s1_val),
    .ce(1'b1),
    .dout(grp_fu_351_p1)
);

rv32_ooo_tick_sitofp_32ns_32_4_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sitofp_32ns_32_4_no_dsp_1_U60(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(fpu_rs_s1_val),
    .ce(1'b1),
    .dout(grp_fu_354_p1)
);

rv32_ooo_tick_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U61(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_357_p0),
    .din1(grp_fu_357_p1),
    .ce(1'b1),
    .opcode(grp_fu_357_opcode),
    .dout(grp_fu_357_p2)
);

rv32_ooo_tick_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U62(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(a_fu_512_p1),
    .din1(32'd0),
    .ce(1'b1),
    .opcode(5'd8),
    .dout(grp_fu_362_p2)
);

rv32_ooo_tick_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U63(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(bitcast_ln327_fu_572_p1),
    .din1(32'd2139095040),
    .ce(1'b1),
    .opcode(5'd1),
    .dout(grp_fu_367_p2)
);

rv32_ooo_tick_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U64(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(bitcast_ln327_fu_572_p1),
    .din1(32'd8388608),
    .ce(1'b1),
    .opcode(5'd4),
    .dout(grp_fu_372_p2)
);

rv32_ooo_tick_fsqrt_32ns_32ns_32_8_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fsqrt_32ns_32ns_32_8_no_dsp_1_U65(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd0),
    .din1(a_fu_512_p1),
    .ce(1'b1),
    .dout(grp_fu_380_p2)
);

(* dissolve_hierarchy = "yes" *) rv32_ooo_tick_sparsemux_9_3_3_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h4 ),
    .din0_WIDTH( 3 ),
    .CASE1( 3'h2 ),
    .din1_WIDTH( 3 ),
    .CASE2( 3'h1 ),
    .din2_WIDTH( 3 ),
    .CASE3( 3'h0 ),
    .din3_WIDTH( 3 ),
    .def_WIDTH( 3 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 3 ))
sparsemux_9_3_3_1_1_U66(
    .din0(3'd2),
    .din1(3'd0),
    .din2(3'd1),
    .din3(fpclassify_result_i_i_fu_826_p8),
    .def(fpclassify_result_i_i_fu_826_p9),
    .sel(fpclassify_result_i_i_fu_826_p10),
    .dout(fpclassify_result_i_i_fu_826_p11)
);

rv32_ooo_tick_bitselect_1ns_32ns_32s_1_1_1 #(
    .DATAWIDTH( 32 ),
    .ADDRWIDTH( 32 ))
bitselect_1ns_32ns_32s_1_1_1_U67(
    .din(fpu_rs_s1_val),
    .sel(tmp_49_fu_956_p2),
    .dout(tmp_49_fu_956_p3)
);

(* dissolve_hierarchy = "yes" *) rv32_ooo_tick_sparsemux_7_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_7_2_32_1_1_U68(
    .din0(dc_7_fu_1050_p2),
    .din1(a_reg_1883),
    .din2(dc_7_fu_1050_p6),
    .def(dc_7_fu_1050_p7),
    .sel(dc_7_fu_1050_p8),
    .dout(dc_7_fu_1050_p9)
);

rv32_ooo_tick_bitselect_1ns_32ns_32s_1_1_1 #(
    .DATAWIDTH( 32 ),
    .ADDRWIDTH( 32 ))
bitselect_1ns_32ns_32s_1_1_1_U69(
    .din(fpu_rs_s1_val),
    .sel(tmp_53_fu_1241_p2),
    .dout(tmp_53_fu_1241_p3)
);

(* dissolve_hierarchy = "yes" *) rv32_ooo_tick_sparsemux_7_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_7_2_32_1_1_U70(
    .din0(dc_8_fu_1335_p2),
    .din1(a_reg_1883),
    .din2(dc_8_fu_1335_p6),
    .def(dc_8_fu_1335_p7),
    .sel(dc_8_fu_1335_p8),
    .dout(dc_8_fu_1335_p9)
);

(* dissolve_hierarchy = "yes" *) rv32_ooo_tick_sparsemux_13_5_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h10 ),
    .din0_WIDTH( 32 ),
    .CASE1( 5'h8 ),
    .din1_WIDTH( 32 ),
    .CASE2( 5'h4 ),
    .din2_WIDTH( 32 ),
    .CASE3( 5'h2 ),
    .din3_WIDTH( 32 ),
    .CASE4( 5'h1 ),
    .din4_WIDTH( 32 ),
    .CASE5( 5'h0 ),
    .din5_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
sparsemux_13_5_32_1_1_U71(
    .din0(res_fu_1595_p1),
    .din1(res_fu_1595_p1),
    .din2(res_31_fu_1718_p6),
    .din3(res_31_fu_1718_p8),
    .din4(a_reg_1883),
    .din5(b_reg_1898),
    .def(res_31_fu_1718_p13),
    .sel(res_31_fu_1718_p14),
    .dout(res_31_fu_1718_p15)
);

(* dissolve_hierarchy = "yes" *) rv32_ooo_tick_sparsemux_9_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h4 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h2 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h1 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h0 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_9_3_32_1_1_U72(
    .din0(sign_3_fu_1799_p2),
    .din1(sign_3_fu_1799_p4),
    .din2(sign_3_fu_1799_p6),
    .din3(32'd0),
    .def(sign_3_fu_1799_p9),
    .sel(sign_3_fu_1799_p10),
    .dout(sign_3_fu_1799_p11)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 32'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state69)) begin
            ap_return_preg <= ap_phi_mux_agg_result_0_phi_fu_268_p62;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((fpclassify_result_i_i_reg_2077 == 3'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        agg_result_0_reg_261 <= select_ln60_fu_881_p3;
    end else if (((fpclassify_result_i_i_reg_2077 == 3'd0) & (1'b1 == ap_CS_fsm_state19))) begin
        agg_result_0_reg_261 <= select_ln63_cast_cast_fu_873_p3;
    end else if (((fpclassify_result_i_i_reg_2077 == 3'd2) & (1'b1 == ap_CS_fsm_state19))) begin
        agg_result_0_reg_261 <= select_ln65_fu_858_p3;
    end else if (((fpclassify_result_i_i_reg_2077 == 3'd3) & (1'b1 == ap_CS_fsm_state19))) begin
        agg_result_0_reg_261 <= select_ln66_fu_850_p3;
    end else if (((fpu_rs_f3_load_load_fu_553_p1 == 3'd0) & (1'b1 == ap_CS_fsm_state46))) begin
        agg_result_0_reg_261 <= zext_ln386_fu_1534_p1;
    end else if (((fpu_rs_f3_load_load_fu_553_p1 == 3'd1) & (1'b1 == ap_CS_fsm_state46))) begin
        agg_result_0_reg_261 <= zext_ln387_fu_1531_p1;
    end else if (((fpu_rs_f3_load_load_fu_553_p1 == 3'd2) & (1'b1 == ap_CS_fsm_state46))) begin
        agg_result_0_reg_261 <= zext_ln388_fu_1528_p1;
    end else if (((~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd1) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd2) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd3) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd4) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (fpu_rs_f7_load_load_fu_549_p1 == 7'd120)) | (~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd1) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd2) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd3) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd4) & (ap_start == 1'b1) & (icmp_ln401_fu_562_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (fpu_rs_f7_load_load_fu_549_p1 == 7'd112)))) begin
        agg_result_0_reg_261 <= fpu_rs_s1_val;
    end else if ((~(fpclassify_result_i_i_reg_2077 == 3'd3) & ~(fpclassify_result_i_i_reg_2077 == 3'd2) & ~(fpclassify_result_i_i_reg_2077 == 3'd0) & ~(fpclassify_result_i_i_reg_2077 == 3'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        agg_result_0_reg_261 <= select_ln68_fu_889_p3;
    end else if (((1'd1 == and_ln40_fu_919_p2) & (1'b1 == ap_CS_fsm_state30))) begin
        agg_result_0_reg_261 <= 32'd2147483648;
    end else if (((or_ln38_fu_914_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state29))) begin
        agg_result_0_reg_261 <= 32'd2147483647;
    end else if ((((1'd1 == and_ln48_fu_1204_p2) & (1'b1 == ap_CS_fsm_state35)) | ((grp_fu_357_p2 == 1'd1) & (icmp_ln392_reg_1961 == 1'd1) & (1'b1 == ap_CS_fsm_state28)))) begin
        agg_result_0_reg_261 <= 32'd4294967295;
    end else if ((1'b1 == ap_CS_fsm_state38)) begin
        agg_result_0_reg_261 <= val_fu_1457_p3;
    end else if ((1'b1 == ap_CS_fsm_state33)) begin
        agg_result_0_reg_261 <= result_2_fu_1196_p3;
    end else if (((ap_predicate_pred198_state78 == 1'b1) & (1'b1 == ap_CS_fsm_state78))) begin
        agg_result_0_reg_261 <= empty_28_fu_1863_p1;
    end else if (((ap_predicate_pred187_state78 == 1'b1) & (1'b1 == ap_CS_fsm_state78))) begin
        agg_result_0_reg_261 <= empty_29_fu_1859_p1;
    end else if ((1'b1 == ap_CS_fsm_state73)) begin
        agg_result_0_reg_261 <= empty_30_fu_1855_p1;
    end else if ((~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd1) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd2) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd3) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd4) & (1'b1 == ap_CS_fsm_state69) & (fpu_rs_f7_load_load_fu_549_p1 == 7'd12))) begin
        agg_result_0_reg_261 <= empty_31_fu_1851_p1;
    end else if ((1'b1 == ap_CS_fsm_state60)) begin
        agg_result_0_reg_261 <= empty_32_fu_1848_p1;
    end else if ((1'b1 == ap_CS_fsm_state52)) begin
        agg_result_0_reg_261 <= or_ln_fu_1840_p3;
    end else if ((1'b1 == ap_CS_fsm_state51)) begin
        agg_result_0_reg_261 <= empty_33_fu_1748_p1;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        agg_result_0_reg_261 <= bitcast_ln397_fu_904_p1;
    end else if (((1'b1 == ap_CS_fsm_state17) & (fpu_rs_r4op_load_load_fu_539_p1 == 3'd1))) begin
        agg_result_0_reg_261 <= empty_fu_762_p1;
    end else if (((1'b1 == ap_CS_fsm_state17) & (fpu_rs_r4op_load_load_fu_539_p1 == 3'd2))) begin
        agg_result_0_reg_261 <= empty_25_fu_758_p1;
    end else if (((1'b1 == ap_CS_fsm_state9) & (fpu_rs_r4op_load_load_fu_539_p1 == 3'd3))) begin
        agg_result_0_reg_261 <= empty_26_fu_754_p1;
    end else if (((1'b1 == ap_CS_fsm_state9) & (fpu_rs_r4op_load_load_fu_539_p1 == 3'd4))) begin
        agg_result_0_reg_261 <= empty_27_fu_750_p1;
    end else if ((((grp_fu_438_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state34)) | (~(fpu_rs_f3_load_load_fu_553_p1 == 3'd2) & ~(fpu_rs_f3_load_load_fu_553_p1 == 3'd1) & ~(fpu_rs_f3_load_load_fu_553_p1 == 3'd0) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd1) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd2) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd3) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd4) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (fpu_rs_f7_load_load_fu_549_p1 == 7'd80)) | (~(fpu_rs_f7_load_load_fu_549_p1 == 7'd120) & ~(fpu_rs_f7_load_load_fu_549_p1 == 7'd112) & ~(fpu_rs_f7_load_load_fu_549_p1 == 7'd104) & ~(fpu_rs_f7_load_load_fu_549_p1 == 7'd96) & ~(fpu_rs_f7_load_load_fu_549_p1 == 7'd80) & ~(fpu_rs_f7_load_load_fu_549_p1 == 7'd20) & ~(fpu_rs_f7_load_load_fu_549_p1 == 7'd16) & ~(fpu_rs_f7_load_load_fu_549_p1 == 7'd44) & ~(fpu_rs_f7_load_load_fu_549_p1 == 7'd12) & ~(fpu_rs_f7_load_load_fu_549_p1 == 7'd8) & ~(fpu_rs_f7_load_load_fu_549_p1 == 7'd0) & ~(fpu_rs_f7_load_load_fu_549_p1 == 7'd4) & ~(fpu_rs_r4op_load_load_fu_539_p1 
    == 3'd1) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd2) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd3) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd4) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        agg_result_0_reg_261 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        a_reg_1883 <= a_fu_512_p1;
        b_reg_1898 <= b_fu_525_p1;
        c_reg_1910 <= c_fu_535_p1;
        icmp_ln18_2_reg_2018 <= icmp_ln18_2_fu_666_p2;
        icmp_ln18_3_reg_2024 <= icmp_ln18_3_fu_672_p2;
        icmp_ln18_reg_2012 <= icmp_ln18_fu_660_p2;
        icmp_ln25_1_reg_2006 <= icmp_ln25_1_fu_654_p2;
        icmp_ln25_reg_2000 <= icmp_ln25_fu_642_p2;
        icmp_ln386_1_reg_1919 <= icmp_ln386_1_fu_543_p2;
        icmp_ln386_2_reg_1985 <= grp_fu_412_p2;
        icmp_ln386_3_reg_1990 <= icmp_ln386_3_fu_602_p2;
        icmp_ln387_1_reg_1975 <= grp_fu_412_p2;
        icmp_ln387_2_reg_1980 <= icmp_ln387_2_fu_592_p2;
        icmp_ln388_1_reg_1965 <= grp_fu_412_p2;
        icmp_ln388_2_reg_1970 <= icmp_ln388_2_fu_582_p2;
        icmp_ln392_reg_1961 <= grp_fu_398_p2;
        icmp_ln397_reg_1956 <= grp_fu_398_p2;
        t_9_reg_1876 <= t_9_fu_508_p1;
        tmp_23_reg_2036 <= fpu_rs_s2_val[32'd31];
        tmp_24_reg_2042 <= xor_ln377_fu_714_p2[32'd31];
        x_fp_sig_1_reg_1870 <= x_fp_sig_1_fu_504_p1;
        x_fp_sign_reg_1995 <= fpu_rs_s1_val[32'd31];
        xor_ln361_reg_1934 <= grp_fu_392_p2;
        xor_ln362_reg_1929 <= grp_fu_392_p2;
        ymaggreater_1_reg_2030 <= ymaggreater_1_fu_698_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state47)) begin
        and_ln25_2_reg_2224 <= and_ln25_2_fu_1551_p2;
        or_ln25_2_reg_2230 <= or_ln25_2_fu_1557_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state39)) begin
        and_ln386_1_reg_2204 <= and_ln386_1_fu_1522_p2;
        and_ln387_1_reg_2199 <= and_ln387_1_fu_1501_p2;
        and_ln388_1_reg_2194 <= and_ln388_1_fu_1480_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_predicate_pred187_state74 <= (fpu_rs_f7_load_load_fu_549_p1 == 7'd4);
        ap_predicate_pred198_state74 <= (fpu_rs_f7_load_load_fu_549_p1 == 7'd0);
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state76)) begin
        ap_predicate_pred187_state77 <= (fpu_rs_f7_load_load_fu_549_p1 == 7'd4);
        ap_predicate_pred198_state77 <= (fpu_rs_f7_load_load_fu_549_p1 == 7'd0);
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state77)) begin
        ap_predicate_pred187_state78 <= (fpu_rs_f7_load_load_fu_549_p1 == 7'd4);
        ap_predicate_pred198_state78 <= (fpu_rs_f7_load_load_fu_549_p1 == 7'd0);
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        cmp_i_i8_reg_2111 <= grp_fu_357_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        dc_7_reg_2142 <= dc_7_fu_1050_p9;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state68)) begin
        div_reg_2256 <= grp_fu_347_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        fpclassify_result_i_i_reg_2077 <= fpclassify_result_i_i_fu_826_p11;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state29)) begin
        or_ln39_reg_2116 <= grp_fu_433_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state34)) begin
        or_ln47_reg_2152 <= grp_fu_433_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state72) | ((1'b1 == ap_CS_fsm_state12) & (fpu_rs_r4op_load_load_fu_539_p1 == 3'd1)) | ((1'b1 == ap_CS_fsm_state12) & (fpu_rs_r4op_load_load_fu_539_p1 == 3'd2)) | ((1'b1 == ap_CS_fsm_state4) & (fpu_rs_r4op_load_load_fu_539_p1 == 3'd3)) | ((1'b1 == ap_CS_fsm_state4) & (fpu_rs_r4op_load_load_fu_539_p1 == 3'd4)))) begin
        reg_490 <= grp_fu_343_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_state77) & (ap_predicate_pred198_state77 == 1'b1)) | ((1'b1 == ap_CS_fsm_state77) & (ap_predicate_pred187_state77 == 1'b1)) | ((1'b1 == ap_CS_fsm_state16) & (fpu_rs_r4op_load_load_fu_539_p1 == 3'd1)) | ((1'b1 == ap_CS_fsm_state16) & (fpu_rs_r4op_load_load_fu_539_p1 == 3'd2)) | ((1'b1 == ap_CS_fsm_state8) & (fpu_rs_r4op_load_load_fu_539_p1 == 3'd3)) | ((1'b1 == ap_CS_fsm_state8) & (fpu_rs_r4op_load_load_fu_539_p1 == 3'd4)))) begin
        reg_495 <= grp_fu_339_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state59)) begin
        tmp_reg_2246 <= grp_fu_380_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        trunc_ln342_1_reg_2184 <= trunc_ln342_1_fu_1366_p1;
        xs_exp_1_reg_2178 <= {{data_7_fu_1354_p1[30:23]}};
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state40_blk = 1'b0;

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

assign ap_ST_fsm_state43_blk = 1'b0;

assign ap_ST_fsm_state44_blk = 1'b0;

assign ap_ST_fsm_state45_blk = 1'b0;

assign ap_ST_fsm_state46_blk = 1'b0;

assign ap_ST_fsm_state47_blk = 1'b0;

assign ap_ST_fsm_state48_blk = 1'b0;

assign ap_ST_fsm_state49_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state50_blk = 1'b0;

assign ap_ST_fsm_state51_blk = 1'b0;

assign ap_ST_fsm_state52_blk = 1'b0;

assign ap_ST_fsm_state53_blk = 1'b0;

assign ap_ST_fsm_state54_blk = 1'b0;

assign ap_ST_fsm_state55_blk = 1'b0;

assign ap_ST_fsm_state56_blk = 1'b0;

assign ap_ST_fsm_state57_blk = 1'b0;

assign ap_ST_fsm_state58_blk = 1'b0;

assign ap_ST_fsm_state59_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state60_blk = 1'b0;

assign ap_ST_fsm_state61_blk = 1'b0;

assign ap_ST_fsm_state62_blk = 1'b0;

assign ap_ST_fsm_state63_blk = 1'b0;

assign ap_ST_fsm_state64_blk = 1'b0;

assign ap_ST_fsm_state65_blk = 1'b0;

assign ap_ST_fsm_state66_blk = 1'b0;

assign ap_ST_fsm_state67_blk = 1'b0;

assign ap_ST_fsm_state68_blk = 1'b0;

assign ap_ST_fsm_state69_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state70_blk = 1'b0;

assign ap_ST_fsm_state71_blk = 1'b0;

assign ap_ST_fsm_state72_blk = 1'b0;

assign ap_ST_fsm_state73_blk = 1'b0;

assign ap_ST_fsm_state74_blk = 1'b0;

assign ap_ST_fsm_state75_blk = 1'b0;

assign ap_ST_fsm_state76_blk = 1'b0;

assign ap_ST_fsm_state77_blk = 1'b0;

assign ap_ST_fsm_state78_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state69) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd1) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd2) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd3) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd4) & (1'b1 == ap_CS_fsm_state69) & (fpu_rs_f7_load_load_fu_549_p1 == 7'd12))) begin
        ap_phi_mux_agg_result_0_phi_fu_268_p62 = empty_31_fu_1851_p1;
    end else begin
        ap_phi_mux_agg_result_0_phi_fu_268_p62 = agg_result_0_reg_261;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state69)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state69)) begin
        ap_return = ap_phi_mux_agg_result_0_phi_fu_268_p62;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    if ((((ap_predicate_pred187_state74 == 1'b1) & (1'b1 == ap_CS_fsm_state74)) | ((1'b1 == ap_CS_fsm_state13) & (fpu_rs_r4op_load_load_fu_539_p1 == 3'd2)) | ((1'b1 == ap_CS_fsm_state5) & (fpu_rs_r4op_load_load_fu_539_p1 == 3'd4)))) begin
        grp_fu_339_opcode = 2'd1;
    end else if ((((ap_predicate_pred198_state74 == 1'b1) & (1'b1 == ap_CS_fsm_state74)) | ((1'b1 == ap_CS_fsm_state13) & (fpu_rs_r4op_load_load_fu_539_p1 == 3'd1)) | ((1'b1 == ap_CS_fsm_state5) & (fpu_rs_r4op_load_load_fu_539_p1 == 3'd3)))) begin
        grp_fu_339_opcode = 2'd0;
    end else begin
        grp_fu_339_opcode = 'bx;
    end
end

always @ (*) begin
    if ((((ap_predicate_pred198_state74 == 1'b1) & (1'b1 == ap_CS_fsm_state74)) | ((ap_predicate_pred187_state74 == 1'b1) & (1'b1 == ap_CS_fsm_state74)))) begin
        grp_fu_339_p0 = a_reg_1883;
    end else if ((((1'b1 == ap_CS_fsm_state13) & (fpu_rs_r4op_load_load_fu_539_p1 == 3'd1)) | ((1'b1 == ap_CS_fsm_state13) & (fpu_rs_r4op_load_load_fu_539_p1 == 3'd2)) | ((1'b1 == ap_CS_fsm_state5) & (fpu_rs_r4op_load_load_fu_539_p1 == 3'd3)) | ((1'b1 == ap_CS_fsm_state5) & (fpu_rs_r4op_load_load_fu_539_p1 == 3'd4)))) begin
        grp_fu_339_p0 = reg_490;
    end else begin
        grp_fu_339_p0 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_predicate_pred198_state74 == 1'b1) & (1'b1 == ap_CS_fsm_state74)) | ((ap_predicate_pred187_state74 == 1'b1) & (1'b1 == ap_CS_fsm_state74)))) begin
        grp_fu_339_p1 = b_reg_1898;
    end else if ((((1'b1 == ap_CS_fsm_state13) & (fpu_rs_r4op_load_load_fu_539_p1 == 3'd1)) | ((1'b1 == ap_CS_fsm_state13) & (fpu_rs_r4op_load_load_fu_539_p1 == 3'd2)) | ((1'b1 == ap_CS_fsm_state5) & (fpu_rs_r4op_load_load_fu_539_p1 == 3'd3)) | ((1'b1 == ap_CS_fsm_state5) & (fpu_rs_r4op_load_load_fu_539_p1 == 3'd4)))) begin
        grp_fu_339_p1 = c_reg_1910;
    end else begin
        grp_fu_339_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state70) | ((1'b1 == ap_CS_fsm_state10) & (fpu_rs_r4op_load_load_fu_539_p1 == 3'd1)) | ((1'b1 == ap_CS_fsm_state10) & (fpu_rs_r4op_load_load_fu_539_p1 == 3'd2)))) begin
        grp_fu_343_p0 = a_reg_1883;
    end else if ((((1'b1 == ap_CS_fsm_state2) & (fpu_rs_r4op_load_load_fu_539_p1 == 3'd3)) | ((1'b1 == ap_CS_fsm_state2) & (fpu_rs_r4op_load_load_fu_539_p1 == 3'd4)))) begin
        grp_fu_343_p0 = b_reg_1898;
    end else begin
        grp_fu_343_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state70) | ((1'b1 == ap_CS_fsm_state10) & (fpu_rs_r4op_load_load_fu_539_p1 == 3'd1)) | ((1'b1 == ap_CS_fsm_state10) & (fpu_rs_r4op_load_load_fu_539_p1 == 3'd2)))) begin
        grp_fu_343_p1 = b_reg_1898;
    end else if (((1'b1 == ap_CS_fsm_state2) & (fpu_rs_r4op_load_load_fu_539_p1 == 3'd3))) begin
        grp_fu_343_p1 = bitcast_ln361_fu_745_p1;
    end else if (((1'b1 == ap_CS_fsm_state2) & (fpu_rs_r4op_load_load_fu_539_p1 == 3'd4))) begin
        grp_fu_343_p1 = bitcast_ln362_fu_734_p1;
    end else begin
        grp_fu_343_p1 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln392_reg_1961 == 1'd0) & (1'b1 == ap_CS_fsm_state28)) | ((grp_fu_438_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state34)))) begin
        grp_fu_357_opcode = 5'd3;
    end else if (((~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd1) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd2) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd3) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd4) & (ap_start == 1'b1) & (fpu_rs_f3_load_load_fu_553_p1 == 3'd0) & (1'b1 == ap_CS_fsm_state1) & (fpu_rs_f7_load_load_fu_549_p1 == 7'd80)) | ((or_ln38_fu_914_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state29)))) begin
        grp_fu_357_opcode = 5'd5;
    end else if ((((grp_fu_357_p2 == 1'd0) & (icmp_ln392_reg_1961 == 1'd1) & (1'b1 == ap_CS_fsm_state28)) | (~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd1) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd2) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd3) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd4) & (ap_start == 1'b1) & (fpu_rs_f3_load_load_fu_553_p1 == 3'd1) & (1'b1 == ap_CS_fsm_state1) & (fpu_rs_f7_load_load_fu_549_p1 == 7'd80)))) begin
        grp_fu_357_opcode = 5'd4;
    end else if ((~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd1) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd2) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd3) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd4) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (fpu_rs_f7_load_load_fu_549_p1 == 7'd96))) begin
        grp_fu_357_opcode = 5'd8;
    end else if (((~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd1) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd2) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd3) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd4) & (ap_start == 1'b1) & (icmp_ln401_fu_562_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (fpu_rs_f7_load_load_fu_549_p1 == 7'd112)) | (~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd1) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd2) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd3) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd4) & (ap_start == 1'b1) & (fpu_rs_f3_load_load_fu_553_p1 == 3'd2) & (1'b1 == ap_CS_fsm_state1) & (fpu_rs_f7_load_load_fu_549_p1 == 7'd80)))) begin
        grp_fu_357_opcode = 5'd1;
    end else begin
        grp_fu_357_opcode = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state29) | ((grp_fu_357_p2 == 1'd0) & (icmp_ln392_reg_1961 == 1'd1) & (1'b1 == ap_CS_fsm_state28)) | ((icmp_ln392_reg_1961 == 1'd0) & (1'b1 == ap_CS_fsm_state28)))) begin
        grp_fu_357_p0 = a_reg_1883;
    end else if (((~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd1) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd2) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd3) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd4) & (1'b1 == ap_CS_fsm_state1) & (fpu_rs_f7_load_load_fu_549_p1 == 7'd96)) | (~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd1) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd2) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd3) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd4) & (icmp_ln401_fu_562_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (fpu_rs_f7_load_load_fu_549_p1 == 7'd112)) | (~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd1) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd2) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd3) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd4) & (fpu_rs_f3_load_load_fu_553_p1 == 3'd2) & (1'b1 == ap_CS_fsm_state1) & (fpu_rs_f7_load_load_fu_549_p1 == 7'd80)) | (~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd1) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd2) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd3) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd4) & (fpu_rs_f3_load_load_fu_553_p1 
    == 3'd1) & (1'b1 == ap_CS_fsm_state1) & (fpu_rs_f7_load_load_fu_549_p1 == 7'd80)) | (~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd1) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd2) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd3) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd4) & (fpu_rs_f3_load_load_fu_553_p1 == 3'd0) & (1'b1 == ap_CS_fsm_state1) & (fpu_rs_f7_load_load_fu_549_p1 == 7'd80)))) begin
        grp_fu_357_p0 = a_fu_512_p1;
    end else begin
        grp_fu_357_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state34)) begin
        grp_fu_357_p1 = 32'd1333788672;
    end else if ((1'b1 == ap_CS_fsm_state29)) begin
        grp_fu_357_p1 = 32'd3472883712;
    end else if (((icmp_ln392_reg_1961 == 1'd0) & (1'b1 == ap_CS_fsm_state28))) begin
        grp_fu_357_p1 = 32'd1325400064;
    end else if (((~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd1) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd2) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd3) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd4) & (fpu_rs_f3_load_load_fu_553_p1 == 3'd2) & (1'b1 == ap_CS_fsm_state1) & (fpu_rs_f7_load_load_fu_549_p1 == 7'd80)) | (~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd1) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd2) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd3) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd4) & (fpu_rs_f3_load_load_fu_553_p1 == 3'd1) & (1'b1 == ap_CS_fsm_state1) & (fpu_rs_f7_load_load_fu_549_p1 == 7'd80)) | (~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd1) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd2) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd3) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd4) & (fpu_rs_f3_load_load_fu_553_p1 == 3'd0) & (1'b1 == ap_CS_fsm_state1) & (fpu_rs_f7_load_load_fu_549_p1 == 7'd80)))) begin
        grp_fu_357_p1 = b_fu_525_p1;
    end else if ((((grp_fu_357_p2 == 1'd0) & (icmp_ln392_reg_1961 == 1'd1) & (1'b1 == ap_CS_fsm_state28)) | (~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd1) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd2) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd3) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd4) & (1'b1 == ap_CS_fsm_state1) & (fpu_rs_f7_load_load_fu_549_p1 == 7'd96)) | (~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd1) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd2) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd3) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd4) & (icmp_ln401_fu_562_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (fpu_rs_f7_load_load_fu_549_p1 == 7'd112)))) begin
        grp_fu_357_p1 = 32'd0;
    end else begin
        grp_fu_357_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state36)) begin
        index_table_address0_local = zext_ln46_1_fu_1209_p1;
    end else if ((1'b1 == ap_CS_fsm_state31)) begin
        index_table_address0_local = zext_ln46_fu_924_p1;
    end else begin
        index_table_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state31))) begin
        index_table_ce0_local = 1'b1;
    end else begin
        index_table_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state36)) begin
        mask_table_address0_local = zext_ln46_1_fu_1209_p1;
    end else if ((1'b1 == ap_CS_fsm_state31)) begin
        mask_table_address0_local = zext_ln46_fu_924_p1;
    end else begin
        mask_table_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state31))) begin
        mask_table_ce0_local = 1'b1;
    end else begin
        mask_table_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state36)) begin
        one_half_minus_one_table_address0_local = zext_ln46_1_fu_1209_p1;
    end else if ((1'b1 == ap_CS_fsm_state31)) begin
        one_half_minus_one_table_address0_local = zext_ln46_fu_924_p1;
    end else begin
        one_half_minus_one_table_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state31))) begin
        one_half_minus_one_table_ce0_local = 1'b1;
    end else begin
        one_half_minus_one_table_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd1) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd2) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd3) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd4) & (fpu_rs_f3_load_load_fu_553_p1 == 3'd2) & (fpu_rs_f7_load_load_fu_549_p1 == 7'd80)) | (~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd1) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd2) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd3) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd4) & (fpu_rs_f3_load_load_fu_553_p1 == 3'd1) & (fpu_rs_f7_load_load_fu_549_p1 == 7'd80))) | (~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd1) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd2) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd3) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd4) & (fpu_rs_f3_load_load_fu_553_p1 == 3'd0) & (fpu_rs_f7_load_load_fu_549_p1 == 7'd80))))) begin
                ap_NS_fsm = ap_ST_fsm_state39;
            end else if ((~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd1) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd2) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd3) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd4) & (ap_start == 1'b1) & (icmp_ln401_fu_562_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (fpu_rs_f7_load_load_fu_549_p1 == 7'd112))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & ((~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd1) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd2) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd3) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd4) & (fpu_rs_f7_load_load_fu_549_p1 == 7'd0)) | (~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd1) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd2) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd3) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd4) & (fpu_rs_f7_load_load_fu_549_p1 == 7'd4))))) begin
                ap_NS_fsm = ap_ST_fsm_state74;
            end else if ((~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd1) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd2) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd3) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd4) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (fpu_rs_f7_load_load_fu_549_p1 == 7'd8))) begin
                ap_NS_fsm = ap_ST_fsm_state70;
            end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((~(fpu_rs_f7_load_load_fu_549_p1 == 7'd112) & ~(fpu_rs_f7_load_load_fu_549_p1 == 7'd104) & ~(fpu_rs_f7_load_load_fu_549_p1 == 7'd96) & ~(fpu_rs_f7_load_load_fu_549_p1 == 7'd80) & ~(fpu_rs_f7_load_load_fu_549_p1 == 7'd20) & ~(fpu_rs_f7_load_load_fu_549_p1 == 7'd16) & ~(fpu_rs_f7_load_load_fu_549_p1 == 7'd44) & ~(fpu_rs_f7_load_load_fu_549_p1 == 7'd12) & ~(fpu_rs_f7_load_load_fu_549_p1 == 7'd8) & ~(fpu_rs_f7_load_load_fu_549_p1 == 7'd0) & ~(fpu_rs_f7_load_load_fu_549_p1 == 7'd4) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd1) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd2) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd3) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd4)) | (~(fpu_rs_f7_load_load_fu_549_p1 == 7'd104) & ~(fpu_rs_f7_load_load_fu_549_p1 == 7'd96) & ~(fpu_rs_f7_load_load_fu_549_p1 == 7'd80) & ~(fpu_rs_f7_load_load_fu_549_p1 == 7'd20) & ~(fpu_rs_f7_load_load_fu_549_p1 == 7'd16) & ~(fpu_rs_f7_load_load_fu_549_p1 == 7'd44) & ~(fpu_rs_f7_load_load_fu_549_p1 == 7'd12) 
    & ~(fpu_rs_f7_load_load_fu_549_p1 == 7'd8) & ~(fpu_rs_f7_load_load_fu_549_p1 == 7'd0) & ~(fpu_rs_f7_load_load_fu_549_p1 == 7'd4) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd1) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd2) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd3) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd4) & (icmp_ln401_fu_562_p2 == 1'd0))) | (~(fpu_rs_f3_load_load_fu_553_p1 == 3'd2) & ~(fpu_rs_f3_load_load_fu_553_p1 == 3'd1) & ~(fpu_rs_f3_load_load_fu_553_p1 == 3'd0) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd1) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd2) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd3) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd4) & (fpu_rs_f7_load_load_fu_549_p1 == 7'd80))))) begin
                ap_NS_fsm = ap_ST_fsm_state69;
            end else if ((~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd1) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd2) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd3) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd4) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (fpu_rs_f7_load_load_fu_549_p1 == 7'd12))) begin
                ap_NS_fsm = ap_ST_fsm_state61;
            end else if ((~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd1) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd2) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd3) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd4) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (fpu_rs_f7_load_load_fu_549_p1 == 7'd44))) begin
                ap_NS_fsm = ap_ST_fsm_state53;
            end else if ((~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd1) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd2) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd3) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd4) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (fpu_rs_f7_load_load_fu_549_p1 == 7'd16))) begin
                ap_NS_fsm = ap_ST_fsm_state52;
            end else if ((~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd1) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd2) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd3) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd4) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (fpu_rs_f7_load_load_fu_549_p1 == 7'd20))) begin
                ap_NS_fsm = ap_ST_fsm_state47;
            end else if ((~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd1) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd2) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd3) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd4) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (fpu_rs_f7_load_load_fu_549_p1 == 7'd96))) begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end else if ((~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd1) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd2) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd3) & ~(fpu_rs_r4op_load_load_fu_539_p1 == 3'd4) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (fpu_rs_f7_load_load_fu_549_p1 == 7'd104))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & ((fpu_rs_r4op_load_load_fu_539_p1 == 3'd1) | (fpu_rs_r4op_load_load_fu_539_p1 == 3'd2)))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & ((fpu_rs_r4op_load_load_fu_539_p1 == 3'd3) | (fpu_rs_r4op_load_load_fu_539_p1 == 3'd4)))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state28 : begin
            if (((grp_fu_357_p2 == 1'd1) & (icmp_ln392_reg_1961 == 1'd1) & (1'b1 == ap_CS_fsm_state28))) begin
                ap_NS_fsm = ap_ST_fsm_state69;
            end else if (((grp_fu_357_p2 == 1'd0) & (icmp_ln392_reg_1961 == 1'd1) & (1'b1 == ap_CS_fsm_state28))) begin
                ap_NS_fsm = ap_ST_fsm_state34;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state29;
            end
        end
        ap_ST_fsm_state29 : begin
            if (((or_ln38_fu_914_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state29))) begin
                ap_NS_fsm = ap_ST_fsm_state69;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state30;
            end
        end
        ap_ST_fsm_state30 : begin
            if (((1'd1 == and_ln40_fu_919_p2) & (1'b1 == ap_CS_fsm_state30))) begin
                ap_NS_fsm = ap_ST_fsm_state69;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state31;
            end
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state34 : begin
            if (((grp_fu_438_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state34))) begin
                ap_NS_fsm = ap_ST_fsm_state69;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state35;
            end
        end
        ap_ST_fsm_state35 : begin
            if (((1'd1 == and_ln48_fu_1204_p2) & (1'b1 == ap_CS_fsm_state35))) begin
                ap_NS_fsm = ap_ST_fsm_state69;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state36;
            end
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state62;
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            ap_NS_fsm = ap_ST_fsm_state65;
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state66;
        end
        ap_ST_fsm_state66 : begin
            ap_NS_fsm = ap_ST_fsm_state67;
        end
        ap_ST_fsm_state67 : begin
            ap_NS_fsm = ap_ST_fsm_state68;
        end
        ap_ST_fsm_state68 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state69 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        ap_ST_fsm_state70 : begin
            ap_NS_fsm = ap_ST_fsm_state71;
        end
        ap_ST_fsm_state71 : begin
            ap_NS_fsm = ap_ST_fsm_state72;
        end
        ap_ST_fsm_state72 : begin
            ap_NS_fsm = ap_ST_fsm_state73;
        end
        ap_ST_fsm_state73 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state74 : begin
            ap_NS_fsm = ap_ST_fsm_state75;
        end
        ap_ST_fsm_state75 : begin
            ap_NS_fsm = ap_ST_fsm_state76;
        end
        ap_ST_fsm_state76 : begin
            ap_NS_fsm = ap_ST_fsm_state77;
        end
        ap_ST_fsm_state77 : begin
            ap_NS_fsm = ap_ST_fsm_state78;
        end
        ap_ST_fsm_state78 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_fu_512_p1 = fpu_rs_s1_val;

assign add_ln317_1_fu_1386_p2 = ($signed(zext_ln317_1_fu_1383_p1) + $signed(9'd385));

assign add_ln317_fu_1110_p2 = ($signed(zext_ln317_fu_1106_p1) + $signed(9'd385));

assign and_ln18_10_fu_1698_p2 = (or_ln18_2_fu_1692_p2 & and_ln18_1_fu_1573_p2);

assign and_ln18_1_fu_1573_p2 = (icmp_ln18_3_reg_2024 & icmp_ln18_2_reg_2018);

assign and_ln18_2_fu_1609_p2 = (and_ln18_fu_1568_p2 & and_ln18_1_fu_1573_p2);

assign and_ln18_3_fu_1615_p2 = (and_ln25_2_reg_2224 & and_ln18_2_fu_1609_p2);

assign and_ln18_4_fu_1625_p2 = (xor_ln25_1_fu_1620_p2 & and_ln18_1_fu_1573_p2);

assign and_ln18_5_fu_1631_p2 = (and_ln18_fu_1568_p2 & and_ln18_4_fu_1625_p2);

assign and_ln18_6_fu_1637_p2 = (icmp_ln18_reg_2012 & icmp_ln18_1_fu_1563_p2);

assign and_ln18_7_fu_1648_p2 = (xor_ln18_fu_1642_p2 & and_ln25_2_reg_2224);

assign and_ln18_8_fu_1653_p2 = (icmp_ln18_3_reg_2024 & icmp_ln18_2_reg_2018);

assign and_ln18_9_fu_1663_p2 = (xor_ln18_1_fu_1657_p2 & and_ln18_7_fu_1648_p2);

assign and_ln18_fu_1568_p2 = (icmp_ln18_reg_2012 & icmp_ln18_1_fu_1563_p2);

assign and_ln25_1_fu_1541_p2 = (icmp_ln25_reg_2000 & icmp_ln25_1_reg_2006);

assign and_ln25_2_fu_1551_p2 = (xor_ln25_fu_1545_p2 & grp_fu_485_p2);

assign and_ln25_fu_1537_p2 = (icmp_ln25_reg_2000 & icmp_ln25_1_reg_2006);

assign and_ln34_1_fu_1216_p2 = (icmp_ln386_1_reg_1919 & grp_fu_473_p2);

assign and_ln34_fu_931_p2 = (icmp_ln386_1_reg_1919 & grp_fu_473_p2);

assign and_ln37_1_fu_1321_p2 = (xor_ln34_1_fu_1315_p2 & grp_fu_479_p2);

assign and_ln37_fu_1036_p2 = (xor_ln34_fu_1030_p2 & grp_fu_479_p2);

assign and_ln386_1_fu_1522_p2 = (grp_fu_357_p2 & and_ln386_fu_1516_p2);

assign and_ln386_fu_1516_p2 = (or_ln386_fu_1507_p2 & or_ln386_1_fu_1512_p2);

assign and_ln387_1_fu_1501_p2 = (grp_fu_357_p2 & and_ln387_fu_1495_p2);

assign and_ln387_fu_1495_p2 = (or_ln387_fu_1486_p2 & or_ln387_1_fu_1491_p2);

assign and_ln388_1_fu_1480_p2 = (grp_fu_357_p2 & and_ln388_fu_1474_p2);

assign and_ln388_fu_1474_p2 = (or_ln388_fu_1465_p2 & or_ln388_1_fu_1470_p2);

assign and_ln39_fu_908_p2 = (grp_fu_433_p2 & grp_fu_357_p2);

assign and_ln40_fu_919_p2 = (or_ln39_reg_2116 & grp_fu_357_p2);

assign and_ln48_fu_1204_p2 = (or_ln47_reg_2152 & grp_fu_357_p2);

assign and_ln538_1_fu_766_p2 = (grp_fu_433_p2 & grp_fu_367_p2);

assign and_ln538_2_fu_772_p2 = (grp_fu_433_p2 & grp_fu_372_p2);

assign and_ln538_3_fu_792_p2 = (xor_ln538_fu_786_p2 & grp_fu_362_p2);

assign and_ln538_4_fu_810_p2 = (xor_ln538_1_fu_804_p2 & and_ln538_1_fu_766_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state34 = ap_CS_fsm[32'd33];

assign ap_CS_fsm_state35 = ap_CS_fsm[32'd34];

assign ap_CS_fsm_state36 = ap_CS_fsm[32'd35];

assign ap_CS_fsm_state37 = ap_CS_fsm[32'd36];

assign ap_CS_fsm_state38 = ap_CS_fsm[32'd37];

assign ap_CS_fsm_state39 = ap_CS_fsm[32'd38];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state46 = ap_CS_fsm[32'd45];

assign ap_CS_fsm_state47 = ap_CS_fsm[32'd46];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state51 = ap_CS_fsm[32'd50];

assign ap_CS_fsm_state52 = ap_CS_fsm[32'd51];

assign ap_CS_fsm_state59 = ap_CS_fsm[32'd58];

assign ap_CS_fsm_state60 = ap_CS_fsm[32'd59];

assign ap_CS_fsm_state68 = ap_CS_fsm[32'd67];

assign ap_CS_fsm_state69 = ap_CS_fsm[32'd68];

assign ap_CS_fsm_state70 = ap_CS_fsm[32'd69];

assign ap_CS_fsm_state72 = ap_CS_fsm[32'd71];

assign ap_CS_fsm_state73 = ap_CS_fsm[32'd72];

assign ap_CS_fsm_state74 = ap_CS_fsm[32'd73];

assign ap_CS_fsm_state76 = ap_CS_fsm[32'd75];

assign ap_CS_fsm_state77 = ap_CS_fsm[32'd76];

assign ap_CS_fsm_state78 = ap_CS_fsm[32'd77];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign b_fu_525_p1 = fpu_rs_s2_val;

assign bitcast_ln327_fu_572_p1 = zext_ln313_fu_568_p1;

assign bitcast_ln361_fu_745_p1 = xor_ln_fu_739_p3;

assign bitcast_ln362_fu_734_p1 = xor_ln1_fu_728_p3;

assign bitcast_ln397_fu_904_p1 = select_ln397_fu_897_p3;

assign c_fu_535_p1 = fpu_rs_s3_val;

assign data_4_fu_981_p2 = (fpu_rs_s1_val + zext_ln42_1_fu_977_p1);

assign data_6_fu_1266_p2 = (fpu_rs_s1_val + zext_ln42_3_fu_1262_p1);

assign data_7_fu_1354_p1 = dc_8_fu_1335_p9;

assign data_fu_1069_p1 = dc_7_reg_2142;

assign dc_7_fu_1050_p2 = t_7_fu_936_p3;

assign dc_7_fu_1050_p6 = t_8_fu_1012_p3;

assign dc_7_fu_1050_p7 = 'bx;

assign dc_7_fu_1050_p8 = {{or_ln34_fu_1024_p2}, {and_ln37_fu_1036_p2}};

assign dc_8_fu_1335_p2 = t_5_fu_1221_p3;

assign dc_8_fu_1335_p6 = t_6_fu_1297_p3;

assign dc_8_fu_1335_p7 = 'bx;

assign dc_8_fu_1335_p8 = {{or_ln34_1_fu_1309_p2}, {and_ln37_1_fu_1321_p2}};

assign empty_25_fu_758_p1 = reg_495;

assign empty_26_fu_754_p1 = reg_495;

assign empty_27_fu_750_p1 = reg_495;

assign empty_28_fu_1863_p1 = reg_495;

assign empty_29_fu_1859_p1 = reg_495;

assign empty_30_fu_1855_p1 = reg_490;

assign empty_31_fu_1851_p1 = div_reg_2256;

assign empty_32_fu_1848_p1 = tmp_reg_2246;

assign empty_33_fu_1748_p1 = res_31_fu_1718_p15;

assign empty_fu_762_p1 = reg_495;

assign fpclassify_result_i_i_fu_826_p10 = {{{grp_fu_438_p2}, {and_ln538_3_fu_792_p2}}, {and_ln538_4_fu_810_p2}};

assign fpclassify_result_i_i_fu_826_p8 = ((and_ln538_2_fu_772_p2[0:0] == 1'b1) ? 3'd3 : 3'd4);

assign fpclassify_result_i_i_fu_826_p9 = 'bx;

assign fpu_rs_f3_load_load_fu_553_p1 = fpu_rs_f3;

assign fpu_rs_f7_load_load_fu_549_p1 = fpu_rs_f7;

assign fpu_rs_r4op_load_load_fu_539_p1 = fpu_rs_r4op;

assign grp_fu_347_p1 = fpu_rs_s2_val;

assign grp_fu_385_p3 = fpu_rs_s1_val[32'd31];

assign grp_fu_392_p2 = (grp_fu_385_p3 ^ 1'd1);

assign grp_fu_398_p2 = ((fpu_rs_rs2f == 5'd1) ? 1'b1 : 1'b0);

assign grp_fu_403_p4 = {{fpu_rs_s2_val[30:23]}};

assign grp_fu_412_p2 = ((grp_fu_403_p4 != 8'd255) ? 1'b1 : 1'b0);

assign grp_fu_418_p4 = {{fpu_rs_s1_val[30:23]}};

assign grp_fu_427_p2 = ((grp_fu_418_p4 != 8'd255) ? 1'b1 : 1'b0);

assign grp_fu_433_p2 = (icmp_ln386_1_reg_1919 | grp_fu_427_p2);

assign grp_fu_438_p2 = (grp_fu_433_p2 & grp_fu_357_p2);

assign grp_fu_444_p3 = fpu_rs_s1_val[32'd31];

assign grp_fu_451_p4 = {{fpu_rs_s1_val[27:23]}};

assign grp_fu_460_p3 = {{fpu_rs_s1_val[30:23]}};

assign grp_fu_467_p2 = ((grp_fu_460_p3 < 8'd126) ? 1'b1 : 1'b0);

assign grp_fu_473_p2 = ((grp_fu_460_p3 == 8'd126) ? 1'b1 : 1'b0);

assign grp_fu_479_p2 = ((grp_fu_460_p3 > 8'd149) ? 1'b1 : 1'b0);

assign grp_fu_485_p2 = ((fpu_rs_f3 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln18_1_fu_1563_p2 = ((x_fp_sig_1_reg_1870 != 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln18_2_fu_666_p2 = ((y_fp_exp_fu_624_p3 == 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln18_3_fu_672_p2 = ((y_fp_sig_fu_632_p1 != 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln18_fu_660_p2 = ((x_fp_exp_fu_608_p3 == 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln25_1_fu_654_p2 = ((or_ln25_1_fu_648_p2 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln25_fu_642_p2 = ((or_ln25_fu_636_p2 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln374_1_fu_1784_p2 = ((fpu_rs_f3 == 3'd1) ? 1'b1 : 1'b0);

assign icmp_ln374_fu_1779_p2 = ((fpu_rs_f3 == 3'd2) ? 1'b1 : 1'b0);

assign icmp_ln386_1_fu_543_p2 = ((x_fp_sig_1_fu_504_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln386_3_fu_602_p2 = ((trunc_ln386_fu_598_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln387_2_fu_592_p2 = ((trunc_ln387_fu_588_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln388_2_fu_582_p2 = ((trunc_ln388_fu_578_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln401_fu_562_p2 = ((fpu_rs_f3 == 3'd1) ? 1'b1 : 1'b0);

assign lshr_ln18_fu_1150_p2 = zext_ln15_fu_1102_p1 >> zext_ln18_fu_1146_p1;

assign lshr_ln71_fu_1425_p2 = zext_ln68_fu_1379_p1 >> zext_ln71_fu_1421_p1;

assign mantissa_1_fu_1370_p4 = {{{{1'd1}, {trunc_ln342_1_reg_2184}}}, {1'd0}};

assign mantissa_fu_1092_p4 = {{{{1'd1}, {trunc_ln342_fu_1088_p1}}}, {1'd0}};

assign one_half_1_fu_963_p2 = (zext_ln42_fu_948_p1 + 24'd1);

assign one_half_2_fu_969_p3 = ((tmp_49_fu_956_p3[0:0] == 1'b1) ? one_half_1_fu_963_p2 : zext_ln42_fu_948_p1);

assign one_half_4_fu_1248_p2 = (zext_ln42_2_fu_1233_p1 + 24'd1);

assign one_half_5_fu_1254_p3 = ((tmp_53_fu_1241_p3[0:0] == 1'b1) ? one_half_4_fu_1248_p2 : zext_ln42_2_fu_1233_p1);

assign or_ln18_1_fu_1674_p2 = (or_ln18_fu_1669_p2 | and_ln18_1_fu_1573_p2);

assign or_ln18_2_fu_1692_p2 = (xor_ln18_3_fu_1686_p2 | and_ln18_7_fu_1648_p2);

assign or_ln18_fu_1669_p2 = (or_ln25_2_reg_2230 | and_ln18_fu_1568_p2);

assign or_ln25_1_fu_648_p2 = (y_fp_sig_fu_632_p1 | x_fp_sig_1_fu_504_p1);

assign or_ln25_2_fu_1557_p2 = (grp_fu_485_p2 | and_ln25_fu_1537_p2);

assign or_ln25_fu_636_p2 = (y_fp_exp_fu_624_p3 | x_fp_exp_fu_608_p3);

assign or_ln34_1_fu_1309_p2 = (grp_fu_467_p2 | and_ln34_1_fu_1216_p2);

assign or_ln34_fu_1024_p2 = (grp_fu_467_p2 | and_ln34_fu_931_p2);

assign or_ln379_fu_1827_p2 = (trunc_ln379_fu_1823_p1 | t_9_reg_1876);

assign or_ln386_1_fu_1512_p2 = (icmp_ln386_3_reg_1990 | icmp_ln386_2_reg_1985);

assign or_ln386_fu_1507_p2 = (icmp_ln386_1_reg_1919 | grp_fu_427_p2);

assign or_ln387_1_fu_1491_p2 = (icmp_ln387_2_reg_1980 | icmp_ln387_1_reg_1975);

assign or_ln387_fu_1486_p2 = (icmp_ln386_1_reg_1919 | grp_fu_427_p2);

assign or_ln388_1_fu_1470_p2 = (icmp_ln388_2_reg_1970 | icmp_ln388_1_reg_1965);

assign or_ln388_fu_1465_p2 = (icmp_ln386_1_reg_1919 | grp_fu_427_p2);

assign or_ln38_fu_914_p2 = (cmp_i_i8_reg_2111 | and_ln39_fu_908_p2);

assign or_ln538_1_fu_798_p2 = (grp_fu_438_p2 | grp_fu_362_p2);

assign or_ln_fu_1840_p3 = {{tmp_33_fu_1832_p3}, {or_ln379_fu_1827_p2}};

assign quiet_fu_866_p3 = fpu_rs_s1_val[32'd22];

assign res_31_fu_1718_p13 = 'bx;

assign res_31_fu_1718_p14 = {{{{{and_ln18_3_fu_1615_p2}, {and_ln18_5_fu_1631_p2}}, {and_ln18_9_fu_1663_p2}}, {xor_ln18_2_fu_1680_p2}}, {and_ln18_10_fu_1698_p2}};

assign res_31_fu_1718_p6 = ((ymaggreater_1_reg_2030[0:0] == 1'b1) ? a_reg_1883 : b_reg_1898);

assign res_31_fu_1718_p8 = ((ymaggreater_1_reg_2030[0:0] == 1'b1) ? b_reg_1898 : a_reg_1883);

assign res_fu_1595_p1 = t_fu_1586_p4;

assign result_1_fu_1190_p2 = (32'd0 - val_2_fu_1182_p3);

assign result_2_fu_1196_p3 = ((xs_sign_fu_1072_p3[0:0] == 1'b1) ? result_1_fu_1190_p2 : val_2_fu_1182_p3);

assign select_ln18_fu_1134_p3 = ((tmp_51_fu_1116_p3[0:0] == 1'b1) ? sext_ln18_fu_1130_p1 : add_ln317_fu_1110_p2);

assign select_ln397_fu_897_p3 = ((icmp_ln397_reg_1956[0:0] == 1'b1) ? grp_fu_351_p1 : grp_fu_354_p1);

assign select_ln39_fu_690_p3 = ((grp_fu_385_p3[0:0] == 1'b1) ? xor_ln39_fu_684_p2 : ymaggreater_fu_678_p2);

assign select_ln60_fu_881_p3 = ((grp_fu_444_p3[0:0] == 1'b1) ? 32'd1 : 32'd128);

assign select_ln63_cast_cast_fu_873_p3 = ((quiet_fu_866_p3[0:0] == 1'b1) ? 32'd512 : 32'd256);

assign select_ln65_fu_858_p3 = ((grp_fu_444_p3[0:0] == 1'b1) ? 32'd8 : 32'd16);

assign select_ln66_fu_850_p3 = ((grp_fu_444_p3[0:0] == 1'b1) ? 32'd4 : 32'd32);

assign select_ln68_fu_889_p3 = ((grp_fu_444_p3[0:0] == 1'b1) ? 32'd2 : 32'd64);

assign select_ln71_fu_1409_p3 = ((tmp_54_fu_1392_p3[0:0] == 1'b1) ? sext_ln71_fu_1405_p1 : add_ln317_1_fu_1386_p2);

assign sext_ln18_1_fu_1142_p1 = $signed(select_ln18_fu_1134_p3);

assign sext_ln18_fu_1130_p1 = $signed(sub_ln18_fu_1124_p2);

assign sext_ln71_1_fu_1417_p1 = $signed(select_ln71_fu_1409_p3);

assign sext_ln71_fu_1405_p1 = $signed(sub_ln71_fu_1400_p2);

assign shl_ln18_fu_1156_p2 = zext_ln15_fu_1102_p1 << zext_ln18_fu_1146_p1;

assign shl_ln71_fu_1431_p2 = zext_ln68_fu_1379_p1 << zext_ln71_fu_1421_p1;

assign sign_3_fu_1799_p10 = {{{icmp_ln374_fu_1779_p2}, {icmp_ln374_1_fu_1784_p2}}, {grp_fu_485_p2}};

assign sign_3_fu_1799_p2 = {{tmp_24_reg_2042}, {31'd0}};

assign sign_3_fu_1799_p4 = {{xor_ln376_fu_1759_p2}, {31'd0}};

assign sign_3_fu_1799_p6 = {{tmp_23_reg_2036}, {31'd0}};

assign sign_3_fu_1799_p9 = 'bx;

assign sub_ln18_fu_1124_p2 = (8'd127 - xs_exp_fu_1080_p3);

assign sub_ln71_fu_1400_p2 = (8'd127 - xs_exp_1_reg_2178);

assign t_5_fu_1221_p3 = {{grp_fu_444_p3}, {31'd0}};

assign t_6_fu_1297_p3 = {{tmp_44_i_fu_1287_p4}, {xs_sig_2_fu_1281_p2}};

assign t_7_fu_936_p3 = {{grp_fu_444_p3}, {31'd0}};

assign t_8_fu_1012_p3 = {{tmp_44_i1_fu_1002_p4}, {xs_sig_1_fu_996_p2}};

assign t_9_fu_508_p1 = fpu_rs_s1_val[30:0];

assign t_fu_1586_p4 = {{{x_fp_sign_reg_1995}, {8'd255}}, {x_fp_sig_fu_1577_p4}};

assign tmp_10_fu_1447_p4 = {{shl_ln71_fu_1431_p2[55:24]}};

assign tmp_33_fu_1832_p3 = sign_3_fu_1799_p11[32'd31];

assign tmp_44_i1_fu_1002_p4 = {{data_4_fu_981_p2[31:23]}};

assign tmp_44_i_fu_1287_p4 = {{data_6_fu_1266_p2[31:23]}};

assign tmp_49_fu_956_p2 = $signed(index_table_q0);

assign tmp_51_fu_1116_p3 = add_ln317_fu_1110_p2[32'd8];

assign tmp_53_fu_1241_p2 = $signed(index_table_q0);

assign tmp_54_fu_1392_p3 = add_ln317_1_fu_1386_p2[32'd8];

assign tmp_7_fu_1162_p4 = {{lshr_ln18_fu_1150_p2[55:24]}};

assign tmp_8_fu_1172_p4 = {{shl_ln18_fu_1156_p2[55:24]}};

assign tmp_9_fu_1437_p4 = {{lshr_ln71_fu_1425_p2[55:24]}};

assign trunc_ln301_1_fu_1271_p1 = data_6_fu_1266_p2[22:0];

assign trunc_ln301_fu_986_p1 = data_4_fu_981_p2[22:0];

assign trunc_ln342_1_fu_1366_p1 = data_7_fu_1354_p1[22:0];

assign trunc_ln342_fu_1088_p1 = data_fu_1069_p1[22:0];

assign trunc_ln379_fu_1823_p1 = sign_3_fu_1799_p11[30:0];

assign trunc_ln386_fu_598_p1 = fpu_rs_s2_val[22:0];

assign trunc_ln387_fu_588_p1 = fpu_rs_s2_val[22:0];

assign trunc_ln388_fu_578_p1 = fpu_rs_s2_val[22:0];

assign val_2_fu_1182_p3 = ((tmp_51_fu_1116_p3[0:0] == 1'b1) ? tmp_7_fu_1162_p4 : tmp_8_fu_1172_p4);

assign val_fu_1457_p3 = ((tmp_54_fu_1392_p3[0:0] == 1'b1) ? tmp_9_fu_1437_p4 : tmp_10_fu_1447_p4);

assign x_fp_exp_fu_608_p3 = {{fpu_rs_s1_val[30:23]}};

assign x_fp_sig_1_fu_504_p1 = fpu_rs_s1_val[22:0];

assign x_fp_sig_fu_1577_p4 = {|(1'd1), x_fp_sig_1_reg_1870[22 - 1:0]};

assign xor_ln18_1_fu_1657_p2 = (1'd1 ^ and_ln18_8_fu_1653_p2);

assign xor_ln18_2_fu_1680_p2 = (or_ln18_1_fu_1674_p2 ^ 1'd1);

assign xor_ln18_3_fu_1686_p2 = (or_ln18_fu_1669_p2 ^ 1'd1);

assign xor_ln18_fu_1642_p2 = (1'd1 ^ and_ln18_6_fu_1637_p2);

assign xor_ln1_fu_728_p3 = {{xor_ln362_reg_1929}, {t_9_reg_1876}};

assign xor_ln25_1_fu_1620_p2 = (or_ln25_2_reg_2230 ^ 1'd1);

assign xor_ln25_fu_1545_p2 = (1'd1 ^ and_ln25_1_fu_1541_p2);

assign xor_ln34_1_fu_1315_p2 = (or_ln34_1_fu_1309_p2 ^ 1'd1);

assign xor_ln34_fu_1030_p2 = (or_ln34_fu_1024_p2 ^ 1'd1);

assign xor_ln376_fu_1759_p2 = (tmp_23_reg_2036 ^ 1'd1);

assign xor_ln377_fu_714_p2 = (fpu_rs_s2_val ^ fpu_rs_s1_val);

assign xor_ln39_fu_684_p2 = (ymaggreater_fu_678_p2 ^ 1'd1);

assign xor_ln538_1_fu_804_p2 = (or_ln538_1_fu_798_p2 ^ 1'd1);

assign xor_ln538_fu_786_p2 = (grp_fu_438_p2 ^ 1'd1);

assign xor_ln77_1_fu_1275_p2 = (mask_table_q0 ^ 23'd8388607);

assign xor_ln77_fu_990_p2 = (mask_table_q0 ^ 23'd8388607);

assign xor_ln_fu_739_p3 = {{xor_ln361_reg_1934}, {t_9_reg_1876}};

assign xs_exp_fu_1080_p3 = {{data_fu_1069_p1[30:23]}};

assign xs_sig_1_fu_996_p2 = (xor_ln77_fu_990_p2 & trunc_ln301_fu_986_p1);

assign xs_sig_2_fu_1281_p2 = (xor_ln77_1_fu_1275_p2 & trunc_ln301_1_fu_1271_p1);

assign xs_sign_fu_1072_p3 = data_fu_1069_p1[32'd31];

assign y_fp_exp_fu_624_p3 = {{fpu_rs_s2_val[30:23]}};

assign y_fp_sig_fu_632_p1 = fpu_rs_s2_val[22:0];

assign y_fp_sign_fu_616_p3 = fpu_rs_s2_val[32'd31];

assign ymaggreater_1_fu_698_p3 = ((y_fp_sign_fu_616_p3[0:0] == 1'b1) ? select_ln39_fu_690_p3 : ymaggreater_fu_678_p2);

assign ymaggreater_fu_678_p2 = (($signed(fpu_rs_s1_val) < $signed(fpu_rs_s2_val)) ? 1'b1 : 1'b0);

assign zext_ln15_fu_1102_p1 = mantissa_fu_1092_p4;

assign zext_ln18_fu_1146_p1 = $unsigned(sext_ln18_1_fu_1142_p1);

assign zext_ln313_fu_568_p1 = t_9_fu_508_p1;

assign zext_ln317_1_fu_1383_p1 = xs_exp_1_reg_2178;

assign zext_ln317_fu_1106_p1 = xs_exp_fu_1080_p3;

assign zext_ln386_fu_1534_p1 = and_ln386_1_reg_2204;

assign zext_ln387_fu_1531_p1 = and_ln387_1_reg_2199;

assign zext_ln388_fu_1528_p1 = and_ln388_1_reg_2194;

assign zext_ln42_1_fu_977_p1 = one_half_2_fu_969_p3;

assign zext_ln42_2_fu_1233_p1 = one_half_minus_one_table_q0;

assign zext_ln42_3_fu_1262_p1 = one_half_5_fu_1254_p3;

assign zext_ln42_fu_948_p1 = one_half_minus_one_table_q0;

assign zext_ln46_1_fu_1209_p1 = grp_fu_451_p4;

assign zext_ln46_fu_924_p1 = grp_fu_451_p4;

assign zext_ln68_fu_1379_p1 = mantissa_1_fu_1370_p4;

assign zext_ln71_fu_1421_p1 = $unsigned(sext_ln71_1_fu_1417_p1);

endmodule //rv32_ooo_tick_fpu_compute
