#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("reset", 1, hls_in, 0, "ap_none", "in_data", 1),
	Port_Property("r0_out", 32, hls_out, 1, "ap_none", "out_data", 1),
	Port_Property("r1_out", 32, hls_out, 2, "ap_none", "out_data", 1),
	Port_Property("r2_out", 32, hls_out, 3, "ap_none", "out_data", 1),
	Port_Property("r3_out", 32, hls_out, 4, "ap_none", "out_data", 1),
	Port_Property("commit_reg", 2, hls_out, 5, "ap_none", "out_data", 1),
	Port_Property("commit_valid", 1, hls_out, 6, "ap_none", "out_data", 1),
	Port_Property("alu_complete_tag", 2, hls_out, 7, "ap_none", "out_data", 1),
	Port_Property("alu_complete_valid", 1, hls_out, 8, "ap_none", "out_data", 1),
	Port_Property("mul_complete_tag", 2, hls_out, 9, "ap_none", "out_data", 1),
	Port_Property("mul_complete_valid", 1, hls_out, 10, "ap_none", "out_data", 1),
	Port_Property("halted", 1, hls_out, 11, "ap_none", "out_data", 1),
	Port_Property("s_axi_control_AWVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_AWREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_AWADDR", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_WVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_WREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_WDATA", 32, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_WSTRB", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_ARVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_ARREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_ARADDR", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_RVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_RREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_RDATA", 32, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_RRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_BVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_BREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_BRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("interrupt", 1, hls_out, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "ooo_demo_tick";
