// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module rv32_ooo_tick_cdb_broadcast (
        ap_ready,
        tag,
        value_r,
        alu_rs_busy_0,
        alu_rs_s1_ready_0_i,
        alu_rs_s1_ready_0_o,
        alu_rs_s1_ready_0_o_ap_vld,
        alu_rs_s1_tag_0,
        alu_rs_s1_val_0,
        alu_rs_s1_val_0_ap_vld,
        alu_rs_s2_ready_0_i,
        alu_rs_s2_ready_0_o,
        alu_rs_s2_ready_0_o_ap_vld,
        alu_rs_s2_tag_0,
        alu_rs_s2_val_0,
        alu_rs_s2_val_0_ap_vld,
        alu_rs_busy_1,
        md_rs_busy,
        md_rs_s1_ready_i,
        md_rs_s1_ready_o,
        md_rs_s1_ready_o_ap_vld,
        md_rs_s1_tag,
        md_rs_s1_val,
        md_rs_s1_val_ap_vld,
        md_rs_s2_ready_i,
        md_rs_s2_ready_o,
        md_rs_s2_ready_o_ap_vld,
        md_rs_s2_tag,
        md_rs_s2_val,
        md_rs_s2_val_ap_vld,
        lsu_rs_busy,
        lsu_rs_s1_ready_i,
        lsu_rs_s1_ready_o,
        lsu_rs_s1_ready_o_ap_vld,
        lsu_rs_s1_tag,
        lsu_rs_s1_val,
        lsu_rs_s1_val_ap_vld,
        lsu_rs_s2_ready_i,
        lsu_rs_s2_ready_o,
        lsu_rs_s2_ready_o_ap_vld,
        lsu_rs_s2_tag,
        lsu_rs_s2_val,
        lsu_rs_s2_val_ap_vld,
        br_rs_busy,
        br_rs_s1_ready_i,
        br_rs_s1_ready_o,
        br_rs_s1_ready_o_ap_vld,
        br_rs_s1_tag,
        br_rs_s1_val,
        br_rs_s1_val_ap_vld,
        br_rs_s2_ready_i,
        br_rs_s2_ready_o,
        br_rs_s2_ready_o_ap_vld,
        br_rs_s2_tag,
        br_rs_s2_val,
        br_rs_s2_val_ap_vld,
        fpu_rs_busy,
        fpu_rs_s1_ready_i,
        fpu_rs_s1_ready_o,
        fpu_rs_s1_ready_o_ap_vld,
        fpu_rs_s1_tag,
        fpu_rs_s1_val,
        fpu_rs_s1_val_ap_vld,
        fpu_rs_s2_ready_i,
        fpu_rs_s2_ready_o,
        fpu_rs_s2_ready_o_ap_vld,
        fpu_rs_s2_tag,
        fpu_rs_s2_val,
        fpu_rs_s2_val_ap_vld,
        fpu_rs_s3_ready_i,
        fpu_rs_s3_ready_o,
        fpu_rs_s3_ready_o_ap_vld,
        fpu_rs_s3_tag,
        fpu_rs_s3_val,
        fpu_rs_s3_val_ap_vld,
        vec_rs_busy,
        vec_rs_s1_ready_i,
        vec_rs_s1_ready_o,
        vec_rs_s1_ready_o_ap_vld,
        vec_rs_s1_tag,
        vec_rs_s1_val,
        vec_rs_s1_val_ap_vld,
        sys_rs_busy,
        sys_rs_s1_ready_i,
        sys_rs_s1_ready_o,
        sys_rs_s1_ready_o_ap_vld,
        sys_rs_s1_tag,
        sys_rs_s1_val,
        sys_rs_s1_val_ap_vld,
        alu_rs_s1_ready_1_i,
        alu_rs_s1_ready_1_o,
        alu_rs_s1_ready_1_o_ap_vld,
        alu_rs_s1_tag_1,
        alu_rs_s1_val_1,
        alu_rs_s1_val_1_ap_vld,
        alu_rs_s2_ready_1_i,
        alu_rs_s2_ready_1_o,
        alu_rs_s2_ready_1_o_ap_vld,
        alu_rs_s2_tag_1,
        alu_rs_s2_val_1,
        alu_rs_s2_val_1_ap_vld,
        ap_rst
);


output   ap_ready;
input  [2:0] tag;
input  [31:0] value_r;
input  [0:0] alu_rs_busy_0;
input  [0:0] alu_rs_s1_ready_0_i;
output  [0:0] alu_rs_s1_ready_0_o;
output   alu_rs_s1_ready_0_o_ap_vld;
input  [2:0] alu_rs_s1_tag_0;
output  [31:0] alu_rs_s1_val_0;
output   alu_rs_s1_val_0_ap_vld;
input  [0:0] alu_rs_s2_ready_0_i;
output  [0:0] alu_rs_s2_ready_0_o;
output   alu_rs_s2_ready_0_o_ap_vld;
input  [2:0] alu_rs_s2_tag_0;
output  [31:0] alu_rs_s2_val_0;
output   alu_rs_s2_val_0_ap_vld;
input  [0:0] alu_rs_busy_1;
input  [0:0] md_rs_busy;
input  [0:0] md_rs_s1_ready_i;
output  [0:0] md_rs_s1_ready_o;
output   md_rs_s1_ready_o_ap_vld;
input  [2:0] md_rs_s1_tag;
output  [31:0] md_rs_s1_val;
output   md_rs_s1_val_ap_vld;
input  [0:0] md_rs_s2_ready_i;
output  [0:0] md_rs_s2_ready_o;
output   md_rs_s2_ready_o_ap_vld;
input  [2:0] md_rs_s2_tag;
output  [31:0] md_rs_s2_val;
output   md_rs_s2_val_ap_vld;
input  [0:0] lsu_rs_busy;
input  [0:0] lsu_rs_s1_ready_i;
output  [0:0] lsu_rs_s1_ready_o;
output   lsu_rs_s1_ready_o_ap_vld;
input  [2:0] lsu_rs_s1_tag;
output  [7:0] lsu_rs_s1_val;
output   lsu_rs_s1_val_ap_vld;
input  [0:0] lsu_rs_s2_ready_i;
output  [0:0] lsu_rs_s2_ready_o;
output   lsu_rs_s2_ready_o_ap_vld;
input  [2:0] lsu_rs_s2_tag;
output  [31:0] lsu_rs_s2_val;
output   lsu_rs_s2_val_ap_vld;
input  [0:0] br_rs_busy;
input  [0:0] br_rs_s1_ready_i;
output  [0:0] br_rs_s1_ready_o;
output   br_rs_s1_ready_o_ap_vld;
input  [2:0] br_rs_s1_tag;
output  [31:0] br_rs_s1_val;
output   br_rs_s1_val_ap_vld;
input  [0:0] br_rs_s2_ready_i;
output  [0:0] br_rs_s2_ready_o;
output   br_rs_s2_ready_o_ap_vld;
input  [2:0] br_rs_s2_tag;
output  [31:0] br_rs_s2_val;
output   br_rs_s2_val_ap_vld;
input  [0:0] fpu_rs_busy;
input  [0:0] fpu_rs_s1_ready_i;
output  [0:0] fpu_rs_s1_ready_o;
output   fpu_rs_s1_ready_o_ap_vld;
input  [2:0] fpu_rs_s1_tag;
output  [31:0] fpu_rs_s1_val;
output   fpu_rs_s1_val_ap_vld;
input  [0:0] fpu_rs_s2_ready_i;
output  [0:0] fpu_rs_s2_ready_o;
output   fpu_rs_s2_ready_o_ap_vld;
input  [2:0] fpu_rs_s2_tag;
output  [31:0] fpu_rs_s2_val;
output   fpu_rs_s2_val_ap_vld;
input  [0:0] fpu_rs_s3_ready_i;
output  [0:0] fpu_rs_s3_ready_o;
output   fpu_rs_s3_ready_o_ap_vld;
input  [2:0] fpu_rs_s3_tag;
output  [31:0] fpu_rs_s3_val;
output   fpu_rs_s3_val_ap_vld;
input  [0:0] vec_rs_busy;
input  [0:0] vec_rs_s1_ready_i;
output  [0:0] vec_rs_s1_ready_o;
output   vec_rs_s1_ready_o_ap_vld;
input  [2:0] vec_rs_s1_tag;
output  [7:0] vec_rs_s1_val;
output   vec_rs_s1_val_ap_vld;
input  [0:0] sys_rs_busy;
input  [0:0] sys_rs_s1_ready_i;
output  [0:0] sys_rs_s1_ready_o;
output   sys_rs_s1_ready_o_ap_vld;
input  [2:0] sys_rs_s1_tag;
output  [31:0] sys_rs_s1_val;
output   sys_rs_s1_val_ap_vld;
input  [0:0] alu_rs_s1_ready_1_i;
output  [0:0] alu_rs_s1_ready_1_o;
output   alu_rs_s1_ready_1_o_ap_vld;
input  [2:0] alu_rs_s1_tag_1;
output  [31:0] alu_rs_s1_val_1;
output   alu_rs_s1_val_1_ap_vld;
input  [0:0] alu_rs_s2_ready_1_i;
output  [0:0] alu_rs_s2_ready_1_o;
output   alu_rs_s2_ready_1_o_ap_vld;
input  [2:0] alu_rs_s2_tag_1;
output  [31:0] alu_rs_s2_val_1;
output   alu_rs_s2_val_1_ap_vld;
input   ap_rst;

reg[0:0] alu_rs_s1_ready_0_o;
reg alu_rs_s1_ready_0_o_ap_vld;
reg alu_rs_s1_val_0_ap_vld;
reg[0:0] alu_rs_s2_ready_0_o;
reg alu_rs_s2_ready_0_o_ap_vld;
reg alu_rs_s2_val_0_ap_vld;
reg[0:0] md_rs_s1_ready_o;
reg md_rs_s1_ready_o_ap_vld;
reg md_rs_s1_val_ap_vld;
reg[0:0] md_rs_s2_ready_o;
reg md_rs_s2_ready_o_ap_vld;
reg md_rs_s2_val_ap_vld;
reg[0:0] lsu_rs_s1_ready_o;
reg lsu_rs_s1_ready_o_ap_vld;
reg lsu_rs_s1_val_ap_vld;
reg[0:0] lsu_rs_s2_ready_o;
reg lsu_rs_s2_ready_o_ap_vld;
reg lsu_rs_s2_val_ap_vld;
reg[0:0] br_rs_s1_ready_o;
reg br_rs_s1_ready_o_ap_vld;
reg br_rs_s1_val_ap_vld;
reg[0:0] br_rs_s2_ready_o;
reg br_rs_s2_ready_o_ap_vld;
reg br_rs_s2_val_ap_vld;
reg[0:0] fpu_rs_s1_ready_o;
reg fpu_rs_s1_ready_o_ap_vld;
reg fpu_rs_s1_val_ap_vld;
reg[0:0] fpu_rs_s2_ready_o;
reg fpu_rs_s2_ready_o_ap_vld;
reg fpu_rs_s2_val_ap_vld;
reg[0:0] fpu_rs_s3_ready_o;
reg fpu_rs_s3_ready_o_ap_vld;
reg fpu_rs_s3_val_ap_vld;
reg[0:0] vec_rs_s1_ready_o;
reg vec_rs_s1_ready_o_ap_vld;
reg vec_rs_s1_val_ap_vld;
reg[0:0] sys_rs_s1_ready_o;
reg sys_rs_s1_ready_o_ap_vld;
reg sys_rs_s1_val_ap_vld;
reg[0:0] alu_rs_s1_ready_1_o;
reg alu_rs_s1_ready_1_o_ap_vld;
reg alu_rs_s1_val_1_ap_vld;
reg[0:0] alu_rs_s2_ready_1_o;
reg alu_rs_s2_ready_1_o_ap_vld;
reg alu_rs_s2_val_1_ap_vld;

wire   [0:0] alu_rs_busy_0_load_load_fu_132_p1;
wire   [0:0] or_ln180_fu_150_p2;
wire   [0:0] or_ln183_fu_182_p2;
wire   [0:0] md_rs_busy_load_load_fu_268_p1;
wire   [0:0] or_ln187_fu_286_p2;
wire   [0:0] or_ln190_fu_318_p2;
wire   [0:0] lsu_rs_busy_load_load_fu_336_p1;
wire   [0:0] or_ln193_fu_354_p2;
wire   [7:0] trunc_ln177_fu_128_p1;
wire   [0:0] or_ln196_fu_386_p2;
wire   [0:0] br_rs_busy_load_load_fu_404_p1;
wire   [0:0] or_ln199_fu_422_p2;
wire   [0:0] or_ln202_fu_454_p2;
wire   [0:0] fpu_rs_busy_load_load_fu_472_p1;
wire   [0:0] or_ln205_fu_490_p2;
wire   [0:0] or_ln208_fu_522_p2;
wire   [0:0] or_ln211_fu_554_p2;
wire   [0:0] vec_rs_busy_load_load_fu_572_p1;
wire   [0:0] or_ln214_fu_590_p2;
wire   [0:0] sys_rs_busy_load_load_fu_608_p1;
wire   [0:0] or_ln217_fu_626_p2;
wire   [0:0] alu_rs_busy_1_load_load_fu_200_p1;
wire   [0:0] or_ln180_1_fu_218_p2;
wire   [0:0] or_ln183_1_fu_250_p2;
wire   [0:0] icmp_ln180_fu_144_p2;
wire   [0:0] icmp_ln183_fu_176_p2;
wire   [0:0] icmp_ln180_1_fu_212_p2;
wire   [0:0] icmp_ln183_1_fu_244_p2;
wire   [0:0] icmp_ln187_fu_280_p2;
wire   [0:0] icmp_ln190_fu_312_p2;
wire   [0:0] icmp_ln193_fu_348_p2;
wire   [0:0] icmp_ln196_fu_380_p2;
wire   [0:0] icmp_ln199_fu_416_p2;
wire   [0:0] icmp_ln202_fu_448_p2;
wire   [0:0] icmp_ln205_fu_484_p2;
wire   [0:0] icmp_ln208_fu_516_p2;
wire   [0:0] icmp_ln211_fu_548_p2;
wire   [0:0] icmp_ln214_fu_584_p2;
wire   [0:0] icmp_ln217_fu_620_p2;
wire    ap_ce_reg;

always @ (*) begin
    if (((or_ln180_fu_150_p2 == 1'd0) & (1'd1 == alu_rs_busy_0_load_load_fu_132_p1))) begin
        alu_rs_s1_ready_0_o = 1'd1;
    end else begin
        alu_rs_s1_ready_0_o = alu_rs_s1_ready_0_i;
    end
end

always @ (*) begin
    if (((or_ln180_fu_150_p2 == 1'd0) & (1'd1 == alu_rs_busy_0_load_load_fu_132_p1))) begin
        alu_rs_s1_ready_0_o_ap_vld = 1'b1;
    end else begin
        alu_rs_s1_ready_0_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln180_1_fu_218_p2 == 1'd0) & (1'd1 == alu_rs_busy_1_load_load_fu_200_p1))) begin
        alu_rs_s1_ready_1_o = 1'd1;
    end else begin
        alu_rs_s1_ready_1_o = alu_rs_s1_ready_1_i;
    end
end

always @ (*) begin
    if (((or_ln180_1_fu_218_p2 == 1'd0) & (1'd1 == alu_rs_busy_1_load_load_fu_200_p1))) begin
        alu_rs_s1_ready_1_o_ap_vld = 1'b1;
    end else begin
        alu_rs_s1_ready_1_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln180_fu_150_p2 == 1'd0) & (1'd1 == alu_rs_busy_0_load_load_fu_132_p1))) begin
        alu_rs_s1_val_0_ap_vld = 1'b1;
    end else begin
        alu_rs_s1_val_0_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln180_1_fu_218_p2 == 1'd0) & (1'd1 == alu_rs_busy_1_load_load_fu_200_p1))) begin
        alu_rs_s1_val_1_ap_vld = 1'b1;
    end else begin
        alu_rs_s1_val_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln183_fu_182_p2 == 1'd0) & (1'd1 == alu_rs_busy_0_load_load_fu_132_p1))) begin
        alu_rs_s2_ready_0_o = 1'd1;
    end else begin
        alu_rs_s2_ready_0_o = alu_rs_s2_ready_0_i;
    end
end

always @ (*) begin
    if (((or_ln183_fu_182_p2 == 1'd0) & (1'd1 == alu_rs_busy_0_load_load_fu_132_p1))) begin
        alu_rs_s2_ready_0_o_ap_vld = 1'b1;
    end else begin
        alu_rs_s2_ready_0_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln183_1_fu_250_p2 == 1'd0) & (1'd1 == alu_rs_busy_1_load_load_fu_200_p1))) begin
        alu_rs_s2_ready_1_o = 1'd1;
    end else begin
        alu_rs_s2_ready_1_o = alu_rs_s2_ready_1_i;
    end
end

always @ (*) begin
    if (((or_ln183_1_fu_250_p2 == 1'd0) & (1'd1 == alu_rs_busy_1_load_load_fu_200_p1))) begin
        alu_rs_s2_ready_1_o_ap_vld = 1'b1;
    end else begin
        alu_rs_s2_ready_1_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln183_fu_182_p2 == 1'd0) & (1'd1 == alu_rs_busy_0_load_load_fu_132_p1))) begin
        alu_rs_s2_val_0_ap_vld = 1'b1;
    end else begin
        alu_rs_s2_val_0_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln183_1_fu_250_p2 == 1'd0) & (1'd1 == alu_rs_busy_1_load_load_fu_200_p1))) begin
        alu_rs_s2_val_1_ap_vld = 1'b1;
    end else begin
        alu_rs_s2_val_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln199_fu_422_p2 == 1'd0) & (br_rs_busy_load_load_fu_404_p1 == 1'd1))) begin
        br_rs_s1_ready_o = 1'd1;
    end else begin
        br_rs_s1_ready_o = br_rs_s1_ready_i;
    end
end

always @ (*) begin
    if (((or_ln199_fu_422_p2 == 1'd0) & (br_rs_busy_load_load_fu_404_p1 == 1'd1))) begin
        br_rs_s1_ready_o_ap_vld = 1'b1;
    end else begin
        br_rs_s1_ready_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln199_fu_422_p2 == 1'd0) & (br_rs_busy_load_load_fu_404_p1 == 1'd1))) begin
        br_rs_s1_val_ap_vld = 1'b1;
    end else begin
        br_rs_s1_val_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln202_fu_454_p2 == 1'd0) & (br_rs_busy_load_load_fu_404_p1 == 1'd1))) begin
        br_rs_s2_ready_o = 1'd1;
    end else begin
        br_rs_s2_ready_o = br_rs_s2_ready_i;
    end
end

always @ (*) begin
    if (((or_ln202_fu_454_p2 == 1'd0) & (br_rs_busy_load_load_fu_404_p1 == 1'd1))) begin
        br_rs_s2_ready_o_ap_vld = 1'b1;
    end else begin
        br_rs_s2_ready_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln202_fu_454_p2 == 1'd0) & (br_rs_busy_load_load_fu_404_p1 == 1'd1))) begin
        br_rs_s2_val_ap_vld = 1'b1;
    end else begin
        br_rs_s2_val_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln205_fu_490_p2 == 1'd0) & (fpu_rs_busy_load_load_fu_472_p1 == 1'd1))) begin
        fpu_rs_s1_ready_o = 1'd1;
    end else begin
        fpu_rs_s1_ready_o = fpu_rs_s1_ready_i;
    end
end

always @ (*) begin
    if (((or_ln205_fu_490_p2 == 1'd0) & (fpu_rs_busy_load_load_fu_472_p1 == 1'd1))) begin
        fpu_rs_s1_ready_o_ap_vld = 1'b1;
    end else begin
        fpu_rs_s1_ready_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln205_fu_490_p2 == 1'd0) & (fpu_rs_busy_load_load_fu_472_p1 == 1'd1))) begin
        fpu_rs_s1_val_ap_vld = 1'b1;
    end else begin
        fpu_rs_s1_val_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln208_fu_522_p2 == 1'd0) & (fpu_rs_busy_load_load_fu_472_p1 == 1'd1))) begin
        fpu_rs_s2_ready_o = 1'd1;
    end else begin
        fpu_rs_s2_ready_o = fpu_rs_s2_ready_i;
    end
end

always @ (*) begin
    if (((or_ln208_fu_522_p2 == 1'd0) & (fpu_rs_busy_load_load_fu_472_p1 == 1'd1))) begin
        fpu_rs_s2_ready_o_ap_vld = 1'b1;
    end else begin
        fpu_rs_s2_ready_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln208_fu_522_p2 == 1'd0) & (fpu_rs_busy_load_load_fu_472_p1 == 1'd1))) begin
        fpu_rs_s2_val_ap_vld = 1'b1;
    end else begin
        fpu_rs_s2_val_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln211_fu_554_p2 == 1'd0) & (fpu_rs_busy_load_load_fu_472_p1 == 1'd1))) begin
        fpu_rs_s3_ready_o = 1'd1;
    end else begin
        fpu_rs_s3_ready_o = fpu_rs_s3_ready_i;
    end
end

always @ (*) begin
    if (((or_ln211_fu_554_p2 == 1'd0) & (fpu_rs_busy_load_load_fu_472_p1 == 1'd1))) begin
        fpu_rs_s3_ready_o_ap_vld = 1'b1;
    end else begin
        fpu_rs_s3_ready_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln211_fu_554_p2 == 1'd0) & (fpu_rs_busy_load_load_fu_472_p1 == 1'd1))) begin
        fpu_rs_s3_val_ap_vld = 1'b1;
    end else begin
        fpu_rs_s3_val_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln193_fu_354_p2 == 1'd0) & (lsu_rs_busy_load_load_fu_336_p1 == 1'd1))) begin
        lsu_rs_s1_ready_o = 1'd1;
    end else begin
        lsu_rs_s1_ready_o = lsu_rs_s1_ready_i;
    end
end

always @ (*) begin
    if (((or_ln193_fu_354_p2 == 1'd0) & (lsu_rs_busy_load_load_fu_336_p1 == 1'd1))) begin
        lsu_rs_s1_ready_o_ap_vld = 1'b1;
    end else begin
        lsu_rs_s1_ready_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln193_fu_354_p2 == 1'd0) & (lsu_rs_busy_load_load_fu_336_p1 == 1'd1))) begin
        lsu_rs_s1_val_ap_vld = 1'b1;
    end else begin
        lsu_rs_s1_val_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln196_fu_386_p2 == 1'd0) & (lsu_rs_busy_load_load_fu_336_p1 == 1'd1))) begin
        lsu_rs_s2_ready_o = 1'd1;
    end else begin
        lsu_rs_s2_ready_o = lsu_rs_s2_ready_i;
    end
end

always @ (*) begin
    if (((or_ln196_fu_386_p2 == 1'd0) & (lsu_rs_busy_load_load_fu_336_p1 == 1'd1))) begin
        lsu_rs_s2_ready_o_ap_vld = 1'b1;
    end else begin
        lsu_rs_s2_ready_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln196_fu_386_p2 == 1'd0) & (lsu_rs_busy_load_load_fu_336_p1 == 1'd1))) begin
        lsu_rs_s2_val_ap_vld = 1'b1;
    end else begin
        lsu_rs_s2_val_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln187_fu_286_p2 == 1'd0) & (md_rs_busy_load_load_fu_268_p1 == 1'd1))) begin
        md_rs_s1_ready_o = 1'd1;
    end else begin
        md_rs_s1_ready_o = md_rs_s1_ready_i;
    end
end

always @ (*) begin
    if (((or_ln187_fu_286_p2 == 1'd0) & (md_rs_busy_load_load_fu_268_p1 == 1'd1))) begin
        md_rs_s1_ready_o_ap_vld = 1'b1;
    end else begin
        md_rs_s1_ready_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln187_fu_286_p2 == 1'd0) & (md_rs_busy_load_load_fu_268_p1 == 1'd1))) begin
        md_rs_s1_val_ap_vld = 1'b1;
    end else begin
        md_rs_s1_val_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln190_fu_318_p2 == 1'd0) & (md_rs_busy_load_load_fu_268_p1 == 1'd1))) begin
        md_rs_s2_ready_o = 1'd1;
    end else begin
        md_rs_s2_ready_o = md_rs_s2_ready_i;
    end
end

always @ (*) begin
    if (((or_ln190_fu_318_p2 == 1'd0) & (md_rs_busy_load_load_fu_268_p1 == 1'd1))) begin
        md_rs_s2_ready_o_ap_vld = 1'b1;
    end else begin
        md_rs_s2_ready_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln190_fu_318_p2 == 1'd0) & (md_rs_busy_load_load_fu_268_p1 == 1'd1))) begin
        md_rs_s2_val_ap_vld = 1'b1;
    end else begin
        md_rs_s2_val_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln217_fu_626_p2 == 1'd0) & (sys_rs_busy_load_load_fu_608_p1 == 1'd1))) begin
        sys_rs_s1_ready_o = 1'd1;
    end else begin
        sys_rs_s1_ready_o = sys_rs_s1_ready_i;
    end
end

always @ (*) begin
    if (((or_ln217_fu_626_p2 == 1'd0) & (sys_rs_busy_load_load_fu_608_p1 == 1'd1))) begin
        sys_rs_s1_ready_o_ap_vld = 1'b1;
    end else begin
        sys_rs_s1_ready_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln217_fu_626_p2 == 1'd0) & (sys_rs_busy_load_load_fu_608_p1 == 1'd1))) begin
        sys_rs_s1_val_ap_vld = 1'b1;
    end else begin
        sys_rs_s1_val_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln214_fu_590_p2 == 1'd0) & (vec_rs_busy_load_load_fu_572_p1 == 1'd1))) begin
        vec_rs_s1_ready_o = 1'd1;
    end else begin
        vec_rs_s1_ready_o = vec_rs_s1_ready_i;
    end
end

always @ (*) begin
    if (((or_ln214_fu_590_p2 == 1'd0) & (vec_rs_busy_load_load_fu_572_p1 == 1'd1))) begin
        vec_rs_s1_ready_o_ap_vld = 1'b1;
    end else begin
        vec_rs_s1_ready_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln214_fu_590_p2 == 1'd0) & (vec_rs_busy_load_load_fu_572_p1 == 1'd1))) begin
        vec_rs_s1_val_ap_vld = 1'b1;
    end else begin
        vec_rs_s1_val_ap_vld = 1'b0;
    end
end

assign alu_rs_s1_val_0 = value_r;

assign alu_rs_s1_val_1 = value_r;

assign alu_rs_s2_val_0 = value_r;

assign alu_rs_s2_val_1 = value_r;

assign ap_ready = 1'b1;

assign br_rs_s1_val = value_r;

assign br_rs_s2_val = value_r;

assign fpu_rs_s1_val = value_r;

assign fpu_rs_s2_val = value_r;

assign fpu_rs_s3_val = value_r;

assign icmp_ln180_1_fu_212_p2 = ((alu_rs_s1_tag_1 != tag) ? 1'b1 : 1'b0);

assign icmp_ln180_fu_144_p2 = ((alu_rs_s1_tag_0 != tag) ? 1'b1 : 1'b0);

assign icmp_ln183_1_fu_244_p2 = ((alu_rs_s2_tag_1 != tag) ? 1'b1 : 1'b0);

assign icmp_ln183_fu_176_p2 = ((alu_rs_s2_tag_0 != tag) ? 1'b1 : 1'b0);

assign icmp_ln187_fu_280_p2 = ((md_rs_s1_tag != tag) ? 1'b1 : 1'b0);

assign icmp_ln190_fu_312_p2 = ((md_rs_s2_tag != tag) ? 1'b1 : 1'b0);

assign icmp_ln193_fu_348_p2 = ((lsu_rs_s1_tag != tag) ? 1'b1 : 1'b0);

assign icmp_ln196_fu_380_p2 = ((lsu_rs_s2_tag != tag) ? 1'b1 : 1'b0);

assign icmp_ln199_fu_416_p2 = ((br_rs_s1_tag != tag) ? 1'b1 : 1'b0);

assign icmp_ln202_fu_448_p2 = ((br_rs_s2_tag != tag) ? 1'b1 : 1'b0);

assign icmp_ln205_fu_484_p2 = ((fpu_rs_s1_tag != tag) ? 1'b1 : 1'b0);

assign icmp_ln208_fu_516_p2 = ((fpu_rs_s2_tag != tag) ? 1'b1 : 1'b0);

assign icmp_ln211_fu_548_p2 = ((fpu_rs_s3_tag != tag) ? 1'b1 : 1'b0);

assign icmp_ln214_fu_584_p2 = ((vec_rs_s1_tag != tag) ? 1'b1 : 1'b0);

assign icmp_ln217_fu_620_p2 = ((sys_rs_s1_tag != tag) ? 1'b1 : 1'b0);

assign lsu_rs_s1_val = trunc_ln177_fu_128_p1;

assign lsu_rs_s2_val = value_r;

assign md_rs_s1_val = value_r;

assign md_rs_s2_val = value_r;

assign or_ln180_1_fu_218_p2 = (icmp_ln180_1_fu_212_p2 | alu_rs_s1_ready_1_i);

assign or_ln180_fu_150_p2 = (icmp_ln180_fu_144_p2 | alu_rs_s1_ready_0_i);

assign or_ln183_1_fu_250_p2 = (icmp_ln183_1_fu_244_p2 | alu_rs_s2_ready_1_i);

assign or_ln183_fu_182_p2 = (icmp_ln183_fu_176_p2 | alu_rs_s2_ready_0_i);

assign or_ln187_fu_286_p2 = (md_rs_s1_ready_i | icmp_ln187_fu_280_p2);

assign or_ln190_fu_318_p2 = (md_rs_s2_ready_i | icmp_ln190_fu_312_p2);

assign or_ln193_fu_354_p2 = (lsu_rs_s1_ready_i | icmp_ln193_fu_348_p2);

assign or_ln196_fu_386_p2 = (lsu_rs_s2_ready_i | icmp_ln196_fu_380_p2);

assign or_ln199_fu_422_p2 = (icmp_ln199_fu_416_p2 | br_rs_s1_ready_i);

assign or_ln202_fu_454_p2 = (icmp_ln202_fu_448_p2 | br_rs_s2_ready_i);

assign or_ln205_fu_490_p2 = (icmp_ln205_fu_484_p2 | fpu_rs_s1_ready_i);

assign or_ln208_fu_522_p2 = (icmp_ln208_fu_516_p2 | fpu_rs_s2_ready_i);

assign or_ln211_fu_554_p2 = (icmp_ln211_fu_548_p2 | fpu_rs_s3_ready_i);

assign or_ln214_fu_590_p2 = (vec_rs_s1_ready_i | icmp_ln214_fu_584_p2);

assign or_ln217_fu_626_p2 = (sys_rs_s1_ready_i | icmp_ln217_fu_620_p2);

assign sys_rs_s1_val = value_r;

assign trunc_ln177_fu_128_p1 = value_r[7:0];

assign vec_rs_s1_val = trunc_ln177_fu_128_p1;

assign alu_rs_busy_0_load_load_fu_132_p1 = alu_rs_busy_0;

assign alu_rs_busy_1_load_load_fu_200_p1 = alu_rs_busy_1;

assign br_rs_busy_load_load_fu_404_p1 = br_rs_busy;

assign fpu_rs_busy_load_load_fu_472_p1 = fpu_rs_busy;

assign lsu_rs_busy_load_load_fu_336_p1 = lsu_rs_busy;

assign md_rs_busy_load_load_fu_268_p1 = md_rs_busy;

assign sys_rs_busy_load_load_fu_608_p1 = sys_rs_busy;

assign vec_rs_busy_load_load_fu_572_p1 = vec_rs_busy;

endmodule //rv32_ooo_tick_cdb_broadcast
