// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module ooo_demo_tick_ooo_demo_tick_Pipeline_VITIS_LOOP_119_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_7,
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_7_ap_vld,
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_11,
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_11_ap_vld,
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_3,
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_3_ap_vld,
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_15,
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_15_ap_vld,
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_18,
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_18_ap_vld,
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_25,
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_25_ap_vld,
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_22,
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_22_ap_vld,
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_6,
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_6_ap_vld,
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_10,
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_10_ap_vld,
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_2,
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_2_ap_vld,
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_14,
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_14_ap_vld,
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_17,
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_17_ap_vld,
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_24,
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_24_ap_vld,
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_21,
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_21_ap_vld,
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_5,
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_5_ap_vld,
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_9,
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_9_ap_vld,
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_1,
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_1_ap_vld,
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_13,
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_13_ap_vld,
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_16,
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_16_ap_vld,
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_23,
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_23_ap_vld,
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_20,
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_20_ap_vld,
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_4,
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_4_ap_vld,
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_8,
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_8_ap_vld,
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u,
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_ap_vld,
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_12,
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_12_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [0:0] ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_7;
output   ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_7_ap_vld;
output  [0:0] ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_11;
output   ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_11_ap_vld;
output  [31:0] ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_3;
output   ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_3_ap_vld;
output  [1:0] ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_15;
output   ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_15_ap_vld;
output  [31:0] ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_18;
output   ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_18_ap_vld;
output  [0:0] ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_25;
output   ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_25_ap_vld;
output  [1:0] ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_22;
output   ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_22_ap_vld;
output  [0:0] ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_6;
output   ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_6_ap_vld;
output  [0:0] ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_10;
output   ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_10_ap_vld;
output  [31:0] ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_2;
output   ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_2_ap_vld;
output  [1:0] ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_14;
output   ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_14_ap_vld;
output  [31:0] ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_17;
output   ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_17_ap_vld;
output  [0:0] ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_24;
output   ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_24_ap_vld;
output  [1:0] ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_21;
output   ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_21_ap_vld;
output  [0:0] ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_5;
output   ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_5_ap_vld;
output  [0:0] ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_9;
output   ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_9_ap_vld;
output  [31:0] ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_1;
output   ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_1_ap_vld;
output  [1:0] ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_13;
output   ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_13_ap_vld;
output  [31:0] ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_16;
output   ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_16_ap_vld;
output  [0:0] ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_23;
output   ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_23_ap_vld;
output  [1:0] ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_20;
output   ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_20_ap_vld;
output  [0:0] ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_4;
output   ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_4_ap_vld;
output  [0:0] ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_8;
output   ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_8_ap_vld;
output  [31:0] ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u;
output   ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_ap_vld;
output  [1:0] ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_12;
output   ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_12_ap_vld;

reg ap_idle;
reg ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_7_ap_vld;
reg ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_11_ap_vld;
reg ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_3_ap_vld;
reg ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_15_ap_vld;
reg ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_18_ap_vld;
reg ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_25_ap_vld;
reg ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_22_ap_vld;
reg ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_6_ap_vld;
reg ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_10_ap_vld;
reg ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_2_ap_vld;
reg ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_14_ap_vld;
reg ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_17_ap_vld;
reg ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_24_ap_vld;
reg ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_21_ap_vld;
reg ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_5_ap_vld;
reg ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_9_ap_vld;
reg ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_1_ap_vld;
reg ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_13_ap_vld;
reg ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_16_ap_vld;
reg ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_23_ap_vld;
reg ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_20_ap_vld;
reg ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_4_ap_vld;
reg ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_8_ap_vld;
reg ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_ap_vld;
reg ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_12_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln119_fu_94_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [1:0] trunc_ln119_fu_106_p1;
reg   [2:0] i_fu_82;
wire   [2:0] add_ln119_fu_100_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_i_1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 i_fu_82 = 3'd0;
#0 ap_done_reg = 1'b0;
end

ooo_demo_tick_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln119_fu_94_p2 == 1'd0)) begin
            i_fu_82 <= add_ln119_fu_100_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_82 <= 3'd0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln119_fu_94_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 3'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_82;
    end
end

always @ (*) begin
    if (((trunc_ln119_fu_106_p1 == 2'd1) & (icmp_ln119_fu_94_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_10_ap_vld = 1'b1;
    end else begin
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_10_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln119_fu_106_p1 == 2'd0) & (icmp_ln119_fu_94_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_11_ap_vld = 1'b1;
    end else begin
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_11_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln119_fu_106_p1 == 2'd3) & (icmp_ln119_fu_94_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_12_ap_vld = 1'b1;
    end else begin
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_12_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln119_fu_106_p1 == 2'd2) & (icmp_ln119_fu_94_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_13_ap_vld = 1'b1;
    end else begin
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_13_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln119_fu_106_p1 == 2'd1) & (icmp_ln119_fu_94_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_14_ap_vld = 1'b1;
    end else begin
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_14_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln119_fu_106_p1 == 2'd0) & (icmp_ln119_fu_94_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_15_ap_vld = 1'b1;
    end else begin
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_15_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln119_fu_106_p1 == 2'd3) & (icmp_ln119_fu_94_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_16_ap_vld = 1'b1;
    end else begin
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_16_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln119_fu_106_p1 == 2'd2) & (icmp_ln119_fu_94_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_17_ap_vld = 1'b1;
    end else begin
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_17_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln119_fu_106_p1 == 2'd1) & (icmp_ln119_fu_94_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_18_ap_vld = 1'b1;
    end else begin
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_18_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln119_fu_106_p1 == 2'd2) & (icmp_ln119_fu_94_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_1_ap_vld = 1'b1;
    end else begin
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln119_fu_106_p1 == 2'd3) & (icmp_ln119_fu_94_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_20_ap_vld = 1'b1;
    end else begin
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_20_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln119_fu_106_p1 == 2'd2) & (icmp_ln119_fu_94_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_21_ap_vld = 1'b1;
    end else begin
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_21_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln119_fu_106_p1 == 2'd1) & (icmp_ln119_fu_94_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_22_ap_vld = 1'b1;
    end else begin
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_22_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln119_fu_106_p1 == 2'd3) & (icmp_ln119_fu_94_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_23_ap_vld = 1'b1;
    end else begin
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_23_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln119_fu_106_p1 == 2'd2) & (icmp_ln119_fu_94_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_24_ap_vld = 1'b1;
    end else begin
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_24_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln119_fu_106_p1 == 2'd1) & (icmp_ln119_fu_94_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_25_ap_vld = 1'b1;
    end else begin
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_25_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln119_fu_106_p1 == 2'd1) & (icmp_ln119_fu_94_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_2_ap_vld = 1'b1;
    end else begin
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln119_fu_106_p1 == 2'd0) & (icmp_ln119_fu_94_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_3_ap_vld = 1'b1;
    end else begin
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_3_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln119_fu_106_p1 == 2'd3) & (icmp_ln119_fu_94_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_4_ap_vld = 1'b1;
    end else begin
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_4_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln119_fu_106_p1 == 2'd2) & (icmp_ln119_fu_94_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_5_ap_vld = 1'b1;
    end else begin
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_5_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln119_fu_106_p1 == 2'd1) & (icmp_ln119_fu_94_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_6_ap_vld = 1'b1;
    end else begin
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_6_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln119_fu_106_p1 == 2'd0) & (icmp_ln119_fu_94_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_7_ap_vld = 1'b1;
    end else begin
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_7_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln119_fu_106_p1 == 2'd3) & (icmp_ln119_fu_94_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_8_ap_vld = 1'b1;
    end else begin
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_8_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln119_fu_106_p1 == 2'd2) & (icmp_ln119_fu_94_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_9_ap_vld = 1'b1;
    end else begin
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_9_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln119_fu_106_p1 == 2'd3) & (icmp_ln119_fu_94_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_ap_vld = 1'b1;
    end else begin
        ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln119_fu_100_p2 = (ap_sig_allocacmp_i_1 + 3'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln119_fu_94_p2 = ((ap_sig_allocacmp_i_1 == 3'd4) ? 1'b1 : 1'b0);

assign ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u = 32'd0;

assign ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_1 = 32'd0;

assign ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_10 = 1'd0;

assign ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_11 = 1'd0;

assign ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_12 = 2'd0;

assign ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_13 = 2'd0;

assign ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_14 = 2'd0;

assign ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_15 = 2'd0;

assign ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_16 = 32'd0;

assign ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_17 = 32'd0;

assign ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_18 = 32'd0;

assign ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_2 = 32'd0;

assign ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_20 = 2'd0;

assign ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_21 = 2'd0;

assign ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_22 = 2'd0;

assign ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_23 = 1'd0;

assign ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_24 = 1'd0;

assign ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_25 = 1'd0;

assign ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_3 = 32'd0;

assign ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_4 = 1'd0;

assign ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_5 = 1'd0;

assign ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_6 = 1'd0;

assign ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_7 = 1'd0;

assign ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_8 = 1'd0;

assign ooo_demo_tick_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_uint_ap_u_9 = 1'd0;

assign trunc_ln119_fu_106_p1 = ap_sig_allocacmp_i_1[1:0];

endmodule //ooo_demo_tick_ooo_demo_tick_Pipeline_VITIS_LOOP_119_1
