-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2024.2 (lin64) Build 5239630 Fri Nov 08 22:34:34 MST 2024
-- Date        : Wed Jul 22 07:51:09 2026
-- Host        : andy-ThinkPad-P53 running 64-bit Ubuntu 24.04.4 LTS
-- Command     : write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix
--               decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ bd_0_hls_inst_0_stub.vhdl
-- Design      : bd_0_hls_inst_0
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xck26-sfvc784-2LV-c
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  Port ( 
    s_axi_control_ARADDR : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axi_control_ARREADY : out STD_LOGIC;
    s_axi_control_ARVALID : in STD_LOGIC;
    s_axi_control_AWADDR : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axi_control_AWREADY : out STD_LOGIC;
    s_axi_control_AWVALID : in STD_LOGIC;
    s_axi_control_BREADY : in STD_LOGIC;
    s_axi_control_BRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_control_BVALID : out STD_LOGIC;
    s_axi_control_RDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_control_RREADY : in STD_LOGIC;
    s_axi_control_RRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_control_RVALID : out STD_LOGIC;
    s_axi_control_WDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_control_WREADY : out STD_LOGIC;
    s_axi_control_WSTRB : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axi_control_WVALID : in STD_LOGIC;
    ap_clk : in STD_LOGIC;
    ap_rst_n : in STD_LOGIC;
    interrupt : out STD_LOGIC;
    reset : in STD_LOGIC_VECTOR ( 0 to 0 );
    imem_Addr_A : out STD_LOGIC_VECTOR ( 31 downto 0 );
    imem_Clk_A : out STD_LOGIC;
    imem_Din_A : out STD_LOGIC_VECTOR ( 31 downto 0 );
    imem_Dout_A : in STD_LOGIC_VECTOR ( 31 downto 0 );
    imem_EN_A : out STD_LOGIC;
    imem_Rst_A : out STD_LOGIC;
    imem_WEN_A : out STD_LOGIC_VECTOR ( 3 downto 0 );
    imem_Addr_B : out STD_LOGIC_VECTOR ( 31 downto 0 );
    imem_Clk_B : out STD_LOGIC;
    imem_Din_B : out STD_LOGIC_VECTOR ( 31 downto 0 );
    imem_Dout_B : in STD_LOGIC_VECTOR ( 31 downto 0 );
    imem_EN_B : out STD_LOGIC;
    imem_Rst_B : out STD_LOGIC;
    imem_WEN_B : out STD_LOGIC_VECTOR ( 3 downto 0 );
    dmem_Addr_A : out STD_LOGIC_VECTOR ( 31 downto 0 );
    dmem_Clk_A : out STD_LOGIC;
    dmem_Din_A : out STD_LOGIC_VECTOR ( 31 downto 0 );
    dmem_Dout_A : in STD_LOGIC_VECTOR ( 31 downto 0 );
    dmem_EN_A : out STD_LOGIC;
    dmem_Rst_A : out STD_LOGIC;
    dmem_WEN_A : out STD_LOGIC_VECTOR ( 3 downto 0 );
    dmem_Addr_B : out STD_LOGIC_VECTOR ( 31 downto 0 );
    dmem_Clk_B : out STD_LOGIC;
    dmem_Din_B : out STD_LOGIC_VECTOR ( 31 downto 0 );
    dmem_Dout_B : in STD_LOGIC_VECTOR ( 31 downto 0 );
    dmem_EN_B : out STD_LOGIC;
    dmem_Rst_B : out STD_LOGIC;
    dmem_WEN_B : out STD_LOGIC_VECTOR ( 3 downto 0 );
    disp_valid : out STD_LOGIC_VECTOR ( 0 to 0 );
    disp_tag : out STD_LOGIC_VECTOR ( 2 downto 0 );
    disp_pc : out STD_LOGIC_VECTOR ( 31 downto 0 );
    alu0_done : out STD_LOGIC_VECTOR ( 0 to 0 );
    alu0_tag : out STD_LOGIC_VECTOR ( 2 downto 0 );
    alu1_done : out STD_LOGIC_VECTOR ( 0 to 0 );
    alu1_tag : out STD_LOGIC_VECTOR ( 2 downto 0 );
    md_done : out STD_LOGIC_VECTOR ( 0 to 0 );
    md_tag : out STD_LOGIC_VECTOR ( 2 downto 0 );
    fpu_done : out STD_LOGIC_VECTOR ( 0 to 0 );
    fpu_tag : out STD_LOGIC_VECTOR ( 2 downto 0 );
    lsu_done : out STD_LOGIC_VECTOR ( 0 to 0 );
    lsu_tag : out STD_LOGIC_VECTOR ( 2 downto 0 );
    br_done : out STD_LOGIC_VECTOR ( 0 to 0 );
    br_tag : out STD_LOGIC_VECTOR ( 2 downto 0 );
    vec_done : out STD_LOGIC_VECTOR ( 0 to 0 );
    vec_tag : out STD_LOGIC_VECTOR ( 2 downto 0 );
    commit_valid : out STD_LOGIC_VECTOR ( 0 to 0 );
    commit_is_fp : out STD_LOGIC_VECTOR ( 0 to 0 );
    commit_rd : out STD_LOGIC_VECTOR ( 4 downto 0 );
    commit_value : out STD_LOGIC_VECTOR ( 31 downto 0 );
    vregs_out_Addr_A : out STD_LOGIC_VECTOR ( 31 downto 0 );
    vregs_out_Clk_A : out STD_LOGIC;
    vregs_out_Din_A : out STD_LOGIC_VECTOR ( 31 downto 0 );
    vregs_out_Dout_A : in STD_LOGIC_VECTOR ( 31 downto 0 );
    vregs_out_EN_A : out STD_LOGIC;
    vregs_out_Rst_A : out STD_LOGIC;
    vregs_out_WEN_A : out STD_LOGIC_VECTOR ( 3 downto 0 );
    halted : out STD_LOGIC_VECTOR ( 0 to 0 )
  );

  attribute CHECK_LICENSE_TYPE : string;
  attribute CHECK_LICENSE_TYPE of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "bd_0_hls_inst_0,rv32_ooo_tick,{}";
  attribute CORE_GENERATION_INFO : string;
  attribute CORE_GENERATION_INFO of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "bd_0_hls_inst_0,rv32_ooo_tick,{x_ipProduct=Vivado 2024.2,x_ipVendor=xilinx.com,x_ipLibrary=hls,x_ipName=rv32_ooo_tick,x_ipVersion=1.0,x_ipCoreRevision=2114707547,x_ipLanguage=VERILOG,x_ipSimLanguage=MIXED,C_S_AXI_CONTROL_ADDR_WIDTH=4,C_S_AXI_CONTROL_DATA_WIDTH=32}";
  attribute DowngradeIPIdentifiedWarnings : string;
  attribute DowngradeIPIdentifiedWarnings of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "yes";
  attribute IP_DEFINITION_SOURCE : string;
  attribute IP_DEFINITION_SOURCE of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "HLS";
  attribute hls_module : string;
  attribute hls_module of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "yes";
end decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix;

architecture stub of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  attribute syn_black_box : boolean;
  attribute black_box_pad_pin : string;
  attribute syn_black_box of stub : architecture is true;
  attribute black_box_pad_pin of stub : architecture is "s_axi_control_ARADDR[3:0],s_axi_control_ARREADY,s_axi_control_ARVALID,s_axi_control_AWADDR[3:0],s_axi_control_AWREADY,s_axi_control_AWVALID,s_axi_control_BREADY,s_axi_control_BRESP[1:0],s_axi_control_BVALID,s_axi_control_RDATA[31:0],s_axi_control_RREADY,s_axi_control_RRESP[1:0],s_axi_control_RVALID,s_axi_control_WDATA[31:0],s_axi_control_WREADY,s_axi_control_WSTRB[3:0],s_axi_control_WVALID,ap_clk,ap_rst_n,interrupt,reset[0:0],imem_Addr_A[31:0],imem_Clk_A,imem_Din_A[31:0],imem_Dout_A[31:0],imem_EN_A,imem_Rst_A,imem_WEN_A[3:0],imem_Addr_B[31:0],imem_Clk_B,imem_Din_B[31:0],imem_Dout_B[31:0],imem_EN_B,imem_Rst_B,imem_WEN_B[3:0],dmem_Addr_A[31:0],dmem_Clk_A,dmem_Din_A[31:0],dmem_Dout_A[31:0],dmem_EN_A,dmem_Rst_A,dmem_WEN_A[3:0],dmem_Addr_B[31:0],dmem_Clk_B,dmem_Din_B[31:0],dmem_Dout_B[31:0],dmem_EN_B,dmem_Rst_B,dmem_WEN_B[3:0],disp_valid[0:0],disp_tag[2:0],disp_pc[31:0],alu0_done[0:0],alu0_tag[2:0],alu1_done[0:0],alu1_tag[2:0],md_done[0:0],md_tag[2:0],fpu_done[0:0],fpu_tag[2:0],lsu_done[0:0],lsu_tag[2:0],br_done[0:0],br_tag[2:0],vec_done[0:0],vec_tag[2:0],commit_valid[0:0],commit_is_fp[0:0],commit_rd[4:0],commit_value[31:0],vregs_out_Addr_A[31:0],vregs_out_Clk_A,vregs_out_Din_A[31:0],vregs_out_Dout_A[31:0],vregs_out_EN_A,vregs_out_Rst_A,vregs_out_WEN_A[3:0],halted[0:0]";
  attribute X_INTERFACE_INFO : string;
  attribute X_INTERFACE_INFO of s_axi_control_ARADDR : signal is "xilinx.com:interface:aximm:1.0 s_axi_control ARADDR";
  attribute X_INTERFACE_MODE : string;
  attribute X_INTERFACE_MODE of s_axi_control_ARADDR : signal is "slave";
  attribute X_INTERFACE_PARAMETER : string;
  attribute X_INTERFACE_PARAMETER of s_axi_control_ARADDR : signal is "XIL_INTERFACENAME s_axi_control, ADDR_WIDTH 4, DATA_WIDTH 32, PROTOCOL AXI4LITE, READ_WRITE_MODE READ_WRITE, FREQ_HZ 100000000.0, ID_WIDTH 0, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_BURST_LENGTH 1, PHASE 0.0, CLK_DOMAIN bd_0_ap_clk_0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s_axi_control_ARREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control ARREADY";
  attribute X_INTERFACE_INFO of s_axi_control_ARVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control ARVALID";
  attribute X_INTERFACE_INFO of s_axi_control_AWADDR : signal is "xilinx.com:interface:aximm:1.0 s_axi_control AWADDR";
  attribute X_INTERFACE_INFO of s_axi_control_AWREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control AWREADY";
  attribute X_INTERFACE_INFO of s_axi_control_AWVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control AWVALID";
  attribute X_INTERFACE_INFO of s_axi_control_BREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control BREADY";
  attribute X_INTERFACE_INFO of s_axi_control_BRESP : signal is "xilinx.com:interface:aximm:1.0 s_axi_control BRESP";
  attribute X_INTERFACE_INFO of s_axi_control_BVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control BVALID";
  attribute X_INTERFACE_INFO of s_axi_control_RDATA : signal is "xilinx.com:interface:aximm:1.0 s_axi_control RDATA";
  attribute X_INTERFACE_INFO of s_axi_control_RREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control RREADY";
  attribute X_INTERFACE_INFO of s_axi_control_RRESP : signal is "xilinx.com:interface:aximm:1.0 s_axi_control RRESP";
  attribute X_INTERFACE_INFO of s_axi_control_RVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control RVALID";
  attribute X_INTERFACE_INFO of s_axi_control_WDATA : signal is "xilinx.com:interface:aximm:1.0 s_axi_control WDATA";
  attribute X_INTERFACE_INFO of s_axi_control_WREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control WREADY";
  attribute X_INTERFACE_INFO of s_axi_control_WSTRB : signal is "xilinx.com:interface:aximm:1.0 s_axi_control WSTRB";
  attribute X_INTERFACE_INFO of s_axi_control_WVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control WVALID";
  attribute X_INTERFACE_INFO of ap_clk : signal is "xilinx.com:signal:clock:1.0 ap_clk CLK";
  attribute X_INTERFACE_MODE of ap_clk : signal is "slave";
  attribute X_INTERFACE_PARAMETER of ap_clk : signal is "XIL_INTERFACENAME ap_clk, ASSOCIATED_BUSIF s_axi_control, ASSOCIATED_RESET ap_rst_n, FREQ_HZ 100000000.0, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN bd_0_ap_clk_0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of ap_rst_n : signal is "xilinx.com:signal:reset:1.0 ap_rst_n RST";
  attribute X_INTERFACE_MODE of ap_rst_n : signal is "slave";
  attribute X_INTERFACE_PARAMETER of ap_rst_n : signal is "XIL_INTERFACENAME ap_rst_n, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of interrupt : signal is "xilinx.com:signal:interrupt:1.0 interrupt INTERRUPT";
  attribute X_INTERFACE_MODE of interrupt : signal is "master";
  attribute X_INTERFACE_PARAMETER of interrupt : signal is "XIL_INTERFACENAME interrupt, SENSITIVITY LEVEL_HIGH, PortWidth 1";
  attribute X_INTERFACE_INFO of reset : signal is "xilinx.com:signal:data:1.0 reset DATA";
  attribute X_INTERFACE_MODE of reset : signal is "slave";
  attribute X_INTERFACE_PARAMETER of reset : signal is "XIL_INTERFACENAME reset, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of imem_Addr_A : signal is "xilinx.com:interface:bram:1.0 imem_PORTA ADDR";
  attribute X_INTERFACE_MODE of imem_Addr_A : signal is "master";
  attribute X_INTERFACE_PARAMETER of imem_Addr_A : signal is "XIL_INTERFACENAME imem_PORTA, MASTER_TYPE BRAM_CTRL, MEM_SIZE 256, MEM_WIDTH 32, MEM_ADDRESS_MODE BYTE_ADDRESS, READ_LATENCY 1, MEM_ECC NONE";
  attribute X_INTERFACE_INFO of imem_Clk_A : signal is "xilinx.com:interface:bram:1.0 imem_PORTA CLK";
  attribute X_INTERFACE_INFO of imem_Din_A : signal is "xilinx.com:interface:bram:1.0 imem_PORTA DIN";
  attribute X_INTERFACE_INFO of imem_Dout_A : signal is "xilinx.com:interface:bram:1.0 imem_PORTA DOUT";
  attribute X_INTERFACE_INFO of imem_EN_A : signal is "xilinx.com:interface:bram:1.0 imem_PORTA EN";
  attribute X_INTERFACE_INFO of imem_Rst_A : signal is "xilinx.com:interface:bram:1.0 imem_PORTA RST";
  attribute X_INTERFACE_INFO of imem_WEN_A : signal is "xilinx.com:interface:bram:1.0 imem_PORTA WE";
  attribute X_INTERFACE_INFO of imem_Addr_B : signal is "xilinx.com:interface:bram:1.0 imem_PORTB ADDR";
  attribute X_INTERFACE_MODE of imem_Addr_B : signal is "master";
  attribute X_INTERFACE_PARAMETER of imem_Addr_B : signal is "XIL_INTERFACENAME imem_PORTB, MASTER_TYPE BRAM_CTRL, MEM_SIZE 256, MEM_WIDTH 32, MEM_ADDRESS_MODE BYTE_ADDRESS, READ_LATENCY 1, MEM_ECC NONE";
  attribute X_INTERFACE_INFO of imem_Clk_B : signal is "xilinx.com:interface:bram:1.0 imem_PORTB CLK";
  attribute X_INTERFACE_INFO of imem_Din_B : signal is "xilinx.com:interface:bram:1.0 imem_PORTB DIN";
  attribute X_INTERFACE_INFO of imem_Dout_B : signal is "xilinx.com:interface:bram:1.0 imem_PORTB DOUT";
  attribute X_INTERFACE_INFO of imem_EN_B : signal is "xilinx.com:interface:bram:1.0 imem_PORTB EN";
  attribute X_INTERFACE_INFO of imem_Rst_B : signal is "xilinx.com:interface:bram:1.0 imem_PORTB RST";
  attribute X_INTERFACE_INFO of imem_WEN_B : signal is "xilinx.com:interface:bram:1.0 imem_PORTB WE";
  attribute X_INTERFACE_INFO of dmem_Addr_A : signal is "xilinx.com:interface:bram:1.0 dmem_PORTA ADDR";
  attribute X_INTERFACE_MODE of dmem_Addr_A : signal is "master";
  attribute X_INTERFACE_PARAMETER of dmem_Addr_A : signal is "XIL_INTERFACENAME dmem_PORTA, MASTER_TYPE BRAM_CTRL, MEM_SIZE 256, MEM_WIDTH 32, MEM_ADDRESS_MODE BYTE_ADDRESS, READ_LATENCY 1, MEM_ECC NONE";
  attribute X_INTERFACE_INFO of dmem_Clk_A : signal is "xilinx.com:interface:bram:1.0 dmem_PORTA CLK";
  attribute X_INTERFACE_INFO of dmem_Din_A : signal is "xilinx.com:interface:bram:1.0 dmem_PORTA DIN";
  attribute X_INTERFACE_INFO of dmem_Dout_A : signal is "xilinx.com:interface:bram:1.0 dmem_PORTA DOUT";
  attribute X_INTERFACE_INFO of dmem_EN_A : signal is "xilinx.com:interface:bram:1.0 dmem_PORTA EN";
  attribute X_INTERFACE_INFO of dmem_Rst_A : signal is "xilinx.com:interface:bram:1.0 dmem_PORTA RST";
  attribute X_INTERFACE_INFO of dmem_WEN_A : signal is "xilinx.com:interface:bram:1.0 dmem_PORTA WE";
  attribute X_INTERFACE_INFO of dmem_Addr_B : signal is "xilinx.com:interface:bram:1.0 dmem_PORTB ADDR";
  attribute X_INTERFACE_MODE of dmem_Addr_B : signal is "master";
  attribute X_INTERFACE_PARAMETER of dmem_Addr_B : signal is "XIL_INTERFACENAME dmem_PORTB, MASTER_TYPE BRAM_CTRL, MEM_SIZE 256, MEM_WIDTH 32, MEM_ADDRESS_MODE BYTE_ADDRESS, READ_LATENCY 1, MEM_ECC NONE";
  attribute X_INTERFACE_INFO of dmem_Clk_B : signal is "xilinx.com:interface:bram:1.0 dmem_PORTB CLK";
  attribute X_INTERFACE_INFO of dmem_Din_B : signal is "xilinx.com:interface:bram:1.0 dmem_PORTB DIN";
  attribute X_INTERFACE_INFO of dmem_Dout_B : signal is "xilinx.com:interface:bram:1.0 dmem_PORTB DOUT";
  attribute X_INTERFACE_INFO of dmem_EN_B : signal is "xilinx.com:interface:bram:1.0 dmem_PORTB EN";
  attribute X_INTERFACE_INFO of dmem_Rst_B : signal is "xilinx.com:interface:bram:1.0 dmem_PORTB RST";
  attribute X_INTERFACE_INFO of dmem_WEN_B : signal is "xilinx.com:interface:bram:1.0 dmem_PORTB WE";
  attribute X_INTERFACE_INFO of disp_valid : signal is "xilinx.com:signal:data:1.0 disp_valid DATA";
  attribute X_INTERFACE_MODE of disp_valid : signal is "master";
  attribute X_INTERFACE_PARAMETER of disp_valid : signal is "XIL_INTERFACENAME disp_valid, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of disp_tag : signal is "xilinx.com:signal:data:1.0 disp_tag DATA";
  attribute X_INTERFACE_MODE of disp_tag : signal is "master";
  attribute X_INTERFACE_PARAMETER of disp_tag : signal is "XIL_INTERFACENAME disp_tag, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of disp_pc : signal is "xilinx.com:signal:data:1.0 disp_pc DATA";
  attribute X_INTERFACE_MODE of disp_pc : signal is "master";
  attribute X_INTERFACE_PARAMETER of disp_pc : signal is "XIL_INTERFACENAME disp_pc, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of alu0_done : signal is "xilinx.com:signal:data:1.0 alu0_done DATA";
  attribute X_INTERFACE_MODE of alu0_done : signal is "master";
  attribute X_INTERFACE_PARAMETER of alu0_done : signal is "XIL_INTERFACENAME alu0_done, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of alu0_tag : signal is "xilinx.com:signal:data:1.0 alu0_tag DATA";
  attribute X_INTERFACE_MODE of alu0_tag : signal is "master";
  attribute X_INTERFACE_PARAMETER of alu0_tag : signal is "XIL_INTERFACENAME alu0_tag, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of alu1_done : signal is "xilinx.com:signal:data:1.0 alu1_done DATA";
  attribute X_INTERFACE_MODE of alu1_done : signal is "master";
  attribute X_INTERFACE_PARAMETER of alu1_done : signal is "XIL_INTERFACENAME alu1_done, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of alu1_tag : signal is "xilinx.com:signal:data:1.0 alu1_tag DATA";
  attribute X_INTERFACE_MODE of alu1_tag : signal is "master";
  attribute X_INTERFACE_PARAMETER of alu1_tag : signal is "XIL_INTERFACENAME alu1_tag, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of md_done : signal is "xilinx.com:signal:data:1.0 md_done DATA";
  attribute X_INTERFACE_MODE of md_done : signal is "master";
  attribute X_INTERFACE_PARAMETER of md_done : signal is "XIL_INTERFACENAME md_done, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of md_tag : signal is "xilinx.com:signal:data:1.0 md_tag DATA";
  attribute X_INTERFACE_MODE of md_tag : signal is "master";
  attribute X_INTERFACE_PARAMETER of md_tag : signal is "XIL_INTERFACENAME md_tag, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of fpu_done : signal is "xilinx.com:signal:data:1.0 fpu_done DATA";
  attribute X_INTERFACE_MODE of fpu_done : signal is "master";
  attribute X_INTERFACE_PARAMETER of fpu_done : signal is "XIL_INTERFACENAME fpu_done, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of fpu_tag : signal is "xilinx.com:signal:data:1.0 fpu_tag DATA";
  attribute X_INTERFACE_MODE of fpu_tag : signal is "master";
  attribute X_INTERFACE_PARAMETER of fpu_tag : signal is "XIL_INTERFACENAME fpu_tag, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of lsu_done : signal is "xilinx.com:signal:data:1.0 lsu_done DATA";
  attribute X_INTERFACE_MODE of lsu_done : signal is "master";
  attribute X_INTERFACE_PARAMETER of lsu_done : signal is "XIL_INTERFACENAME lsu_done, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of lsu_tag : signal is "xilinx.com:signal:data:1.0 lsu_tag DATA";
  attribute X_INTERFACE_MODE of lsu_tag : signal is "master";
  attribute X_INTERFACE_PARAMETER of lsu_tag : signal is "XIL_INTERFACENAME lsu_tag, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of br_done : signal is "xilinx.com:signal:data:1.0 br_done DATA";
  attribute X_INTERFACE_MODE of br_done : signal is "master";
  attribute X_INTERFACE_PARAMETER of br_done : signal is "XIL_INTERFACENAME br_done, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of br_tag : signal is "xilinx.com:signal:data:1.0 br_tag DATA";
  attribute X_INTERFACE_MODE of br_tag : signal is "master";
  attribute X_INTERFACE_PARAMETER of br_tag : signal is "XIL_INTERFACENAME br_tag, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of vec_done : signal is "xilinx.com:signal:data:1.0 vec_done DATA";
  attribute X_INTERFACE_MODE of vec_done : signal is "master";
  attribute X_INTERFACE_PARAMETER of vec_done : signal is "XIL_INTERFACENAME vec_done, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of vec_tag : signal is "xilinx.com:signal:data:1.0 vec_tag DATA";
  attribute X_INTERFACE_MODE of vec_tag : signal is "master";
  attribute X_INTERFACE_PARAMETER of vec_tag : signal is "XIL_INTERFACENAME vec_tag, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of commit_valid : signal is "xilinx.com:signal:data:1.0 commit_valid DATA";
  attribute X_INTERFACE_MODE of commit_valid : signal is "master";
  attribute X_INTERFACE_PARAMETER of commit_valid : signal is "XIL_INTERFACENAME commit_valid, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of commit_is_fp : signal is "xilinx.com:signal:data:1.0 commit_is_fp DATA";
  attribute X_INTERFACE_MODE of commit_is_fp : signal is "master";
  attribute X_INTERFACE_PARAMETER of commit_is_fp : signal is "XIL_INTERFACENAME commit_is_fp, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of commit_rd : signal is "xilinx.com:signal:data:1.0 commit_rd DATA";
  attribute X_INTERFACE_MODE of commit_rd : signal is "master";
  attribute X_INTERFACE_PARAMETER of commit_rd : signal is "XIL_INTERFACENAME commit_rd, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of commit_value : signal is "xilinx.com:signal:data:1.0 commit_value DATA";
  attribute X_INTERFACE_MODE of commit_value : signal is "master";
  attribute X_INTERFACE_PARAMETER of commit_value : signal is "XIL_INTERFACENAME commit_value, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of vregs_out_Addr_A : signal is "xilinx.com:interface:bram:1.0 vregs_out_PORTA ADDR";
  attribute X_INTERFACE_MODE of vregs_out_Addr_A : signal is "master";
  attribute X_INTERFACE_PARAMETER of vregs_out_Addr_A : signal is "XIL_INTERFACENAME vregs_out_PORTA, MASTER_TYPE BRAM_CTRL, MEM_SIZE 512, MEM_WIDTH 32, MEM_ADDRESS_MODE BYTE_ADDRESS, READ_LATENCY 1, MEM_ECC NONE";
  attribute X_INTERFACE_INFO of vregs_out_Clk_A : signal is "xilinx.com:interface:bram:1.0 vregs_out_PORTA CLK";
  attribute X_INTERFACE_INFO of vregs_out_Din_A : signal is "xilinx.com:interface:bram:1.0 vregs_out_PORTA DIN";
  attribute X_INTERFACE_INFO of vregs_out_Dout_A : signal is "xilinx.com:interface:bram:1.0 vregs_out_PORTA DOUT";
  attribute X_INTERFACE_INFO of vregs_out_EN_A : signal is "xilinx.com:interface:bram:1.0 vregs_out_PORTA EN";
  attribute X_INTERFACE_INFO of vregs_out_Rst_A : signal is "xilinx.com:interface:bram:1.0 vregs_out_PORTA RST";
  attribute X_INTERFACE_INFO of vregs_out_WEN_A : signal is "xilinx.com:interface:bram:1.0 vregs_out_PORTA WE";
  attribute X_INTERFACE_INFO of halted : signal is "xilinx.com:signal:data:1.0 halted DATA";
  attribute X_INTERFACE_MODE of halted : signal is "master";
  attribute X_INTERFACE_PARAMETER of halted : signal is "XIL_INTERFACENAME halted, LAYERED_METADATA undef";
  attribute X_CORE_INFO : string;
  attribute X_CORE_INFO of stub : architecture is "rv32_ooo_tick,Vivado 2024.2";
begin
end;
