// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module rv32_ooo_tick_expand (
        ap_ready,
        c,
        ap_return,
        ap_rst
);


output   ap_ready;
input  [15:0] c;
output  [31:0] ap_return;
input   ap_rst;

wire   [31:0] or_ln44_2_fu_1093_p10;
reg   [31:0] ap_phi_mux_retval_11_phi_fu_187_p80;
wire   [1:0] trunc_ln65_fu_484_p1;
wire   [2:0] trunc_ln_fu_488_p4;
wire   [31:0] or_ln39_13_cast_fu_514_p1;
wire   [31:0] or_ln39_10_cast_fu_535_p1;
wire   [31:0] zext_ln35_fu_636_p1;
wire   [31:0] zext_ln264_fu_615_p1;
wire   [0:0] grp_fu_310_p3;
wire   [0:0] icmp_ln254_fu_540_p2;
wire   [0:0] icmp_ln262_fu_582_p2;
wire   [31:0] zext_ln266_fu_602_p1;
wire   [31:0] zext_ln256_fu_571_p1;
wire   [0:0] grp_fu_328_p2;
wire   [31:0] zext_ln259_fu_558_p1;
wire   [31:0] zext_ln35_1_fu_657_p1;
wire   [31:0] zext_ln234_fu_676_p1;
wire   [31:0] or_ln39_7_cast_fu_1140_p1;
wire   [31:0] or_ln39_3_cast_fu_1169_p1;
wire   [31:0] or_ln35_5_cast_fu_1194_p1;
wire   [31:0] or_ln35_2_cast_fu_1219_p1;
wire   [31:0] zext_ln79_fu_1288_p1;
wire   [0:0] icmp_ln78_fu_1266_p2;
wire   [31:0] or_ln44_5_fu_697_p10;
wire   [31:0] or_ln52_1_fu_732_p11;
wire  signed [31:0] or_ln35_10_cast_fu_1014_p1;
wire   [31:0] or_ln5_fu_1031_p11;
wire  signed [31:0] or_ln35_8_cast_fu_1072_p1;
wire   [31:0] zext_ln184_fu_921_p1;
wire   [1:0] grp_fu_374_p4;
wire   [1:0] grp_fu_384_p4;
wire  signed [31:0] sext_ln152_fu_995_p1;
wire   [4:0] grp_fu_280_p4;
wire   [0:0] icmp_ln151_fu_977_p2;
wire   [31:0] zext_ln181_fu_852_p1;
wire   [31:0] zext_ln178_fu_875_p1;
wire   [31:0] zext_ln175_fu_898_p1;
wire  signed [31:0] or_ln35_17_cast_fu_775_p1;
wire   [31:0] or_ln32_7_cast_cast_cast_fu_808_p1;
wire   [31:0] or_ln32_4_cast_fu_829_p1;
wire  signed [31:0] sext_ln145_fu_964_p1;
wire   [0:0] icmp_ln144_fu_942_p2;
wire   [1:0] grp_fu_300_p4;
wire   [4:0] grp_fu_290_p4;
wire   [2:0] grp_fu_318_p4;
wire   [27:0] or_ln39_5_fu_498_p7;
wire   [27:0] or_ln39_4_fu_519_p7;
wire   [24:0] or_ln32_8_fu_546_p5;
wire   [19:0] or_ln35_9_fu_563_p3;
wire   [4:0] or_ln262_fu_576_p2;
wire   [24:0] or_ln32_9_fu_588_p6;
wire   [19:0] or_ln35_s_fu_607_p3;
wire   [1:0] grp_fu_334_p4;
wire   [2:0] grp_fu_344_p4;
wire   [27:0] tmp_54_fu_620_p7;
wire   [27:0] tmp_66_fu_641_p7;
wire   [24:0] or_ln32_3_fu_662_p6;
wire   [0:0] grp_fu_394_p3;
wire   [9:0] tmp_49_fu_681_p5;
wire  signed [11:0] sext_ln44_1_fu_693_p1;
wire   [2:0] grp_fu_354_p4;
wire   [1:0] grp_fu_402_p4;
wire   [5:0] tmp_44_fu_720_p3;
wire   [0:0] grp_fu_420_p3;
wire   [1:0] grp_fu_438_p4;
reg   [1:0] grp_fu_448_p4;
wire   [0:0] grp_fu_412_p3;
wire   [2:0] grp_fu_428_p4;
wire  signed [12:0] sext_ln52_1_fu_728_p1;
wire   [25:0] or_ln35_6_fu_757_p8;
wire   [9:0] tmp_64_fu_780_p4;
wire   [14:0] zext_ln32_fu_790_p1;
wire   [30:0] or_ln32_7_cast_cast_fu_794_p6;
wire   [24:0] or_ln6_fu_813_p7;
wire   [2:0] grp_fu_364_p4;
wire   [23:0] zext_ln181_cast_fu_834_p8;
wire   [23:0] zext_ln178_cast_fu_857_p8;
wire   [30:0] zext_ln175_cast_fu_880_p8;
wire   [23:0] zext_ln184_cast_fu_903_p8;
wire   [0:0] grp_fu_466_p3;
wire   [0:0] grp_fu_458_p3;
wire   [9:0] imm_1_fu_926_p7;
wire   [29:0] or_ln35_8_fu_948_p7;
wire   [5:0] or_ln3_fu_969_p3;
wire   [17:0] or_ln7_fu_983_p5;
wire   [25:0] or_ln35_3_fu_1000_p6;
wire   [4:0] tmp_40_fu_1019_p3;
wire  signed [11:0] sext_ln52_fu_1027_p1;
wire   [25:0] or_ln35_2_fu_1056_p7;
wire   [9:0] tmp_37_fu_1077_p5;
wire  signed [11:0] sext_ln44_fu_1089_p1;
wire   [26:0] or_ln39_3_fu_1116_p11;
wire   [26:0] or_ln39_1_fu_1145_p11;
wire   [2:0] grp_fu_474_p4;
wire   [26:0] or_ln35_1_fu_1174_p9;
wire   [26:0] or_ln_fu_1199_p9;
wire   [3:0] tmp_14_fu_1234_p4;
wire   [1:0] tmp_13_fu_1224_p4;
reg   [1:0] tmp_15_fu_1244_p4;
wire   [9:0] nzuimm_fu_1254_p5;
wire   [29:0] or_ln35_5_fu_1272_p7;
wire    ap_ce_reg;

always @ (*) begin
    if (((icmp_ln144_fu_942_p2 == 1'd0) & (trunc_ln_fu_488_p4 == 3'd3) & (grp_fu_280_p4 == 5'd2) & (trunc_ln65_fu_484_p1 == 2'd1))) begin
        ap_phi_mux_retval_11_phi_fu_187_p80 = sext_ln145_fu_964_p1;
    end else if (((trunc_ln_fu_488_p4 == 3'd4) & (grp_fu_374_p4 == 2'd0) & (trunc_ln65_fu_484_p1 == 2'd1))) begin
        ap_phi_mux_retval_11_phi_fu_187_p80 = or_ln32_4_cast_fu_829_p1;
    end else if (((trunc_ln_fu_488_p4 == 3'd4) & (grp_fu_374_p4 == 2'd1) & (trunc_ln65_fu_484_p1 == 2'd1))) begin
        ap_phi_mux_retval_11_phi_fu_187_p80 = or_ln32_7_cast_cast_cast_fu_808_p1;
    end else if (((trunc_ln_fu_488_p4 == 3'd4) & (grp_fu_374_p4 == 2'd2) & (trunc_ln65_fu_484_p1 == 2'd1))) begin
        ap_phi_mux_retval_11_phi_fu_187_p80 = or_ln35_17_cast_fu_775_p1;
    end else if (((trunc_ln_fu_488_p4 == 3'd4) & (grp_fu_384_p4 == 2'd0) & (grp_fu_374_p4 == 2'd3) & (trunc_ln65_fu_484_p1 == 2'd1))) begin
        ap_phi_mux_retval_11_phi_fu_187_p80 = zext_ln175_fu_898_p1;
    end else if (((trunc_ln_fu_488_p4 == 3'd4) & (grp_fu_384_p4 == 2'd1) & (grp_fu_374_p4 == 2'd3) & (trunc_ln65_fu_484_p1 == 2'd1))) begin
        ap_phi_mux_retval_11_phi_fu_187_p80 = zext_ln178_fu_875_p1;
    end else if (((trunc_ln_fu_488_p4 == 3'd4) & (grp_fu_384_p4 == 2'd2) & (grp_fu_374_p4 == 2'd3) & (trunc_ln65_fu_484_p1 == 2'd1))) begin
        ap_phi_mux_retval_11_phi_fu_187_p80 = zext_ln181_fu_852_p1;
    end else if ((~(grp_fu_280_p4 == 5'd0) & ~(grp_fu_280_p4 == 5'd2) & (trunc_ln_fu_488_p4 == 3'd3) & (icmp_ln151_fu_977_p2 == 1'd0) & (trunc_ln65_fu_484_p1 == 2'd1))) begin
        ap_phi_mux_retval_11_phi_fu_187_p80 = sext_ln152_fu_995_p1;
    end else if (((trunc_ln_fu_488_p4 == 3'd4) & (grp_fu_384_p4 == 2'd3) & (grp_fu_374_p4 == 2'd3) & (trunc_ln65_fu_484_p1 == 2'd1))) begin
        ap_phi_mux_retval_11_phi_fu_187_p80 = zext_ln184_fu_921_p1;
    end else if (((trunc_ln_fu_488_p4 == 3'd0) & (trunc_ln65_fu_484_p1 == 2'd1))) begin
        ap_phi_mux_retval_11_phi_fu_187_p80 = or_ln35_8_cast_fu_1072_p1;
    end else if (((trunc_ln_fu_488_p4 == 3'd1) & (trunc_ln65_fu_484_p1 == 2'd1))) begin
        ap_phi_mux_retval_11_phi_fu_187_p80 = or_ln5_fu_1031_p11;
    end else if (((trunc_ln_fu_488_p4 == 3'd2) & (trunc_ln65_fu_484_p1 == 2'd1))) begin
        ap_phi_mux_retval_11_phi_fu_187_p80 = or_ln35_10_cast_fu_1014_p1;
    end else if (((trunc_ln_fu_488_p4 == 3'd5) & (trunc_ln65_fu_484_p1 == 2'd1))) begin
        ap_phi_mux_retval_11_phi_fu_187_p80 = or_ln52_1_fu_732_p11;
    end else if (((trunc_ln_fu_488_p4 == 3'd6) & (trunc_ln65_fu_484_p1 == 2'd1))) begin
        ap_phi_mux_retval_11_phi_fu_187_p80 = or_ln44_5_fu_697_p10;
    end else if (((trunc_ln_fu_488_p4 == 3'd0) & (trunc_ln65_fu_484_p1 == 2'd0) & (icmp_ln78_fu_1266_p2 == 1'd0))) begin
        ap_phi_mux_retval_11_phi_fu_187_p80 = zext_ln79_fu_1288_p1;
    end else if (((trunc_ln_fu_488_p4 == 3'd2) & (trunc_ln65_fu_484_p1 == 2'd0))) begin
        ap_phi_mux_retval_11_phi_fu_187_p80 = or_ln35_2_cast_fu_1219_p1;
    end else if (((trunc_ln_fu_488_p4 == 3'd3) & (trunc_ln65_fu_484_p1 == 2'd0))) begin
        ap_phi_mux_retval_11_phi_fu_187_p80 = or_ln35_5_cast_fu_1194_p1;
    end else if (((trunc_ln_fu_488_p4 == 3'd6) & (trunc_ln65_fu_484_p1 == 2'd0))) begin
        ap_phi_mux_retval_11_phi_fu_187_p80 = or_ln39_3_cast_fu_1169_p1;
    end else if (((trunc_ln_fu_488_p4 == 3'd7) & (trunc_ln65_fu_484_p1 == 2'd0))) begin
        ap_phi_mux_retval_11_phi_fu_187_p80 = or_ln39_7_cast_fu_1140_p1;
    end else if (((grp_fu_328_p2 == 1'd0) & (trunc_ln_fu_488_p4 == 3'd0) & (trunc_ln65_fu_484_p1 == 2'd2))) begin
        ap_phi_mux_retval_11_phi_fu_187_p80 = zext_ln234_fu_676_p1;
    end else if (((grp_fu_328_p2 == 1'd0) & (trunc_ln_fu_488_p4 == 3'd2) & (trunc_ln65_fu_484_p1 == 2'd2))) begin
        ap_phi_mux_retval_11_phi_fu_187_p80 = zext_ln35_1_fu_657_p1;
    end else if (((icmp_ln254_fu_540_p2 == 1'd0) & (grp_fu_310_p3 == 1'd0) & (trunc_ln_fu_488_p4 == 3'd4) & (trunc_ln65_fu_484_p1 == 2'd2))) begin
        ap_phi_mux_retval_11_phi_fu_187_p80 = zext_ln259_fu_558_p1;
    end else if (((grp_fu_328_p2 == 1'd0) & (icmp_ln254_fu_540_p2 == 1'd1) & (grp_fu_310_p3 == 1'd0) & (trunc_ln_fu_488_p4 == 3'd4) & (trunc_ln65_fu_484_p1 == 2'd2))) begin
        ap_phi_mux_retval_11_phi_fu_187_p80 = zext_ln256_fu_571_p1;
    end else if (((icmp_ln262_fu_582_p2 == 1'd0) & (icmp_ln254_fu_540_p2 == 1'd0) & (grp_fu_310_p3 == 1'd1) & (trunc_ln_fu_488_p4 == 3'd4) & (trunc_ln65_fu_484_p1 == 2'd2))) begin
        ap_phi_mux_retval_11_phi_fu_187_p80 = zext_ln266_fu_602_p1;
    end else if (((icmp_ln262_fu_582_p2 == 1'd0) & (icmp_ln254_fu_540_p2 == 1'd1) & (grp_fu_310_p3 == 1'd1) & (trunc_ln_fu_488_p4 == 3'd4) & (trunc_ln65_fu_484_p1 == 2'd2))) begin
        ap_phi_mux_retval_11_phi_fu_187_p80 = zext_ln264_fu_615_p1;
    end else if (((trunc_ln_fu_488_p4 == 3'd3) & (trunc_ln65_fu_484_p1 == 2'd2))) begin
        ap_phi_mux_retval_11_phi_fu_187_p80 = zext_ln35_fu_636_p1;
    end else if (((trunc_ln_fu_488_p4 == 3'd6) & (trunc_ln65_fu_484_p1 == 2'd2))) begin
        ap_phi_mux_retval_11_phi_fu_187_p80 = or_ln39_10_cast_fu_535_p1;
    end else if (((trunc_ln_fu_488_p4 == 3'd7) & (trunc_ln65_fu_484_p1 == 2'd2))) begin
        ap_phi_mux_retval_11_phi_fu_187_p80 = or_ln39_13_cast_fu_514_p1;
    end else if (((trunc_ln65_fu_484_p1 == 2'd3) | ((trunc_ln_fu_488_p4 == 3'd1) & (trunc_ln65_fu_484_p1 == 2'd2)) | ((trunc_ln_fu_488_p4 == 3'd5) & (trunc_ln65_fu_484_p1 == 2'd2)) | (~(trunc_ln_fu_488_p4 == 3'd6) & ~(trunc_ln_fu_488_p4 == 3'd3) & ~(trunc_ln_fu_488_p4 == 3'd2) & ~(trunc_ln_fu_488_p4 == 3'd0) & ~(trunc_ln_fu_488_p4 == 3'd7) & (trunc_ln65_fu_484_p1 == 2'd0)) | ((trunc_ln_fu_488_p4 == 3'd3) & (grp_fu_280_p4 == 5'd0) & (trunc_ln65_fu_484_p1 == 2'd1)) | ((trunc_ln_fu_488_p4 == 3'd0) & (trunc_ln65_fu_484_p1 == 2'd0) & (icmp_ln78_fu_1266_p2 == 1'd1)) | ((icmp_ln144_fu_942_p2 == 1'd1) & (trunc_ln_fu_488_p4 == 3'd3) & (grp_fu_280_p4 == 5'd2) & (trunc_ln65_fu_484_p1 == 2'd1)) | ((icmp_ln262_fu_582_p2 == 1'd1) & (grp_fu_310_p3 == 1'd1) & (trunc_ln_fu_488_p4 == 3'd4) & (trunc_ln65_fu_484_p1 == 2'd2)) | ((grp_fu_328_p2 == 1'd1) & (icmp_ln254_fu_540_p2 == 1'd1) & (grp_fu_310_p3 == 1'd0) & (trunc_ln_fu_488_p4 == 3'd4) & (trunc_ln65_fu_484_p1 == 2'd2)) | ((grp_fu_328_p2 == 1'd1) & (trunc_ln_fu_488_p4 == 3'd2) & (trunc_ln65_fu_484_p1 
    == 2'd2)) | ((grp_fu_328_p2 == 1'd1) & (trunc_ln_fu_488_p4 == 3'd0) & (trunc_ln65_fu_484_p1 == 2'd2)) | (~(grp_fu_280_p4 == 5'd0) & ~(grp_fu_280_p4 == 5'd2) & (trunc_ln_fu_488_p4 == 3'd3) & (icmp_ln151_fu_977_p2 == 1'd1) & (trunc_ln65_fu_484_p1 == 2'd1)))) begin
        ap_phi_mux_retval_11_phi_fu_187_p80 = 32'd4294967295;
    end else if (((trunc_ln_fu_488_p4 == 3'd7) & (trunc_ln65_fu_484_p1 == 2'd1))) begin
        ap_phi_mux_retval_11_phi_fu_187_p80 = or_ln44_2_fu_1093_p10;
    end else begin
        ap_phi_mux_retval_11_phi_fu_187_p80 = 'bx;
    end
end

assign ap_ready = 1'b1;

assign grp_fu_280_p4 = {{c[11:7]}};

assign grp_fu_290_p4 = {{c[6:2]}};

assign grp_fu_300_p4 = {{c[8:7]}};

assign grp_fu_310_p3 = c[32'd12];

assign grp_fu_318_p4 = {{c[11:9]}};

assign grp_fu_328_p2 = ((grp_fu_280_p4 == 5'd0) ? 1'b1 : 1'b0);

assign grp_fu_334_p4 = {{c[3:2]}};

assign grp_fu_344_p4 = {{c[6:4]}};

assign grp_fu_354_p4 = {{c[9:7]}};

assign grp_fu_364_p4 = {{c[4:2]}};

assign grp_fu_374_p4 = {{c[11:10]}};

assign grp_fu_384_p4 = {{c[6:5]}};

assign grp_fu_394_p3 = c[32'd2];

assign grp_fu_402_p4 = {{c[4:3]}};

assign grp_fu_412_p3 = c[32'd11];

assign grp_fu_420_p3 = c[32'd8];

assign grp_fu_428_p4 = {{c[5:3]}};

assign grp_fu_438_p4 = {{c[10:9]}};

integer ap_tvar_int_0;

always @ (c) begin
    for (ap_tvar_int_0 = 2 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 7 - 6) begin
            grp_fu_448_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            grp_fu_448_p4[ap_tvar_int_0] = c[7 - ap_tvar_int_0];
        end
    end
end

assign grp_fu_458_p3 = c[32'd6];

assign grp_fu_466_p3 = c[32'd5];

assign grp_fu_474_p4 = {{c[12:10]}};

assign icmp_ln144_fu_942_p2 = ((imm_1_fu_926_p7 == 10'd0) ? 1'b1 : 1'b0);

assign icmp_ln151_fu_977_p2 = ((or_ln3_fu_969_p3 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln254_fu_540_p2 = ((grp_fu_290_p4 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln262_fu_582_p2 = ((or_ln262_fu_576_p2 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln78_fu_1266_p2 = ((nzuimm_fu_1254_p5 == 10'd0) ? 1'b1 : 1'b0);

assign imm_1_fu_926_p7 = {{{{{{grp_fu_310_p3}, {grp_fu_402_p4}}, {grp_fu_466_p3}}, {grp_fu_394_p3}}, {grp_fu_458_p3}}, {4'd0}};

assign nzuimm_fu_1254_p5 = {{{{tmp_14_fu_1234_p4}, {tmp_13_fu_1224_p4}}, {tmp_15_fu_1244_p4}}, {2'd0}};

assign or_ln262_fu_576_p2 = (grp_fu_290_p4 | grp_fu_280_p4);

assign or_ln32_3_fu_662_p6 = {{{{{grp_fu_290_p4}, {grp_fu_280_p4}}, {3'd1}}, {grp_fu_280_p4}}, {7'd19}};

assign or_ln32_4_cast_fu_829_p1 = or_ln6_fu_813_p7;

assign or_ln32_7_cast_cast_cast_fu_808_p1 = or_ln32_7_cast_cast_fu_794_p6;

assign or_ln32_7_cast_cast_fu_794_p6 = {{{{{{{{1'd1}, {zext_ln32_fu_790_p1}}}, {5'd21}}}, {grp_fu_354_p4}}}, {7'd19}};

assign or_ln32_8_fu_546_p5 = {{{{grp_fu_290_p4}, {8'd0}}, {grp_fu_280_p4}}, {7'd51}};

assign or_ln32_9_fu_588_p6 = {{{{{grp_fu_290_p4}, {grp_fu_280_p4}}, {3'd0}}, {grp_fu_280_p4}}, {7'd51}};

assign or_ln35_10_cast_fu_1014_p1 = $signed(or_ln35_3_fu_1000_p6);

assign or_ln35_17_cast_fu_775_p1 = $signed(or_ln35_6_fu_757_p8);

assign or_ln35_1_fu_1174_p9 = {{{{{{{{grp_fu_466_p3}, {grp_fu_474_p4}}, {grp_fu_458_p3}}, {4'd1}}, {grp_fu_354_p4}}, {5'd9}}, {grp_fu_364_p4}}, {7'd7}};

assign or_ln35_2_cast_fu_1219_p1 = or_ln_fu_1199_p9;

assign or_ln35_2_fu_1056_p7 = {{{{{{grp_fu_310_p3}, {grp_fu_290_p4}}, {grp_fu_280_p4}}, {3'd0}}, {grp_fu_280_p4}}, {7'd19}};

assign or_ln35_3_fu_1000_p6 = {{{{{grp_fu_310_p3}, {grp_fu_290_p4}}, {8'd0}}, {grp_fu_280_p4}}, {7'd19}};

assign or_ln35_5_cast_fu_1194_p1 = or_ln35_1_fu_1174_p9;

assign or_ln35_5_fu_1272_p7 = {{{{{{tmp_14_fu_1234_p4}, {tmp_13_fu_1224_p4}}, {tmp_15_fu_1244_p4}}, {12'd65}}, {grp_fu_364_p4}}, {7'd19}};

assign or_ln35_6_fu_757_p8 = {{{{{{{grp_fu_310_p3}, {grp_fu_290_p4}}, {2'd1}}, {grp_fu_354_p4}}, {5'd29}}, {grp_fu_354_p4}}, {7'd19}};

assign or_ln35_8_cast_fu_1072_p1 = $signed(or_ln35_2_fu_1056_p7);

assign or_ln35_8_fu_948_p7 = {{{{{{grp_fu_310_p3}, {grp_fu_402_p4}}, {grp_fu_466_p3}}, {grp_fu_394_p3}}, {grp_fu_458_p3}}, {24'd65811}};

assign or_ln35_9_fu_563_p3 = {{grp_fu_280_p4}, {15'd103}};

assign or_ln35_s_fu_607_p3 = {{grp_fu_280_p4}, {15'd231}};

assign or_ln39_10_cast_fu_535_p1 = or_ln39_4_fu_519_p7;

assign or_ln39_13_cast_fu_514_p1 = or_ln39_5_fu_498_p7;

assign or_ln39_1_fu_1145_p11 = {{{{{{{{{{grp_fu_466_p3}, {grp_fu_310_p3}}, {2'd1}}, {grp_fu_364_p4}}, {2'd1}}, {grp_fu_354_p4}}, {3'd2}}, {grp_fu_374_p4}}, {grp_fu_458_p3}}, {9'd35}};

assign or_ln39_3_cast_fu_1169_p1 = or_ln39_1_fu_1145_p11;

assign or_ln39_3_fu_1116_p11 = {{{{{{{{{{grp_fu_466_p3}, {grp_fu_310_p3}}, {2'd1}}, {grp_fu_364_p4}}, {2'd1}}, {grp_fu_354_p4}}, {3'd2}}, {grp_fu_374_p4}}, {grp_fu_458_p3}}, {9'd39}};

assign or_ln39_4_fu_519_p7 = {{{{{{grp_fu_300_p4}, {grp_fu_310_p3}}, {grp_fu_290_p4}}, {8'd18}}, {grp_fu_318_p4}}, {9'd35}};

assign or_ln39_5_fu_498_p7 = {{{{{{grp_fu_300_p4}, {grp_fu_310_p3}}, {grp_fu_290_p4}}, {8'd18}}, {grp_fu_318_p4}}, {9'd39}};

assign or_ln39_7_cast_fu_1140_p1 = or_ln39_3_fu_1116_p11;

assign or_ln3_fu_969_p3 = {{grp_fu_310_p3}, {grp_fu_290_p4}};

assign or_ln44_2_fu_1093_p10 = {{{{{{{{{grp_fu_310_p3}, {sext_ln44_fu_1089_p1}}, {1'd1}}, {grp_fu_354_p4}}, {3'd1}}, {grp_fu_374_p4}}, {grp_fu_402_p4}}, {grp_fu_310_p3}}, {7'd99}};

assign or_ln44_5_fu_697_p10 = {{{{{{{{{grp_fu_310_p3}, {sext_ln44_1_fu_693_p1}}, {1'd1}}, {grp_fu_354_p4}}, {3'd0}}, {grp_fu_374_p4}}, {grp_fu_402_p4}}, {grp_fu_310_p3}}, {7'd99}};

assign or_ln52_1_fu_732_p11 = {{{{{{{{{{grp_fu_310_p3}, {grp_fu_420_p3}}, {grp_fu_438_p4}}, {grp_fu_448_p4}}, {grp_fu_394_p3}}, {grp_fu_412_p3}}, {grp_fu_428_p4}}, {grp_fu_310_p3}}, {sext_ln52_1_fu_728_p1}}, {7'd111}};

assign or_ln5_fu_1031_p11 = {{{{{{{{{{grp_fu_310_p3}, {grp_fu_420_p3}}, {grp_fu_438_p4}}, {grp_fu_448_p4}}, {grp_fu_394_p3}}, {grp_fu_412_p3}}, {grp_fu_428_p4}}, {grp_fu_310_p3}}, {sext_ln52_fu_1027_p1}}, {8'd239}};

assign or_ln6_fu_813_p7 = {{{{{{grp_fu_290_p4}, {2'd1}}, {grp_fu_354_p4}}, {5'd21}}, {grp_fu_354_p4}}, {7'd19}};

assign or_ln7_fu_983_p5 = {{{{grp_fu_310_p3}, {grp_fu_290_p4}}, {grp_fu_280_p4}}, {7'd55}};

assign or_ln_fu_1199_p9 = {{{{{{{{grp_fu_466_p3}, {grp_fu_474_p4}}, {grp_fu_458_p3}}, {4'd1}}, {grp_fu_354_p4}}, {5'd9}}, {grp_fu_364_p4}}, {7'd3}};

assign sext_ln145_fu_964_p1 = $signed(or_ln35_8_fu_948_p7);

assign sext_ln152_fu_995_p1 = $signed(or_ln7_fu_983_p5);

assign sext_ln44_1_fu_693_p1 = $signed(tmp_49_fu_681_p5);

assign sext_ln44_fu_1089_p1 = $signed(tmp_37_fu_1077_p5);

assign sext_ln52_1_fu_728_p1 = $signed(tmp_44_fu_720_p3);

assign sext_ln52_fu_1027_p1 = $signed(tmp_40_fu_1019_p3);

assign tmp_13_fu_1224_p4 = {{c[12:11]}};

assign tmp_14_fu_1234_p4 = {{c[10:7]}};

integer ap_tvar_int_1;

always @ (c) begin
    for (ap_tvar_int_1 = 2 - 1; ap_tvar_int_1 >= 0; ap_tvar_int_1 = ap_tvar_int_1 - 1) begin
        if (ap_tvar_int_1 > 6 - 5) begin
            tmp_15_fu_1244_p4[ap_tvar_int_1] = 1'b0;
        end else begin
            tmp_15_fu_1244_p4[ap_tvar_int_1] = c[6 - ap_tvar_int_1];
        end
    end
end

assign tmp_37_fu_1077_p5 = {{{{grp_fu_310_p3}, {grp_fu_384_p4}}, {grp_fu_394_p3}}, {6'd0}};

assign tmp_40_fu_1019_p3 = {{grp_fu_310_p3}, {4'd0}};

assign tmp_44_fu_720_p3 = {{grp_fu_310_p3}, {5'd0}};

assign tmp_49_fu_681_p5 = {{{{grp_fu_310_p3}, {grp_fu_384_p4}}, {grp_fu_394_p3}}, {6'd0}};

assign tmp_54_fu_620_p7 = {{{{{{grp_fu_334_p4}, {grp_fu_310_p3}}, {grp_fu_344_p4}}, {10'd18}}, {grp_fu_280_p4}}, {7'd7}};

assign tmp_64_fu_780_p4 = {{{grp_fu_290_p4}, {2'd1}}, {grp_fu_354_p4}};

assign tmp_66_fu_641_p7 = {{{{{{grp_fu_334_p4}, {grp_fu_310_p3}}, {grp_fu_344_p4}}, {10'd18}}, {grp_fu_280_p4}}, {7'd3}};

assign trunc_ln65_fu_484_p1 = c[1:0];

assign trunc_ln_fu_488_p4 = {{c[15:13]}};

assign zext_ln175_cast_fu_880_p8 = {{{{{{{{{{{{8'd129}, {grp_fu_364_p4}}}, {2'd1}}}, {grp_fu_354_p4}}}, {5'd1}}}, {grp_fu_354_p4}}}, {7'd51}};

assign zext_ln175_fu_898_p1 = zext_ln175_cast_fu_880_p8;

assign zext_ln178_cast_fu_857_p8 = {{{{{{{{{{{{1'd1}, {grp_fu_364_p4}}}, {2'd1}}}, {grp_fu_354_p4}}}, {5'd17}}}, {grp_fu_354_p4}}}, {7'd51}};

assign zext_ln178_fu_875_p1 = zext_ln178_cast_fu_857_p8;

assign zext_ln181_cast_fu_834_p8 = {{{{{{{{{{{{1'd1}, {grp_fu_364_p4}}}, {2'd1}}}, {grp_fu_354_p4}}}, {5'd25}}}, {grp_fu_354_p4}}}, {7'd51}};

assign zext_ln181_fu_852_p1 = zext_ln181_cast_fu_834_p8;

assign zext_ln184_cast_fu_903_p8 = {{{{{{{{{{{{1'd1}, {grp_fu_364_p4}}}, {2'd1}}}, {grp_fu_354_p4}}}, {5'd29}}}, {grp_fu_354_p4}}}, {7'd51}};

assign zext_ln184_fu_921_p1 = zext_ln184_cast_fu_903_p8;

assign zext_ln234_fu_676_p1 = or_ln32_3_fu_662_p6;

assign zext_ln256_fu_571_p1 = or_ln35_9_fu_563_p3;

assign zext_ln259_fu_558_p1 = or_ln32_8_fu_546_p5;

assign zext_ln264_fu_615_p1 = or_ln35_s_fu_607_p3;

assign zext_ln266_fu_602_p1 = or_ln32_9_fu_588_p6;

assign zext_ln32_fu_790_p1 = tmp_64_fu_780_p4;

assign zext_ln35_1_fu_657_p1 = tmp_66_fu_641_p7;

assign zext_ln35_fu_636_p1 = tmp_54_fu_620_p7;

assign zext_ln79_fu_1288_p1 = or_ln35_5_fu_1272_p7;

assign ap_return = ap_phi_mux_retval_11_phi_fu_187_p80;

endmodule //rv32_ooo_tick_expand
