# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /media/andy/9cf23886-b985-4f84-a422-2da06e76f300/home/byovsh/Documents/Vscode/Proyecto/RV32IMFC_hls/rv32_ooo_proj/solution1/impl/verilog/rv32_ooo_tick.xdc

# Block Designs: bd/bd_0/bd_0.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0 || ORIG_REF_NAME==bd_0} -quiet] -quiet

# IP: bd/bd_0/ip/bd_0_hls_inst_0/bd_0_hls_inst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0_hls_inst_0 || ORIG_REF_NAME==bd_0_hls_inst_0} -quiet] -quiet

# XDC: /media/andy/9cf23886-b985-4f84-a422-2da06e76f300/home/byovsh/Documents/Vscode/Proyecto/RV32IMFC_hls/rv32_ooo_proj/solution1/impl/verilog/project.gen/sources_1/bd/bd_0/bd_0_ooc.xdc
