// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module rv32_ooo_tick_read_operand (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        reg_r,
        rat_has_tag_address0,
        rat_has_tag_ce0,
        rat_has_tag_q0,
        rat_tag_address0,
        rat_tag_ce0,
        rat_tag_q0,
        rob_ready_address0,
        rob_ready_ce0,
        rob_ready_q0,
        regfile_address0,
        regfile_ce0,
        regfile_q0,
        rob_value_address0,
        rob_value_ce0,
        rob_value_q0,
        ap_return_0,
        ap_return_1,
        ap_return_2
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [4:0] reg_r;
output  [4:0] rat_has_tag_address0;
output   rat_has_tag_ce0;
input  [0:0] rat_has_tag_q0;
output  [4:0] rat_tag_address0;
output   rat_tag_ce0;
input  [2:0] rat_tag_q0;
output  [2:0] rob_ready_address0;
output   rob_ready_ce0;
input  [0:0] rob_ready_q0;
output  [4:0] regfile_address0;
output   regfile_ce0;
input  [31:0] regfile_q0;
output  [2:0] rob_value_address0;
output   rob_value_ce0;
input  [31:0] rob_value_q0;
output  [0:0] ap_return_0;
output  [31:0] ap_return_1;
output  [2:0] ap_return_2;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[0:0] ap_return_0;
reg[31:0] ap_return_1;
reg[2:0] ap_return_2;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln262_fu_109_p2;
reg   [0:0] icmp_ln262_reg_222;
reg   [0:0] rat_has_tag_load_reg_244;
wire    ap_CS_fsm_state2;
reg   [2:0] t_reg_251;
reg   [31:0] op_val_reg_261;
wire   [63:0] zext_ln266_fu_115_p1;
wire   [63:0] zext_ln271_fu_122_p1;
reg    rat_has_tag_ce0_local;
reg    rat_tag_ce0_local;
reg    regfile_ce0_local;
reg    rob_ready_ce0_local;
reg    rob_value_ce0_local;
wire    ap_CS_fsm_state3;
wire   [0:0] xor_ln266_fu_128_p2;
wire   [0:0] or_ln271_fu_133_p2;
wire   [0:0] or_ln266_fu_144_p2;
wire   [0:0] xor_ln271_fu_154_p2;
wire   [0:0] and_ln271_fu_160_p2;
wire   [0:0] xor_ln266_1_fu_148_p2;
wire   [0:0] or_ln271_2_fu_165_p2;
wire   [31:0] agg_result_val_fu_178_p7;
wire   [1:0] agg_result_val_fu_178_p8;
wire   [0:0] or_ln271_1_fu_138_p2;
wire   [31:0] agg_result_val_fu_178_p9;
wire   [2:0] agg_result_tag_0_fu_197_p3;
reg   [0:0] ap_return_0_preg;
reg   [31:0] ap_return_1_preg;
reg   [2:0] ap_return_2_preg;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire  signed [1:0] agg_result_val_fu_178_p1;
wire   [1:0] agg_result_val_fu_178_p3;
wire   [1:0] agg_result_val_fu_178_p5;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_return_0_preg = 1'd0;
#0 ap_return_1_preg = 32'd0;
#0 ap_return_2_preg = 3'd0;
end

(* dissolve_hierarchy = "yes" *) rv32_ooo_tick_sparsemux_7_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_7_2_32_1_1_U96(
    .din0(op_val_reg_261),
    .din1(32'd0),
    .din2(rob_value_q0),
    .def(agg_result_val_fu_178_p7),
    .sel(agg_result_val_fu_178_p8),
    .dout(agg_result_val_fu_178_p9)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_0_preg <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            ap_return_0_preg <= or_ln271_1_fu_138_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_1_preg <= 32'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            ap_return_1_preg <= agg_result_val_fu_178_p9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_2_preg <= 3'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            ap_return_2_preg <= agg_result_tag_0_fu_197_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        icmp_ln262_reg_222 <= icmp_ln262_fu_109_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        op_val_reg_261 <= regfile_q0;
        rat_has_tag_load_reg_244 <= rat_has_tag_q0;
        t_reg_251 <= rat_tag_q0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ap_return_0 = or_ln271_1_fu_138_p2;
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ap_return_1 = agg_result_val_fu_178_p9;
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ap_return_2 = agg_result_tag_0_fu_197_p3;
    end else begin
        ap_return_2 = ap_return_2_preg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        rat_has_tag_ce0_local = 1'b1;
    end else begin
        rat_has_tag_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        rat_tag_ce0_local = 1'b1;
    end else begin
        rat_tag_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        regfile_ce0_local = 1'b1;
    end else begin
        regfile_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        rob_ready_ce0_local = 1'b1;
    end else begin
        rob_ready_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        rob_value_ce0_local = 1'b1;
    end else begin
        rob_value_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign agg_result_tag_0_fu_197_p3 = ((or_ln271_1_fu_138_p2[0:0] == 1'b1) ? 3'd0 : t_reg_251);

assign agg_result_val_fu_178_p7 = 'bx;

assign agg_result_val_fu_178_p8 = {{xor_ln266_1_fu_148_p2}, {or_ln271_2_fu_165_p2}};

assign and_ln271_fu_160_p2 = (xor_ln271_fu_154_p2 & rat_has_tag_load_reg_244);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign icmp_ln262_fu_109_p2 = ((reg_r == 5'd0) ? 1'b1 : 1'b0);

assign or_ln266_fu_144_p2 = (rat_has_tag_load_reg_244 | icmp_ln262_reg_222);

assign or_ln271_1_fu_138_p2 = (rob_ready_q0 | or_ln271_fu_133_p2);

assign or_ln271_2_fu_165_p2 = (icmp_ln262_reg_222 | and_ln271_fu_160_p2);

assign or_ln271_fu_133_p2 = (xor_ln266_fu_128_p2 | icmp_ln262_reg_222);

assign rat_has_tag_address0 = zext_ln266_fu_115_p1;

assign rat_has_tag_ce0 = rat_has_tag_ce0_local;

assign rat_tag_address0 = zext_ln266_fu_115_p1;

assign rat_tag_ce0 = rat_tag_ce0_local;

assign regfile_address0 = zext_ln266_fu_115_p1;

assign regfile_ce0 = regfile_ce0_local;

assign rob_ready_address0 = zext_ln271_fu_122_p1;

assign rob_ready_ce0 = rob_ready_ce0_local;

assign rob_value_address0 = zext_ln271_fu_122_p1;

assign rob_value_ce0 = rob_value_ce0_local;

assign xor_ln266_1_fu_148_p2 = (or_ln266_fu_144_p2 ^ 1'd1);

assign xor_ln266_fu_128_p2 = (rat_has_tag_load_reg_244 ^ 1'd1);

assign xor_ln271_fu_154_p2 = (rob_ready_q0 ^ 1'd1);

assign zext_ln266_fu_115_p1 = reg_r;

assign zext_ln271_fu_122_p1 = rat_tag_q0;

endmodule //rv32_ooo_tick_read_operand
