-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity rv32_vector_step is
generic (
    C_M_AXI_GMEM_ADDR_WIDTH : INTEGER := 64;
    C_M_AXI_GMEM_ID_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_AWUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_GMEM_WUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_ARUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_RUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_BUSER_WIDTH : INTEGER := 1;
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 4;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32;
    C_S_AXI_CONTROL_R_ADDR_WIDTH : INTEGER := 5;
    C_S_AXI_CONTROL_R_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_GMEM_USER_VALUE : INTEGER := 0;
    C_M_AXI_GMEM_PROT_VALUE : INTEGER := 0;
    C_M_AXI_GMEM_CACHE_VALUE : INTEGER := 3 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    m_axi_gmem_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_AWREADY : IN STD_LOGIC;
    m_axi_gmem_AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ADDR_WIDTH-1 downto 0);
    m_axi_gmem_AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_AWUSER_WIDTH-1 downto 0);
    m_axi_gmem_WVALID : OUT STD_LOGIC;
    m_axi_gmem_WREADY : IN STD_LOGIC;
    m_axi_gmem_WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_DATA_WIDTH-1 downto 0);
    m_axi_gmem_WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_DATA_WIDTH/8-1 downto 0);
    m_axi_gmem_WLAST : OUT STD_LOGIC;
    m_axi_gmem_WID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_WUSER_WIDTH-1 downto 0);
    m_axi_gmem_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_ARREADY : IN STD_LOGIC;
    m_axi_gmem_ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ADDR_WIDTH-1 downto 0);
    m_axi_gmem_ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ARUSER_WIDTH-1 downto 0);
    m_axi_gmem_RVALID : IN STD_LOGIC;
    m_axi_gmem_RREADY : OUT STD_LOGIC;
    m_axi_gmem_RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_DATA_WIDTH-1 downto 0);
    m_axi_gmem_RLAST : IN STD_LOGIC;
    m_axi_gmem_RID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_RUSER_WIDTH-1 downto 0);
    m_axi_gmem_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_BVALID : IN STD_LOGIC;
    m_axi_gmem_BREADY : OUT STD_LOGIC;
    m_axi_gmem_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_BID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_BUSER_WIDTH-1 downto 0);
    instr : IN STD_LOGIC_VECTOR (31 downto 0);
    rs1_val : IN STD_LOGIC_VECTOR (31 downto 0);
    vregs_in_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    vregs_in_EN_A : OUT STD_LOGIC;
    vregs_in_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
    vregs_in_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    vregs_in_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
    vregs_in_Clk_A : OUT STD_LOGIC;
    vregs_in_Rst_A : OUT STD_LOGIC;
    vregs_in_Addr_B : OUT STD_LOGIC_VECTOR (31 downto 0);
    vregs_in_EN_B : OUT STD_LOGIC;
    vregs_in_WEN_B : OUT STD_LOGIC_VECTOR (3 downto 0);
    vregs_in_Din_B : OUT STD_LOGIC_VECTOR (31 downto 0);
    vregs_in_Dout_B : IN STD_LOGIC_VECTOR (31 downto 0);
    vregs_in_Clk_B : OUT STD_LOGIC;
    vregs_in_Rst_B : OUT STD_LOGIC;
    vregs_out_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    vregs_out_EN_A : OUT STD_LOGIC;
    vregs_out_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
    vregs_out_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    vregs_out_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
    vregs_out_Clk_A : OUT STD_LOGIC;
    vregs_out_Rst_A : OUT STD_LOGIC;
    halted : OUT STD_LOGIC_VECTOR (0 downto 0);
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC;
    s_axi_control_r_AWVALID : IN STD_LOGIC;
    s_axi_control_r_AWREADY : OUT STD_LOGIC;
    s_axi_control_r_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_R_ADDR_WIDTH-1 downto 0);
    s_axi_control_r_WVALID : IN STD_LOGIC;
    s_axi_control_r_WREADY : OUT STD_LOGIC;
    s_axi_control_r_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_R_DATA_WIDTH-1 downto 0);
    s_axi_control_r_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_R_DATA_WIDTH/8-1 downto 0);
    s_axi_control_r_ARVALID : IN STD_LOGIC;
    s_axi_control_r_ARREADY : OUT STD_LOGIC;
    s_axi_control_r_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_R_ADDR_WIDTH-1 downto 0);
    s_axi_control_r_RVALID : OUT STD_LOGIC;
    s_axi_control_r_RREADY : IN STD_LOGIC;
    s_axi_control_r_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_R_DATA_WIDTH-1 downto 0);
    s_axi_control_r_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_r_BVALID : OUT STD_LOGIC;
    s_axi_control_r_BREADY : IN STD_LOGIC;
    s_axi_control_r_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0) );
end;


architecture behav of rv32_vector_step is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "rv32_vector_step_rv32_vector_step,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=139,HLS_SYN_TPT=none,HLS_SYN_MEM=4,HLS_SYN_DSP=0,HLS_SYN_FF=1232,HLS_SYN_LUT=1998,HLS_VERSION=2024_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000001000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000010000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000100000000000000000000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (30 downto 0) := "0000000001000000000000000000000";
    constant ap_ST_fsm_state23 : STD_LOGIC_VECTOR (30 downto 0) := "0000000010000000000000000000000";
    constant ap_ST_fsm_state24 : STD_LOGIC_VECTOR (30 downto 0) := "0000000100000000000000000000000";
    constant ap_ST_fsm_state25 : STD_LOGIC_VECTOR (30 downto 0) := "0000001000000000000000000000000";
    constant ap_ST_fsm_state26 : STD_LOGIC_VECTOR (30 downto 0) := "0000010000000000000000000000000";
    constant ap_ST_fsm_state27 : STD_LOGIC_VECTOR (30 downto 0) := "0000100000000000000000000000000";
    constant ap_ST_fsm_state28 : STD_LOGIC_VECTOR (30 downto 0) := "0001000000000000000000000000000";
    constant ap_ST_fsm_state29 : STD_LOGIC_VECTOR (30 downto 0) := "0010000000000000000000000000000";
    constant ap_ST_fsm_state30 : STD_LOGIC_VECTOR (30 downto 0) := "0100000000000000000000000000000";
    constant ap_ST_fsm_state31 : STD_LOGIC_VECTOR (30 downto 0) := "1000000000000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv32_1C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011100";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv7_57 : STD_LOGIC_VECTOR (6 downto 0) := "1010111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv7_27 : STD_LOGIC_VECTOR (6 downto 0) := "0100111";
    constant ap_const_lv7_7 : STD_LOGIC_VECTOR (6 downto 0) := "0000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant C_M_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv64_4 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000100";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv6_2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_const_lv6_25 : STD_LOGIC_VECTOR (5 downto 0) := "100101";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal mem : STD_LOGIC_VECTOR (63 downto 0);
    signal gmem_blk_n_AR : STD_LOGIC;
    signal ap_CS_fsm_state19 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state19 : signal is "none";
    signal gmem_blk_n_R : STD_LOGIC;
    signal ap_CS_fsm_state27 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state27 : signal is "none";
    signal ap_CS_fsm_state28 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state28 : signal is "none";
    signal ap_CS_fsm_state29 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state29 : signal is "none";
    signal ap_CS_fsm_state30 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state30 : signal is "none";
    signal gmem_blk_n_AW : STD_LOGIC;
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal gmem_blk_n_W : STD_LOGIC;
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal gmem_blk_n_B : STD_LOGIC;
    signal ap_CS_fsm_state18 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state18 : signal is "none";
    signal reg_509 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal trunc_ln26_fu_527_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal or_ln36_fu_543_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln89_1_fu_599_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_453_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_467_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_481_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal reg_513 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal gmem_0_AWVALID : STD_LOGIC;
    signal gmem_0_AWREADY : STD_LOGIC;
    signal gmem_0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal gmem_0_WVALID : STD_LOGIC;
    signal gmem_0_WREADY : STD_LOGIC;
    signal gmem_0_ARVALID : STD_LOGIC;
    signal gmem_0_ARREADY : STD_LOGIC;
    signal gmem_0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal gmem_0_RVALID : STD_LOGIC;
    signal gmem_0_RREADY : STD_LOGIC;
    signal gmem_0_RDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal gmem_0_RFIFONUM : STD_LOGIC_VECTOR (8 downto 0);
    signal gmem_0_BVALID : STD_LOGIC;
    signal gmem_0_BREADY : STD_LOGIC;
    signal reg_522 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln26_reg_1013 : STD_LOGIC_VECTOR (6 downto 0);
    signal is_add_fu_563_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal is_add_reg_1020 : STD_LOGIC_VECTOR (0 downto 0);
    signal is_sub_fu_575_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal is_sub_reg_1028 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln89_1_reg_1036 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_reg_1040 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_8_reg_1048 : STD_LOGIC_VECTOR (4 downto 0);
    signal gmem_addr_1_reg_1065 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln62_reg_1074 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln63_reg_1078 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln63_1_reg_1082 : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem_addr_reg_1086 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_ap_start : STD_LOGIC;
    signal grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_ap_done : STD_LOGIC;
    signal grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_ap_idle : STD_LOGIC;
    signal grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_ap_ready : STD_LOGIC;
    signal grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_vregs_in_Addr_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_vregs_in_EN_A : STD_LOGIC;
    signal grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_vregs_in_WEN_A : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_vregs_in_Din_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_vregs_out_Addr_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_vregs_out_EN_A : STD_LOGIC;
    signal grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_vregs_out_WEN_A : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_vregs_out_Din_A : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_halted_local_2_phi_fu_406_p8 : STD_LOGIC_VECTOR (0 downto 0);
    signal halted_local_2_reg_401 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state31 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state31 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_ap_start_reg : STD_LOGIC := '0';
    signal vregs_out_WEN_A_out : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln92_fu_715_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln93_fu_720_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln92_1_fu_745_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln93_1_fu_757_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln98_fu_733_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln92_2_fu_797_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln93_2_fu_809_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln98_1_fu_785_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln92_3_fu_849_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln93_3_fu_861_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln98_2_fu_837_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln98_3_fu_904_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln79_fu_917_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln79_2_fu_930_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln79_3_fu_943_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln79_4_fu_956_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln69_fu_969_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln69_2_fu_982_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln69_3_fu_995_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln69_4_fu_1008_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln81_fu_653_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln69_fu_691_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal vregs_in_EN_B_local : STD_LOGIC;
    signal vregs_in_Addr_B_local : STD_LOGIC_VECTOR (31 downto 0);
    signal vregs_in_Addr_B_orig : STD_LOGIC_VECTOR (31 downto 0);
    signal vregs_in_EN_A_local : STD_LOGIC;
    signal vregs_in_Addr_A_local : STD_LOGIC_VECTOR (31 downto 0);
    signal vregs_in_Addr_A_orig : STD_LOGIC_VECTOR (31 downto 0);
    signal vregs_out_WEN_A_local : STD_LOGIC_VECTOR (3 downto 0);
    signal vregs_out_Din_A_local : STD_LOGIC_VECTOR (31 downto 0);
    signal r_1121420_fu_769_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal vregs_out_EN_A_local : STD_LOGIC;
    signal vregs_out_Addr_A_local : STD_LOGIC_VECTOR (31 downto 0);
    signal vregs_out_Addr_A_orig : STD_LOGIC_VECTOR (31 downto 0);
    signal r_1_11618_fu_821_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_1_222_fu_873_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_3_fu_888_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_435_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_fu_459_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_fu_473_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_497_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_497_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_503_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_503_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln84_fu_531_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln36_fu_537_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_fu_549_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln86_fu_557_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln87_fu_569_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln88_fu_581_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal is_mul_fu_587_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln89_fu_593_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_487_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal and_ln1_fu_625_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln79_1_fu_633_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln79_fu_637_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln1_fu_643_p4 : STD_LOGIC_VECTOR (61 downto 0);
    signal and_ln_fu_663_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln69_1_fu_671_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln69_fu_675_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln_fu_681_p4 : STD_LOGIC_VECTOR (61 downto 0);
    signal mul1_fu_701_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal mul2_fu_708_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal mul3_fu_725_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal or_ln_fu_738_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal or_ln1_fu_750_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_503_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_429_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_497_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_5_fu_762_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln2_fu_777_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal or_ln92_1_fu_790_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal or_ln93_1_fu_802_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal r_6_fu_814_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln98_1_fu_829_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal or_ln92_2_fu_842_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal or_ln93_2_fu_854_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal r_7_fu_866_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_fu_881_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln98_2_fu_896_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal mul4_fu_909_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal or_ln4_fu_922_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal or_ln79_1_fu_935_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal or_ln79_2_fu_948_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal mul_fu_961_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal or_ln3_fu_974_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal or_ln69_1_fu_987_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal or_ln69_2_fu_1000_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ST_fsm_state17_blk : STD_LOGIC;
    signal ap_ST_fsm_state18_blk : STD_LOGIC;
    signal ap_ST_fsm_state19_blk : STD_LOGIC;
    signal ap_ST_fsm_state20_blk : STD_LOGIC;
    signal ap_ST_fsm_state21_blk : STD_LOGIC;
    signal ap_ST_fsm_state22_blk : STD_LOGIC;
    signal ap_ST_fsm_state23_blk : STD_LOGIC;
    signal ap_ST_fsm_state24_blk : STD_LOGIC;
    signal ap_ST_fsm_state25_blk : STD_LOGIC;
    signal ap_ST_fsm_state26_blk : STD_LOGIC;
    signal ap_ST_fsm_state27_blk : STD_LOGIC;
    signal ap_ST_fsm_state28_blk : STD_LOGIC;
    signal ap_ST_fsm_state29_blk : STD_LOGIC;
    signal ap_ST_fsm_state30_blk : STD_LOGIC;
    signal ap_ST_fsm_state31_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component rv32_vector_step_rv32_vector_step_Pipeline_VITIS_LOOP_54_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        vregs_in_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        vregs_in_EN_A : OUT STD_LOGIC;
        vregs_in_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
        vregs_in_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        vregs_in_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
        vregs_out_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        vregs_out_EN_A : OUT STD_LOGIC;
        vregs_out_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
        vregs_out_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        vregs_out_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component rv32_vector_step_mul_32s_32s_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component rv32_vector_step_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component rv32_vector_step_control_r_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        mem : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component rv32_vector_step_gmem_m_axi IS
    generic (
        CONSERVATIVE : INTEGER;
        USER_MAXREQS : INTEGER;
        MAX_READ_BURST_LENGTH : INTEGER;
        MAX_WRITE_BURST_LENGTH : INTEGER;
        C_M_AXI_ID_WIDTH : INTEGER;
        C_M_AXI_ADDR_WIDTH : INTEGER;
        C_M_AXI_DATA_WIDTH : INTEGER;
        C_M_AXI_AWUSER_WIDTH : INTEGER;
        C_M_AXI_ARUSER_WIDTH : INTEGER;
        C_M_AXI_WUSER_WIDTH : INTEGER;
        C_M_AXI_RUSER_WIDTH : INTEGER;
        C_M_AXI_BUSER_WIDTH : INTEGER;
        C_USER_VALUE : INTEGER;
        C_PROT_VALUE : INTEGER;
        C_CACHE_VALUE : INTEGER;
        CH0_USER_RFIFONUM_WIDTH : INTEGER;
        CH0_USER_DW : INTEGER;
        CH0_USER_AW : INTEGER;
        NUM_READ_OUTSTANDING : INTEGER;
        NUM_WRITE_OUTSTANDING : INTEGER );
    port (
        AWVALID : OUT STD_LOGIC;
        AWREADY : IN STD_LOGIC;
        AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_AWUSER_WIDTH-1 downto 0);
        WVALID : OUT STD_LOGIC;
        WREADY : IN STD_LOGIC;
        WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH/8-1 downto 0);
        WLAST : OUT STD_LOGIC;
        WID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WUSER_WIDTH-1 downto 0);
        ARVALID : OUT STD_LOGIC;
        ARREADY : IN STD_LOGIC;
        ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_ARUSER_WIDTH-1 downto 0);
        RVALID : IN STD_LOGIC;
        RREADY : OUT STD_LOGIC;
        RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        RLAST : IN STD_LOGIC;
        RID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_RUSER_WIDTH-1 downto 0);
        RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BVALID : IN STD_LOGIC;
        BREADY : OUT STD_LOGIC;
        BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_BUSER_WIDTH-1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        I_CH0_ARVALID : IN STD_LOGIC;
        I_CH0_ARREADY : OUT STD_LOGIC;
        I_CH0_ARADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_ARLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_RVALID : OUT STD_LOGIC;
        I_CH0_RREADY : IN STD_LOGIC;
        I_CH0_RDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_RFIFONUM : OUT STD_LOGIC_VECTOR (8 downto 0);
        I_CH0_AWVALID : IN STD_LOGIC;
        I_CH0_AWREADY : OUT STD_LOGIC;
        I_CH0_AWADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_AWLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_WVALID : IN STD_LOGIC;
        I_CH0_WREADY : OUT STD_LOGIC;
        I_CH0_WDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_WSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        I_CH0_BVALID : OUT STD_LOGIC;
        I_CH0_BREADY : IN STD_LOGIC );
    end component;



begin
    grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421 : component rv32_vector_step_rv32_vector_step_Pipeline_VITIS_LOOP_54_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_ap_start,
        ap_done => grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_ap_done,
        ap_idle => grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_ap_idle,
        ap_ready => grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_ap_ready,
        vregs_in_Addr_A => grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_vregs_in_Addr_A,
        vregs_in_EN_A => grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_vregs_in_EN_A,
        vregs_in_WEN_A => grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_vregs_in_WEN_A,
        vregs_in_Din_A => grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_vregs_in_Din_A,
        vregs_in_Dout_A => vregs_in_Dout_A,
        vregs_out_Addr_A => grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_vregs_out_Addr_A,
        vregs_out_EN_A => grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_vregs_out_EN_A,
        vregs_out_WEN_A => grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_vregs_out_WEN_A,
        vregs_out_Din_A => grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_vregs_out_Din_A,
        vregs_out_Dout_A => ap_const_lv32_0);

    control_s_axi_U : component rv32_vector_step_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    control_r_s_axi_U : component rv32_vector_step_control_r_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_R_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_R_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_r_AWVALID,
        AWREADY => s_axi_control_r_AWREADY,
        AWADDR => s_axi_control_r_AWADDR,
        WVALID => s_axi_control_r_WVALID,
        WREADY => s_axi_control_r_WREADY,
        WDATA => s_axi_control_r_WDATA,
        WSTRB => s_axi_control_r_WSTRB,
        ARVALID => s_axi_control_r_ARVALID,
        ARREADY => s_axi_control_r_ARREADY,
        ARADDR => s_axi_control_r_ARADDR,
        RVALID => s_axi_control_r_RVALID,
        RREADY => s_axi_control_r_RREADY,
        RDATA => s_axi_control_r_RDATA,
        RRESP => s_axi_control_r_RRESP,
        BVALID => s_axi_control_r_BVALID,
        BREADY => s_axi_control_r_BREADY,
        BRESP => s_axi_control_r_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        mem => mem);

    gmem_m_axi_U : component rv32_vector_step_gmem_m_axi
    generic map (
        CONSERVATIVE => 1,
        USER_MAXREQS => 4,
        MAX_READ_BURST_LENGTH => 16,
        MAX_WRITE_BURST_LENGTH => 16,
        C_M_AXI_ID_WIDTH => C_M_AXI_GMEM_ID_WIDTH,
        C_M_AXI_ADDR_WIDTH => C_M_AXI_GMEM_ADDR_WIDTH,
        C_M_AXI_DATA_WIDTH => C_M_AXI_GMEM_DATA_WIDTH,
        C_M_AXI_AWUSER_WIDTH => C_M_AXI_GMEM_AWUSER_WIDTH,
        C_M_AXI_ARUSER_WIDTH => C_M_AXI_GMEM_ARUSER_WIDTH,
        C_M_AXI_WUSER_WIDTH => C_M_AXI_GMEM_WUSER_WIDTH,
        C_M_AXI_RUSER_WIDTH => C_M_AXI_GMEM_RUSER_WIDTH,
        C_M_AXI_BUSER_WIDTH => C_M_AXI_GMEM_BUSER_WIDTH,
        C_USER_VALUE => C_M_AXI_GMEM_USER_VALUE,
        C_PROT_VALUE => C_M_AXI_GMEM_PROT_VALUE,
        C_CACHE_VALUE => C_M_AXI_GMEM_CACHE_VALUE,
        CH0_USER_RFIFONUM_WIDTH => 9,
        CH0_USER_DW => 32,
        CH0_USER_AW => 64,
        NUM_READ_OUTSTANDING => 16,
        NUM_WRITE_OUTSTANDING => 16)
    port map (
        AWVALID => m_axi_gmem_AWVALID,
        AWREADY => m_axi_gmem_AWREADY,
        AWADDR => m_axi_gmem_AWADDR,
        AWID => m_axi_gmem_AWID,
        AWLEN => m_axi_gmem_AWLEN,
        AWSIZE => m_axi_gmem_AWSIZE,
        AWBURST => m_axi_gmem_AWBURST,
        AWLOCK => m_axi_gmem_AWLOCK,
        AWCACHE => m_axi_gmem_AWCACHE,
        AWPROT => m_axi_gmem_AWPROT,
        AWQOS => m_axi_gmem_AWQOS,
        AWREGION => m_axi_gmem_AWREGION,
        AWUSER => m_axi_gmem_AWUSER,
        WVALID => m_axi_gmem_WVALID,
        WREADY => m_axi_gmem_WREADY,
        WDATA => m_axi_gmem_WDATA,
        WSTRB => m_axi_gmem_WSTRB,
        WLAST => m_axi_gmem_WLAST,
        WID => m_axi_gmem_WID,
        WUSER => m_axi_gmem_WUSER,
        ARVALID => m_axi_gmem_ARVALID,
        ARREADY => m_axi_gmem_ARREADY,
        ARADDR => m_axi_gmem_ARADDR,
        ARID => m_axi_gmem_ARID,
        ARLEN => m_axi_gmem_ARLEN,
        ARSIZE => m_axi_gmem_ARSIZE,
        ARBURST => m_axi_gmem_ARBURST,
        ARLOCK => m_axi_gmem_ARLOCK,
        ARCACHE => m_axi_gmem_ARCACHE,
        ARPROT => m_axi_gmem_ARPROT,
        ARQOS => m_axi_gmem_ARQOS,
        ARREGION => m_axi_gmem_ARREGION,
        ARUSER => m_axi_gmem_ARUSER,
        RVALID => m_axi_gmem_RVALID,
        RREADY => m_axi_gmem_RREADY,
        RDATA => m_axi_gmem_RDATA,
        RLAST => m_axi_gmem_RLAST,
        RID => m_axi_gmem_RID,
        RUSER => m_axi_gmem_RUSER,
        RRESP => m_axi_gmem_RRESP,
        BVALID => m_axi_gmem_BVALID,
        BREADY => m_axi_gmem_BREADY,
        BRESP => m_axi_gmem_BRESP,
        BID => m_axi_gmem_BID,
        BUSER => m_axi_gmem_BUSER,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        I_CH0_ARVALID => gmem_0_ARVALID,
        I_CH0_ARREADY => gmem_0_ARREADY,
        I_CH0_ARADDR => gmem_addr_reg_1086,
        I_CH0_ARLEN => gmem_0_ARLEN,
        I_CH0_RVALID => gmem_0_RVALID,
        I_CH0_RREADY => gmem_0_RREADY,
        I_CH0_RDATA => gmem_0_RDATA,
        I_CH0_RFIFONUM => gmem_0_RFIFONUM,
        I_CH0_AWVALID => gmem_0_AWVALID,
        I_CH0_AWREADY => gmem_0_AWREADY,
        I_CH0_AWADDR => gmem_addr_1_reg_1065,
        I_CH0_AWLEN => gmem_0_AWLEN,
        I_CH0_WVALID => gmem_0_WVALID,
        I_CH0_WREADY => gmem_0_WREADY,
        I_CH0_WDATA => reg_513,
        I_CH0_WSTRB => ap_const_lv4_F,
        I_CH0_BVALID => gmem_0_BVALID,
        I_CH0_BREADY => gmem_0_BREADY);

    mul_32s_32s_32_1_1_U1 : component rv32_vector_step_mul_32s_32s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => vregs_in_Dout_A,
        din1 => vregs_in_Dout_B,
        dout => grp_fu_429_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_ap_ready = ap_const_logic_1)) then 
                    grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    halted_local_2_reg_401_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2) and ((((((((not((trunc_ln26_fu_527_p1 = ap_const_lv7_7)) and not((trunc_ln26_fu_527_p1 = ap_const_lv7_27)) and not((trunc_ln26_fu_527_p1 = ap_const_lv7_57))) or (not((trunc_ln26_fu_527_p1 = ap_const_lv7_7)) and not((trunc_ln26_fu_527_p1 = ap_const_lv7_27)) and (or_ln36_fu_543_p2 = ap_const_lv1_0))) or ((grp_fu_481_p2 = ap_const_lv1_0) and (trunc_ln26_fu_527_p1 = ap_const_lv7_27))) or ((grp_fu_467_p2 = ap_const_lv1_0) and (trunc_ln26_fu_527_p1 = ap_const_lv7_27))) or ((grp_fu_453_p2 = ap_const_lv1_0) and (trunc_ln26_fu_527_p1 = ap_const_lv7_27))) or ((grp_fu_481_p2 = ap_const_lv1_0) and (trunc_ln26_fu_527_p1 = ap_const_lv7_7))) or ((grp_fu_467_p2 = ap_const_lv1_0) and (trunc_ln26_fu_527_p1 = ap_const_lv7_7))) or ((grp_fu_453_p2 = ap_const_lv1_0) and (trunc_ln26_fu_527_p1 = ap_const_lv7_7))))) then 
                halted_local_2_reg_401 <= ap_const_lv1_1;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state7) or ((gmem_0_BVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state18)) or ((icmp_ln63_1_reg_1082 = ap_const_lv1_1) and (icmp_ln63_reg_1078 = ap_const_lv1_1) and (icmp_ln62_reg_1074 = ap_const_lv1_1) and (trunc_ln26_reg_1013 = ap_const_lv7_7) and (ap_const_logic_1 = ap_CS_fsm_state31)))) then 
                halted_local_2_reg_401 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    reg_513_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((gmem_0_WREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state12)) or ((gmem_0_WREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10)))) then 
                reg_513 <= vregs_in_Dout_B;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state9) or ((gmem_0_WREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11)))) then 
                reg_513 <= vregs_in_Dout_A;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                gmem_addr_1_reg_1065 <= sext_ln81_fu_653_p1;
                gmem_addr_reg_1086 <= sext_ln69_fu_691_p1;
                icmp_ln62_reg_1074 <= grp_fu_453_p2;
                icmp_ln63_1_reg_1082 <= grp_fu_481_p2;
                icmp_ln63_reg_1078 <= grp_fu_467_p2;
                is_add_reg_1020 <= is_add_fu_563_p2;
                is_sub_reg_1028 <= is_sub_fu_575_p2;
                or_ln89_1_reg_1036 <= or_ln89_1_fu_599_p2;
                tmp_7_reg_1040 <= instr(24 downto 20);
                tmp_8_reg_1048 <= instr(19 downto 15);
                trunc_ln26_reg_1013 <= trunc_ln26_fu_527_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((grp_fu_481_p2 = ap_const_lv1_1) and (grp_fu_467_p2 = ap_const_lv1_1) and (grp_fu_453_p2 = ap_const_lv1_1) and (trunc_ln26_fu_527_p1 = ap_const_lv7_7) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((grp_fu_481_p2 = ap_const_lv1_1) and (grp_fu_467_p2 = ap_const_lv1_1) and (grp_fu_453_p2 = ap_const_lv1_1) and (trunc_ln26_fu_527_p1 = ap_const_lv7_27) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((or_ln89_1_fu_599_p2 = ap_const_lv1_1) and (or_ln36_fu_543_p2 = ap_const_lv1_1) and (trunc_ln26_fu_527_p1 = ap_const_lv7_57) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then
                reg_509 <= instr(11 downto 7);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((gmem_0_RVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state30)) or ((gmem_0_RVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state29)) or ((gmem_0_RVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state28)) or ((gmem_0_RVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state27)))) then
                reg_522 <= gmem_0_RDATA;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state19, ap_CS_fsm_state27, ap_CS_fsm_state28, ap_CS_fsm_state29, ap_CS_fsm_state30, ap_CS_fsm_state8, ap_CS_fsm_state10, ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state18, ap_CS_fsm_state2, trunc_ln26_fu_527_p1, or_ln36_fu_543_p2, or_ln89_1_fu_599_p2, grp_fu_453_p2, grp_fu_467_p2, grp_fu_481_p2, gmem_0_AWREADY, gmem_0_WREADY, gmem_0_ARREADY, gmem_0_RVALID, gmem_0_BVALID, grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_ap_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2) and ((((((((not((trunc_ln26_fu_527_p1 = ap_const_lv7_7)) and not((trunc_ln26_fu_527_p1 = ap_const_lv7_27)) and not((trunc_ln26_fu_527_p1 = ap_const_lv7_57))) or (not((trunc_ln26_fu_527_p1 = ap_const_lv7_7)) and not((trunc_ln26_fu_527_p1 = ap_const_lv7_27)) and (or_ln36_fu_543_p2 = ap_const_lv1_0))) or ((grp_fu_481_p2 = ap_const_lv1_0) and (trunc_ln26_fu_527_p1 = ap_const_lv7_27))) or ((grp_fu_467_p2 = ap_const_lv1_0) and (trunc_ln26_fu_527_p1 = ap_const_lv7_27))) or ((grp_fu_453_p2 = ap_const_lv1_0) and (trunc_ln26_fu_527_p1 = ap_const_lv7_27))) or ((grp_fu_481_p2 = ap_const_lv1_0) and (trunc_ln26_fu_527_p1 = ap_const_lv7_7))) or ((grp_fu_467_p2 = ap_const_lv1_0) and (trunc_ln26_fu_527_p1 = ap_const_lv7_7))) or ((grp_fu_453_p2 = ap_const_lv1_0) and (trunc_ln26_fu_527_p1 = ap_const_lv7_7))))) then
                    ap_NS_fsm <= ap_ST_fsm_state31;
                elsif (((grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_ap_done = ap_const_logic_1) and (grp_fu_481_p2 = ap_const_lv1_1) and (grp_fu_467_p2 = ap_const_lv1_1) and (grp_fu_453_p2 = ap_const_lv1_1) and (trunc_ln26_fu_527_p1 = ap_const_lv7_7) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state19;
                elsif (((grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_ap_done = ap_const_logic_1) and (grp_fu_481_p2 = ap_const_lv1_1) and (grp_fu_467_p2 = ap_const_lv1_1) and (grp_fu_453_p2 = ap_const_lv1_1) and (trunc_ln26_fu_527_p1 = ap_const_lv7_27) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                elsif (((grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_ap_done = ap_const_logic_1) and (or_ln89_1_fu_599_p2 = ap_const_lv1_0) and (or_ln36_fu_543_p2 = ap_const_lv1_1) and (trunc_ln26_fu_527_p1 = ap_const_lv7_57) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                elsif (((grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_ap_done = ap_const_logic_1) and (or_ln89_1_fu_599_p2 = ap_const_lv1_1) and (or_ln36_fu_543_p2 = ap_const_lv1_1) and (trunc_ln26_fu_527_p1 = ap_const_lv7_57) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state31;
            when ap_ST_fsm_state8 => 
                if (((gmem_0_AWREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                if (((gmem_0_WREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                    ap_NS_fsm <= ap_ST_fsm_state11;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when ap_ST_fsm_state11 => 
                if (((gmem_0_WREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then
                    ap_NS_fsm <= ap_ST_fsm_state12;
                else
                    ap_NS_fsm <= ap_ST_fsm_state11;
                end if;
            when ap_ST_fsm_state12 => 
                if (((gmem_0_WREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state12))) then
                    ap_NS_fsm <= ap_ST_fsm_state13;
                else
                    ap_NS_fsm <= ap_ST_fsm_state12;
                end if;
            when ap_ST_fsm_state13 => 
                if (((gmem_0_WREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then
                    ap_NS_fsm <= ap_ST_fsm_state14;
                else
                    ap_NS_fsm <= ap_ST_fsm_state13;
                end if;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                if (((gmem_0_BVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state18))) then
                    ap_NS_fsm <= ap_ST_fsm_state31;
                else
                    ap_NS_fsm <= ap_ST_fsm_state18;
                end if;
            when ap_ST_fsm_state19 => 
                if (((gmem_0_ARREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state19))) then
                    ap_NS_fsm <= ap_ST_fsm_state20;
                else
                    ap_NS_fsm <= ap_ST_fsm_state19;
                end if;
            when ap_ST_fsm_state20 => 
                ap_NS_fsm <= ap_ST_fsm_state21;
            when ap_ST_fsm_state21 => 
                ap_NS_fsm <= ap_ST_fsm_state22;
            when ap_ST_fsm_state22 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state23 => 
                ap_NS_fsm <= ap_ST_fsm_state24;
            when ap_ST_fsm_state24 => 
                ap_NS_fsm <= ap_ST_fsm_state25;
            when ap_ST_fsm_state25 => 
                ap_NS_fsm <= ap_ST_fsm_state26;
            when ap_ST_fsm_state26 => 
                ap_NS_fsm <= ap_ST_fsm_state27;
            when ap_ST_fsm_state27 => 
                if (((gmem_0_RVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state27))) then
                    ap_NS_fsm <= ap_ST_fsm_state28;
                else
                    ap_NS_fsm <= ap_ST_fsm_state27;
                end if;
            when ap_ST_fsm_state28 => 
                if (((gmem_0_RVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state28))) then
                    ap_NS_fsm <= ap_ST_fsm_state29;
                else
                    ap_NS_fsm <= ap_ST_fsm_state28;
                end if;
            when ap_ST_fsm_state29 => 
                if (((gmem_0_RVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state29))) then
                    ap_NS_fsm <= ap_ST_fsm_state30;
                else
                    ap_NS_fsm <= ap_ST_fsm_state29;
                end if;
            when ap_ST_fsm_state30 => 
                if (((gmem_0_RVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state30))) then
                    ap_NS_fsm <= ap_ST_fsm_state31;
                else
                    ap_NS_fsm <= ap_ST_fsm_state30;
                end if;
            when ap_ST_fsm_state31 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    add_ln69_fu_675_p2 <= std_logic_vector(unsigned(zext_ln69_1_fu_671_p1) + unsigned(mem));
    add_ln79_fu_637_p2 <= std_logic_vector(unsigned(zext_ln79_1_fu_633_p1) + unsigned(mem));
    and_ln1_fu_625_p3 <= (grp_fu_487_p4 & ap_const_lv2_0);
    and_ln_fu_663_p3 <= (grp_fu_487_p4 & ap_const_lv2_0);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state18 <= ap_CS_fsm(17);
    ap_CS_fsm_state19 <= ap_CS_fsm(18);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state27 <= ap_CS_fsm(26);
    ap_CS_fsm_state28 <= ap_CS_fsm(27);
    ap_CS_fsm_state29 <= ap_CS_fsm(28);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state30 <= ap_CS_fsm(29);
    ap_CS_fsm_state31 <= ap_CS_fsm(30);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_ST_fsm_state10_blk_assign_proc : process(gmem_0_WREADY)
    begin
        if ((gmem_0_WREADY = ap_const_logic_0)) then 
            ap_ST_fsm_state10_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state10_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state11_blk_assign_proc : process(gmem_0_WREADY)
    begin
        if ((gmem_0_WREADY = ap_const_logic_0)) then 
            ap_ST_fsm_state11_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state11_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state12_blk_assign_proc : process(gmem_0_WREADY)
    begin
        if ((gmem_0_WREADY = ap_const_logic_0)) then 
            ap_ST_fsm_state12_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state12_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state13_blk_assign_proc : process(gmem_0_WREADY)
    begin
        if ((gmem_0_WREADY = ap_const_logic_0)) then 
            ap_ST_fsm_state13_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state13_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state14_blk <= ap_const_logic_0;
    ap_ST_fsm_state15_blk <= ap_const_logic_0;
    ap_ST_fsm_state16_blk <= ap_const_logic_0;
    ap_ST_fsm_state17_blk <= ap_const_logic_0;

    ap_ST_fsm_state18_blk_assign_proc : process(gmem_0_BVALID)
    begin
        if ((gmem_0_BVALID = ap_const_logic_0)) then 
            ap_ST_fsm_state18_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state18_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state19_blk_assign_proc : process(gmem_0_ARREADY)
    begin
        if ((gmem_0_ARREADY = ap_const_logic_0)) then 
            ap_ST_fsm_state19_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state19_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state20_blk <= ap_const_logic_0;
    ap_ST_fsm_state21_blk <= ap_const_logic_0;
    ap_ST_fsm_state22_blk <= ap_const_logic_0;
    ap_ST_fsm_state23_blk <= ap_const_logic_0;
    ap_ST_fsm_state24_blk <= ap_const_logic_0;
    ap_ST_fsm_state25_blk <= ap_const_logic_0;
    ap_ST_fsm_state26_blk <= ap_const_logic_0;

    ap_ST_fsm_state27_blk_assign_proc : process(gmem_0_RVALID)
    begin
        if ((gmem_0_RVALID = ap_const_logic_0)) then 
            ap_ST_fsm_state27_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state27_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state28_blk_assign_proc : process(gmem_0_RVALID)
    begin
        if ((gmem_0_RVALID = ap_const_logic_0)) then 
            ap_ST_fsm_state28_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state28_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state29_blk_assign_proc : process(gmem_0_RVALID)
    begin
        if ((gmem_0_RVALID = ap_const_logic_0)) then 
            ap_ST_fsm_state29_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state29_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_ap_done)
    begin
        if ((grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state30_blk_assign_proc : process(gmem_0_RVALID)
    begin
        if ((gmem_0_RVALID = ap_const_logic_0)) then 
            ap_ST_fsm_state30_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state30_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state31_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_ST_fsm_state8_blk_assign_proc : process(gmem_0_AWREADY)
    begin
        if ((gmem_0_AWREADY = ap_const_logic_0)) then 
            ap_ST_fsm_state8_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state8_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_CS_fsm_state31)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state31)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_halted_local_2_phi_fu_406_p8_assign_proc : process(trunc_ln26_reg_1013, icmp_ln62_reg_1074, icmp_ln63_reg_1078, icmp_ln63_1_reg_1082, halted_local_2_reg_401, ap_CS_fsm_state31)
    begin
        if (((icmp_ln63_1_reg_1082 = ap_const_lv1_1) and (icmp_ln63_reg_1078 = ap_const_lv1_1) and (icmp_ln62_reg_1074 = ap_const_lv1_1) and (trunc_ln26_reg_1013 = ap_const_lv7_7) and (ap_const_logic_1 = ap_CS_fsm_state31))) then 
            ap_phi_mux_halted_local_2_phi_fu_406_p8 <= ap_const_lv1_0;
        else 
            ap_phi_mux_halted_local_2_phi_fu_406_p8 <= halted_local_2_reg_401;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state31)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state31)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    gmem_0_ARLEN <= ap_const_lv64_4(32 - 1 downto 0);

    gmem_0_ARVALID_assign_proc : process(ap_CS_fsm_state19, gmem_0_ARREADY)
    begin
        if (((gmem_0_ARREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state19))) then 
            gmem_0_ARVALID <= ap_const_logic_1;
        else 
            gmem_0_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    gmem_0_AWLEN <= ap_const_lv64_4(32 - 1 downto 0);

    gmem_0_AWVALID_assign_proc : process(ap_CS_fsm_state8, gmem_0_AWREADY)
    begin
        if (((gmem_0_AWREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            gmem_0_AWVALID <= ap_const_logic_1;
        else 
            gmem_0_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    gmem_0_BREADY_assign_proc : process(ap_CS_fsm_state18, gmem_0_BVALID)
    begin
        if (((gmem_0_BVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state18))) then 
            gmem_0_BREADY <= ap_const_logic_1;
        else 
            gmem_0_BREADY <= ap_const_logic_0;
        end if; 
    end process;


    gmem_0_RREADY_assign_proc : process(ap_CS_fsm_state27, ap_CS_fsm_state28, ap_CS_fsm_state29, ap_CS_fsm_state30, gmem_0_RVALID)
    begin
        if ((((gmem_0_RVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state30)) or ((gmem_0_RVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state29)) or ((gmem_0_RVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state28)) or ((gmem_0_RVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state27)))) then 
            gmem_0_RREADY <= ap_const_logic_1;
        else 
            gmem_0_RREADY <= ap_const_logic_0;
        end if; 
    end process;


    gmem_0_WVALID_assign_proc : process(ap_CS_fsm_state10, ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state13, gmem_0_WREADY)
    begin
        if ((((gmem_0_WREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13)) or ((gmem_0_WREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state12)) or ((gmem_0_WREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11)) or ((gmem_0_WREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10)))) then 
            gmem_0_WVALID <= ap_const_logic_1;
        else 
            gmem_0_WVALID <= ap_const_logic_0;
        end if; 
    end process;


    gmem_blk_n_AR_assign_proc : process(m_axi_gmem_ARREADY, ap_CS_fsm_state19)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            gmem_blk_n_AR <= m_axi_gmem_ARREADY;
        else 
            gmem_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    gmem_blk_n_AW_assign_proc : process(m_axi_gmem_AWREADY, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            gmem_blk_n_AW <= m_axi_gmem_AWREADY;
        else 
            gmem_blk_n_AW <= ap_const_logic_1;
        end if; 
    end process;


    gmem_blk_n_B_assign_proc : process(m_axi_gmem_BVALID, ap_CS_fsm_state18)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            gmem_blk_n_B <= m_axi_gmem_BVALID;
        else 
            gmem_blk_n_B <= ap_const_logic_1;
        end if; 
    end process;


    gmem_blk_n_R_assign_proc : process(m_axi_gmem_RVALID, ap_CS_fsm_state27, ap_CS_fsm_state28, ap_CS_fsm_state29, ap_CS_fsm_state30)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state30) or (ap_const_logic_1 = ap_CS_fsm_state29) or (ap_const_logic_1 = ap_CS_fsm_state28) or (ap_const_logic_1 = ap_CS_fsm_state27))) then 
            gmem_blk_n_R <= m_axi_gmem_RVALID;
        else 
            gmem_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;


    gmem_blk_n_W_assign_proc : process(m_axi_gmem_WREADY, ap_CS_fsm_state10, ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            gmem_blk_n_W <= m_axi_gmem_WREADY;
        else 
            gmem_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;

    grp_fu_435_p3 <= instr(14 downto 12);
    grp_fu_453_p2 <= "1" when (grp_fu_435_p3 = ap_const_lv3_6) else "0";
    grp_fu_459_p3 <= instr(27 downto 26);
    grp_fu_467_p2 <= "1" when (grp_fu_459_p3 = ap_const_lv2_0) else "0";
    grp_fu_473_p3 <= instr(24 downto 20);
    grp_fu_481_p2 <= "1" when (grp_fu_473_p3 = ap_const_lv5_0) else "0";
    grp_fu_487_p4 <= rs1_val(31 downto 2);
    grp_fu_497_p0 <= vregs_in_Dout_A;
    grp_fu_497_p1 <= vregs_in_Dout_B;
    grp_fu_497_p2 <= std_logic_vector(signed(grp_fu_497_p0) + signed(grp_fu_497_p1));
    grp_fu_503_p0 <= vregs_in_Dout_B;
    grp_fu_503_p1 <= vregs_in_Dout_A;
    grp_fu_503_p2 <= std_logic_vector(signed(grp_fu_503_p0) - signed(grp_fu_503_p1));
    grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_ap_start <= grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_ap_start_reg;
    halted <= ap_phi_mux_halted_local_2_phi_fu_406_p8;
    icmp_ln36_fu_537_p2 <= "1" when (grp_fu_435_p3 = ap_const_lv3_2) else "0";
    icmp_ln84_fu_531_p2 <= "1" when (grp_fu_435_p3 = ap_const_lv3_0) else "0";
    icmp_ln86_fu_557_p2 <= "1" when (tmp_9_fu_549_p3 = ap_const_lv6_0) else "0";
    icmp_ln87_fu_569_p2 <= "1" when (tmp_9_fu_549_p3 = ap_const_lv6_2) else "0";
    icmp_ln88_fu_581_p2 <= "1" when (tmp_9_fu_549_p3 = ap_const_lv6_25) else "0";
    is_add_fu_563_p2 <= (icmp_ln86_fu_557_p2 and icmp_ln84_fu_531_p2);
    is_mul_fu_587_p2 <= (icmp_ln88_fu_581_p2 and icmp_ln36_fu_537_p2);
    is_sub_fu_575_p2 <= (icmp_ln87_fu_569_p2 and icmp_ln84_fu_531_p2);
    mul1_fu_701_p3 <= (tmp_7_reg_1040 & ap_const_lv2_0);
    mul2_fu_708_p3 <= (tmp_8_reg_1048 & ap_const_lv2_0);
    mul3_fu_725_p3 <= (reg_509 & ap_const_lv2_0);
    mul4_fu_909_p3 <= (reg_509 & ap_const_lv2_0);
    mul_fu_961_p3 <= (reg_509 & ap_const_lv2_0);
    or_ln1_fu_750_p3 <= (tmp_8_reg_1048 & ap_const_lv2_1);
    or_ln2_fu_777_p3 <= (reg_509 & ap_const_lv2_1);
    or_ln36_fu_543_p2 <= (icmp_ln84_fu_531_p2 or icmp_ln36_fu_537_p2);
    or_ln3_fu_974_p3 <= (reg_509 & ap_const_lv2_1);
    or_ln4_fu_922_p3 <= (reg_509 & ap_const_lv2_1);
    or_ln69_1_fu_987_p3 <= (reg_509 & ap_const_lv2_2);
    or_ln69_2_fu_1000_p3 <= (reg_509 & ap_const_lv2_3);
    or_ln79_1_fu_935_p3 <= (reg_509 & ap_const_lv2_2);
    or_ln79_2_fu_948_p3 <= (reg_509 & ap_const_lv2_3);
    or_ln89_1_fu_599_p2 <= (or_ln89_fu_593_p2 or is_add_fu_563_p2);
    or_ln89_fu_593_p2 <= (is_sub_fu_575_p2 or is_mul_fu_587_p2);
    or_ln92_1_fu_790_p3 <= (tmp_7_reg_1040 & ap_const_lv2_2);
    or_ln92_2_fu_842_p3 <= (tmp_7_reg_1040 & ap_const_lv2_3);
    or_ln93_1_fu_802_p3 <= (tmp_8_reg_1048 & ap_const_lv2_2);
    or_ln93_2_fu_854_p3 <= (tmp_8_reg_1048 & ap_const_lv2_3);
    or_ln98_1_fu_829_p3 <= (reg_509 & ap_const_lv2_2);
    or_ln98_2_fu_896_p3 <= (reg_509 & ap_const_lv2_3);
    or_ln_fu_738_p3 <= (tmp_7_reg_1040 & ap_const_lv2_1);
    r_1121420_fu_769_p3 <= 
        grp_fu_497_p2 when (is_add_reg_1020(0) = '1') else 
        r_5_fu_762_p3;
    r_1_11618_fu_821_p3 <= 
        grp_fu_497_p2 when (is_add_reg_1020(0) = '1') else 
        r_6_fu_814_p3;
    r_1_222_fu_873_p3 <= 
        grp_fu_497_p2 when (is_add_reg_1020(0) = '1') else 
        r_7_fu_866_p3;
    r_3_fu_888_p3 <= 
        grp_fu_497_p2 when (is_add_reg_1020(0) = '1') else 
        r_fu_881_p3;
    r_5_fu_762_p3 <= 
        grp_fu_503_p2 when (is_sub_reg_1028(0) = '1') else 
        grp_fu_429_p2;
    r_6_fu_814_p3 <= 
        grp_fu_503_p2 when (is_sub_reg_1028(0) = '1') else 
        grp_fu_429_p2;
    r_7_fu_866_p3 <= 
        grp_fu_503_p2 when (is_sub_reg_1028(0) = '1') else 
        grp_fu_429_p2;
    r_fu_881_p3 <= 
        grp_fu_503_p2 when (is_sub_reg_1028(0) = '1') else 
        grp_fu_429_p2;
        sext_ln69_fu_691_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_fu_681_p4),64));

        sext_ln81_fu_653_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1_fu_643_p4),64));

    tmp_9_fu_549_p3 <= instr(31 downto 26);
    trunc_ln1_fu_643_p4 <= add_ln79_fu_637_p2(63 downto 2);
    trunc_ln26_fu_527_p1 <= instr(7 - 1 downto 0);
    trunc_ln_fu_681_p4 <= add_ln69_fu_675_p2(63 downto 2);

    vregs_in_Addr_A_assign_proc : process(ap_CS_fsm_state2, grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_vregs_in_Addr_A, vregs_in_Addr_A_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            vregs_in_Addr_A <= grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_vregs_in_Addr_A;
        else 
            vregs_in_Addr_A <= vregs_in_Addr_A_local;
        end if; 
    end process;

    vregs_in_Addr_A_local <= std_logic_vector(shift_left(unsigned(vregs_in_Addr_A_orig),to_integer(unsigned('0' & ap_const_lv32_2(31-1 downto 0)))));

    vregs_in_Addr_A_orig_assign_proc : process(ap_CS_fsm_state8, ap_CS_fsm_state10, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, zext_ln93_fu_720_p1, zext_ln93_1_fu_757_p1, zext_ln93_2_fu_809_p1, zext_ln93_3_fu_861_p1, zext_ln79_fu_917_p1, zext_ln79_3_fu_943_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            vregs_in_Addr_A_orig <= zext_ln79_3_fu_943_p1(32 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            vregs_in_Addr_A_orig <= zext_ln79_fu_917_p1(32 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            vregs_in_Addr_A_orig <= zext_ln93_3_fu_861_p1(32 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            vregs_in_Addr_A_orig <= zext_ln93_2_fu_809_p1(32 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            vregs_in_Addr_A_orig <= zext_ln93_1_fu_757_p1(32 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            vregs_in_Addr_A_orig <= zext_ln93_fu_720_p1(32 - 1 downto 0);
        else 
            vregs_in_Addr_A_orig <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    vregs_in_Addr_B <= vregs_in_Addr_B_local;
    vregs_in_Addr_B_local <= std_logic_vector(shift_left(unsigned(vregs_in_Addr_B_orig),to_integer(unsigned('0' & ap_const_lv32_2(31-1 downto 0)))));

    vregs_in_Addr_B_orig_assign_proc : process(ap_CS_fsm_state11, ap_CS_fsm_state9, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, zext_ln92_fu_715_p1, zext_ln92_1_fu_745_p1, zext_ln92_2_fu_797_p1, zext_ln92_3_fu_849_p1, zext_ln79_2_fu_930_p1, zext_ln79_4_fu_956_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            vregs_in_Addr_B_orig <= zext_ln79_4_fu_956_p1(32 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            vregs_in_Addr_B_orig <= zext_ln79_2_fu_930_p1(32 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            vregs_in_Addr_B_orig <= zext_ln92_3_fu_849_p1(32 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            vregs_in_Addr_B_orig <= zext_ln92_2_fu_797_p1(32 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            vregs_in_Addr_B_orig <= zext_ln92_1_fu_745_p1(32 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            vregs_in_Addr_B_orig <= zext_ln92_fu_715_p1(32 - 1 downto 0);
        else 
            vregs_in_Addr_B_orig <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    vregs_in_Clk_A <= ap_clk;
    vregs_in_Clk_B <= ap_clk;
    vregs_in_Din_A <= ap_const_lv32_0;
    vregs_in_Din_B <= ap_const_lv32_0;

    vregs_in_EN_A_assign_proc : process(ap_CS_fsm_state2, grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_vregs_in_EN_A, vregs_in_EN_A_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            vregs_in_EN_A <= grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_vregs_in_EN_A;
        else 
            vregs_in_EN_A <= vregs_in_EN_A_local;
        end if; 
    end process;


    vregs_in_EN_A_local_assign_proc : process(ap_CS_fsm_state8, ap_CS_fsm_state10, gmem_0_AWREADY, gmem_0_WREADY, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or ((gmem_0_AWREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8)) or ((gmem_0_WREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10)))) then 
            vregs_in_EN_A_local <= ap_const_logic_1;
        else 
            vregs_in_EN_A_local <= ap_const_logic_0;
        end if; 
    end process;

    vregs_in_EN_B <= vregs_in_EN_B_local;

    vregs_in_EN_B_local_assign_proc : process(ap_CS_fsm_state11, ap_CS_fsm_state9, gmem_0_WREADY, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state9) or ((gmem_0_WREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11)))) then 
            vregs_in_EN_B_local <= ap_const_logic_1;
        else 
            vregs_in_EN_B_local <= ap_const_logic_0;
        end if; 
    end process;

    vregs_in_Rst_A <= ap_rst_n_inv;
    vregs_in_Rst_B <= ap_rst_n_inv;
    vregs_in_WEN_A <= ap_const_lv4_0;
    vregs_in_WEN_B <= ap_const_lv4_0;

    vregs_out_Addr_A_assign_proc : process(ap_CS_fsm_state2, grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_vregs_out_Addr_A, vregs_out_Addr_A_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            vregs_out_Addr_A <= grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_vregs_out_Addr_A;
        else 
            vregs_out_Addr_A <= vregs_out_Addr_A_local;
        end if; 
    end process;

    vregs_out_Addr_A_local <= std_logic_vector(shift_left(unsigned(vregs_out_Addr_A_orig),to_integer(unsigned('0' & ap_const_lv32_2(31-1 downto 0)))));

    vregs_out_Addr_A_orig_assign_proc : process(ap_CS_fsm_state28, ap_CS_fsm_state29, ap_CS_fsm_state30, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state31, ap_CS_fsm_state7, zext_ln98_fu_733_p1, zext_ln98_1_fu_785_p1, zext_ln98_2_fu_837_p1, zext_ln98_3_fu_904_p1, zext_ln69_fu_969_p1, zext_ln69_2_fu_982_p1, zext_ln69_3_fu_995_p1, zext_ln69_4_fu_1008_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state31)) then 
            vregs_out_Addr_A_orig <= zext_ln69_4_fu_1008_p1(32 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state30)) then 
            vregs_out_Addr_A_orig <= zext_ln69_3_fu_995_p1(32 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state29)) then 
            vregs_out_Addr_A_orig <= zext_ln69_2_fu_982_p1(32 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state28)) then 
            vregs_out_Addr_A_orig <= zext_ln69_fu_969_p1(32 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            vregs_out_Addr_A_orig <= zext_ln98_3_fu_904_p1(32 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            vregs_out_Addr_A_orig <= zext_ln98_2_fu_837_p1(32 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            vregs_out_Addr_A_orig <= zext_ln98_1_fu_785_p1(32 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            vregs_out_Addr_A_orig <= zext_ln98_fu_733_p1(32 - 1 downto 0);
        else 
            vregs_out_Addr_A_orig <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    vregs_out_Clk_A <= ap_clk;

    vregs_out_Din_A_assign_proc : process(ap_CS_fsm_state2, grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_vregs_out_Din_A, vregs_out_Din_A_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            vregs_out_Din_A <= grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_vregs_out_Din_A;
        else 
            vregs_out_Din_A <= vregs_out_Din_A_local;
        end if; 
    end process;


    vregs_out_Din_A_local_assign_proc : process(ap_CS_fsm_state28, ap_CS_fsm_state29, ap_CS_fsm_state30, reg_522, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state31, ap_CS_fsm_state7, r_1121420_fu_769_p3, r_1_11618_fu_821_p3, r_1_222_fu_873_p3, r_3_fu_888_p3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state31) or (ap_const_logic_1 = ap_CS_fsm_state30) or (ap_const_logic_1 = ap_CS_fsm_state29) or (ap_const_logic_1 = ap_CS_fsm_state28))) then 
            vregs_out_Din_A_local <= reg_522;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            vregs_out_Din_A_local <= r_3_fu_888_p3;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            vregs_out_Din_A_local <= r_1_222_fu_873_p3;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            vregs_out_Din_A_local <= r_1_11618_fu_821_p3;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            vregs_out_Din_A_local <= r_1121420_fu_769_p3;
        else 
            vregs_out_Din_A_local <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    vregs_out_EN_A_assign_proc : process(ap_CS_fsm_state2, grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_vregs_out_EN_A, vregs_out_EN_A_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            vregs_out_EN_A <= grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_vregs_out_EN_A;
        else 
            vregs_out_EN_A <= vregs_out_EN_A_local;
        end if; 
    end process;


    vregs_out_EN_A_local_assign_proc : process(ap_CS_fsm_state28, ap_CS_fsm_state29, ap_CS_fsm_state30, gmem_0_RVALID, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state31, ap_CS_fsm_state7)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state31) or (ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or ((gmem_0_RVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state30)) or ((gmem_0_RVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state29)) or ((gmem_0_RVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state28)))) then 
            vregs_out_EN_A_local <= ap_const_logic_1;
        else 
            vregs_out_EN_A_local <= ap_const_logic_0;
        end if; 
    end process;

    vregs_out_Rst_A <= ap_rst_n_inv;

    vregs_out_WEN_A_assign_proc : process(ap_CS_fsm_state2, grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_vregs_out_WEN_A, vregs_out_WEN_A_out)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            vregs_out_WEN_A <= grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_vregs_out_WEN_A;
        else 
            vregs_out_WEN_A <= (vregs_out_WEN_A_out or ap_const_lv4_0);
        end if; 
    end process;


    vregs_out_WEN_A_local_assign_proc : process(ap_CS_fsm_state28, ap_CS_fsm_state29, ap_CS_fsm_state30, gmem_0_RVALID, trunc_ln26_reg_1013, or_ln89_1_reg_1036, icmp_ln62_reg_1074, icmp_ln63_reg_1078, icmp_ln63_1_reg_1082, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state31, ap_CS_fsm_state7)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or ((or_ln89_1_reg_1036 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7)) or ((icmp_ln63_1_reg_1082 = ap_const_lv1_1) and (icmp_ln63_reg_1078 = ap_const_lv1_1) and (icmp_ln62_reg_1074 = ap_const_lv1_1) and (trunc_ln26_reg_1013 = ap_const_lv7_7) and (ap_const_logic_1 = ap_CS_fsm_state31)) or ((gmem_0_RVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state30)) or ((gmem_0_RVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state29)) or ((gmem_0_RVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state28)))) then 
            vregs_out_WEN_A_local <= ap_const_lv4_F;
        else 
            vregs_out_WEN_A_local <= ap_const_lv4_0;
        end if; 
    end process;

    vregs_out_WEN_A_out <= vregs_out_WEN_A_local;
    zext_ln69_1_fu_671_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln_fu_663_p3),64));
    zext_ln69_2_fu_982_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln3_fu_974_p3),64));
    zext_ln69_3_fu_995_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln69_1_fu_987_p3),64));
    zext_ln69_4_fu_1008_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln69_2_fu_1000_p3),64));
    zext_ln69_fu_969_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_fu_961_p3),64));
    zext_ln79_1_fu_633_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln1_fu_625_p3),64));
    zext_ln79_2_fu_930_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln4_fu_922_p3),64));
    zext_ln79_3_fu_943_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln79_1_fu_935_p3),64));
    zext_ln79_4_fu_956_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln79_2_fu_948_p3),64));
    zext_ln79_fu_917_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul4_fu_909_p3),64));
    zext_ln92_1_fu_745_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln_fu_738_p3),64));
    zext_ln92_2_fu_797_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln92_1_fu_790_p3),64));
    zext_ln92_3_fu_849_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln92_2_fu_842_p3),64));
    zext_ln92_fu_715_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul1_fu_701_p3),64));
    zext_ln93_1_fu_757_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln1_fu_750_p3),64));
    zext_ln93_2_fu_809_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln93_1_fu_802_p3),64));
    zext_ln93_3_fu_861_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln93_2_fu_854_p3),64));
    zext_ln93_fu_720_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul2_fu_708_p3),64));
    zext_ln98_1_fu_785_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln2_fu_777_p3),64));
    zext_ln98_2_fu_837_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln98_1_fu_829_p3),64));
    zext_ln98_3_fu_904_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln98_2_fu_896_p3),64));
    zext_ln98_fu_733_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul3_fu_725_p3),64));
end behav;
