-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity rv32_ooo_tick_read_operand is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    reg_r : IN STD_LOGIC_VECTOR (4 downto 0);
    rat_has_tag_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    rat_has_tag_ce0 : OUT STD_LOGIC;
    rat_has_tag_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
    rat_tag_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    rat_tag_ce0 : OUT STD_LOGIC;
    rat_tag_q0 : IN STD_LOGIC_VECTOR (2 downto 0);
    rob_ready_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    rob_ready_ce0 : OUT STD_LOGIC;
    rob_ready_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
    regfile_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    regfile_ce0 : OUT STD_LOGIC;
    regfile_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    rob_value_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    rob_value_ce0 : OUT STD_LOGIC;
    rob_value_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (2 downto 0) );
end;


architecture behav of rv32_ooo_tick_read_operand is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal icmp_ln262_fu_109_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln262_reg_222 : STD_LOGIC_VECTOR (0 downto 0);
    signal rat_has_tag_load_reg_244 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal t_reg_251 : STD_LOGIC_VECTOR (2 downto 0);
    signal op_val_reg_261 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln266_fu_115_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln271_fu_122_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal rat_has_tag_ce0_local : STD_LOGIC;
    signal rat_tag_ce0_local : STD_LOGIC;
    signal regfile_ce0_local : STD_LOGIC;
    signal rob_ready_ce0_local : STD_LOGIC;
    signal rob_value_ce0_local : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal xor_ln266_fu_128_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln271_fu_133_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln266_fu_144_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln271_fu_154_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln271_fu_160_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln266_1_fu_148_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln271_2_fu_165_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal agg_result_val_fu_178_p7 : STD_LOGIC_VECTOR (31 downto 0);
    signal agg_result_val_fu_178_p8 : STD_LOGIC_VECTOR (1 downto 0);
    signal or_ln271_1_fu_138_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal agg_result_val_fu_178_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal agg_result_tag_0_fu_197_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_return_0_preg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal ap_return_1_preg : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_return_2_preg : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal agg_result_val_fu_178_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal agg_result_val_fu_178_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal agg_result_val_fu_178_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component rv32_ooo_tick_sparsemux_7_2_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        def : IN STD_LOGIC_VECTOR (31 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    sparsemux_7_2_32_1_1_U96 : component rv32_ooo_tick_sparsemux_7_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 32,
        CASE1 => "01",
        din1_WIDTH => 32,
        CASE2 => "00",
        din2_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => op_val_reg_261,
        din1 => ap_const_lv32_0,
        din2 => rob_value_q0,
        def => agg_result_val_fu_178_p7,
        sel => agg_result_val_fu_178_p8,
        dout => agg_result_val_fu_178_p9);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_return_0_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_0_preg <= ap_const_lv1_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    ap_return_0_preg <= or_ln271_1_fu_138_p2;
                end if; 
            end if;
        end if;
    end process;


    ap_return_1_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_1_preg <= ap_const_lv32_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    ap_return_1_preg <= agg_result_val_fu_178_p9;
                end if; 
            end if;
        end if;
    end process;


    ap_return_2_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_2_preg <= ap_const_lv3_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    ap_return_2_preg <= agg_result_tag_0_fu_197_p3;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                icmp_ln262_reg_222 <= icmp_ln262_fu_109_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                op_val_reg_261 <= regfile_q0;
                rat_has_tag_load_reg_244 <= rat_has_tag_q0;
                t_reg_251 <= rat_tag_q0;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    agg_result_tag_0_fu_197_p3 <= 
        ap_const_lv3_0 when (or_ln271_1_fu_138_p2(0) = '1') else 
        t_reg_251;
    agg_result_val_fu_178_p7 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    agg_result_val_fu_178_p8 <= (xor_ln266_1_fu_148_p2 & or_ln271_2_fu_165_p2);
    and_ln271_fu_160_p2 <= (xor_ln271_fu_154_p2 and rat_has_tag_load_reg_244);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_return_0_assign_proc : process(ap_CS_fsm_state3, or_ln271_1_fu_138_p2, ap_return_0_preg)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            ap_return_0 <= or_ln271_1_fu_138_p2;
        else 
            ap_return_0 <= ap_return_0_preg;
        end if; 
    end process;


    ap_return_1_assign_proc : process(ap_CS_fsm_state3, agg_result_val_fu_178_p9, ap_return_1_preg)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            ap_return_1 <= agg_result_val_fu_178_p9;
        else 
            ap_return_1 <= ap_return_1_preg;
        end if; 
    end process;


    ap_return_2_assign_proc : process(ap_CS_fsm_state3, agg_result_tag_0_fu_197_p3, ap_return_2_preg)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            ap_return_2 <= agg_result_tag_0_fu_197_p3;
        else 
            ap_return_2 <= ap_return_2_preg;
        end if; 
    end process;

    icmp_ln262_fu_109_p2 <= "1" when (reg_r = ap_const_lv5_0) else "0";
    or_ln266_fu_144_p2 <= (rat_has_tag_load_reg_244 or icmp_ln262_reg_222);
    or_ln271_1_fu_138_p2 <= (rob_ready_q0 or or_ln271_fu_133_p2);
    or_ln271_2_fu_165_p2 <= (icmp_ln262_reg_222 or and_ln271_fu_160_p2);
    or_ln271_fu_133_p2 <= (xor_ln266_fu_128_p2 or icmp_ln262_reg_222);
    rat_has_tag_address0 <= zext_ln266_fu_115_p1(5 - 1 downto 0);
    rat_has_tag_ce0 <= rat_has_tag_ce0_local;

    rat_has_tag_ce0_local_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rat_has_tag_ce0_local <= ap_const_logic_1;
        else 
            rat_has_tag_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    rat_tag_address0 <= zext_ln266_fu_115_p1(5 - 1 downto 0);
    rat_tag_ce0 <= rat_tag_ce0_local;

    rat_tag_ce0_local_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rat_tag_ce0_local <= ap_const_logic_1;
        else 
            rat_tag_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    regfile_address0 <= zext_ln266_fu_115_p1(5 - 1 downto 0);
    regfile_ce0 <= regfile_ce0_local;

    regfile_ce0_local_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            regfile_ce0_local <= ap_const_logic_1;
        else 
            regfile_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    rob_ready_address0 <= zext_ln271_fu_122_p1(3 - 1 downto 0);
    rob_ready_ce0 <= rob_ready_ce0_local;

    rob_ready_ce0_local_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            rob_ready_ce0_local <= ap_const_logic_1;
        else 
            rob_ready_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    rob_value_address0 <= zext_ln271_fu_122_p1(3 - 1 downto 0);
    rob_value_ce0 <= rob_value_ce0_local;

    rob_value_ce0_local_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            rob_value_ce0_local <= ap_const_logic_1;
        else 
            rob_value_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    xor_ln266_1_fu_148_p2 <= (or_ln266_fu_144_p2 xor ap_const_lv1_1);
    xor_ln266_fu_128_p2 <= (rat_has_tag_load_reg_244 xor ap_const_lv1_1);
    xor_ln271_fu_154_p2 <= (rob_ready_q0 xor ap_const_lv1_1);
    zext_ln266_fu_115_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reg_r),64));
    zext_ln271_fu_122_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(rat_tag_q0),64));
end behav;
