// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="rv32_vector_step_rv32_vector_step,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=139,HLS_SYN_TPT=none,HLS_SYN_MEM=4,HLS_SYN_DSP=0,HLS_SYN_FF=1232,HLS_SYN_LUT=1998,HLS_VERSION=2024_2}" *)

module rv32_vector_step (
        ap_clk,
        ap_rst_n,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        instr,
        rs1_val,
        vregs_in_Addr_A,
        vregs_in_EN_A,
        vregs_in_WEN_A,
        vregs_in_Din_A,
        vregs_in_Dout_A,
        vregs_in_Clk_A,
        vregs_in_Rst_A,
        vregs_in_Addr_B,
        vregs_in_EN_B,
        vregs_in_WEN_B,
        vregs_in_Din_B,
        vregs_in_Dout_B,
        vregs_in_Clk_B,
        vregs_in_Rst_B,
        vregs_out_Addr_A,
        vregs_out_EN_A,
        vregs_out_WEN_A,
        vregs_out_Din_A,
        vregs_out_Dout_A,
        vregs_out_Clk_A,
        vregs_out_Rst_A,
        halted,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt,
        s_axi_control_r_AWVALID,
        s_axi_control_r_AWREADY,
        s_axi_control_r_AWADDR,
        s_axi_control_r_WVALID,
        s_axi_control_r_WREADY,
        s_axi_control_r_WDATA,
        s_axi_control_r_WSTRB,
        s_axi_control_r_ARVALID,
        s_axi_control_r_ARREADY,
        s_axi_control_r_ARADDR,
        s_axi_control_r_RVALID,
        s_axi_control_r_RREADY,
        s_axi_control_r_RDATA,
        s_axi_control_r_RRESP,
        s_axi_control_r_BVALID,
        s_axi_control_r_BREADY,
        s_axi_control_r_BRESP
);

parameter    ap_ST_fsm_state1 = 31'd1;
parameter    ap_ST_fsm_state2 = 31'd2;
parameter    ap_ST_fsm_state3 = 31'd4;
parameter    ap_ST_fsm_state4 = 31'd8;
parameter    ap_ST_fsm_state5 = 31'd16;
parameter    ap_ST_fsm_state6 = 31'd32;
parameter    ap_ST_fsm_state7 = 31'd64;
parameter    ap_ST_fsm_state8 = 31'd128;
parameter    ap_ST_fsm_state9 = 31'd256;
parameter    ap_ST_fsm_state10 = 31'd512;
parameter    ap_ST_fsm_state11 = 31'd1024;
parameter    ap_ST_fsm_state12 = 31'd2048;
parameter    ap_ST_fsm_state13 = 31'd4096;
parameter    ap_ST_fsm_state14 = 31'd8192;
parameter    ap_ST_fsm_state15 = 31'd16384;
parameter    ap_ST_fsm_state16 = 31'd32768;
parameter    ap_ST_fsm_state17 = 31'd65536;
parameter    ap_ST_fsm_state18 = 31'd131072;
parameter    ap_ST_fsm_state19 = 31'd262144;
parameter    ap_ST_fsm_state20 = 31'd524288;
parameter    ap_ST_fsm_state21 = 31'd1048576;
parameter    ap_ST_fsm_state22 = 31'd2097152;
parameter    ap_ST_fsm_state23 = 31'd4194304;
parameter    ap_ST_fsm_state24 = 31'd8388608;
parameter    ap_ST_fsm_state25 = 31'd16777216;
parameter    ap_ST_fsm_state26 = 31'd33554432;
parameter    ap_ST_fsm_state27 = 31'd67108864;
parameter    ap_ST_fsm_state28 = 31'd134217728;
parameter    ap_ST_fsm_state29 = 31'd268435456;
parameter    ap_ST_fsm_state30 = 31'd536870912;
parameter    ap_ST_fsm_state31 = 31'd1073741824;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 4;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_R_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_R_ADDR_WIDTH = 5;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_CONTROL_R_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1:0] m_axi_gmem_BUSER;
input  [31:0] instr;
input  [31:0] rs1_val;
output  [31:0] vregs_in_Addr_A;
output   vregs_in_EN_A;
output  [3:0] vregs_in_WEN_A;
output  [31:0] vregs_in_Din_A;
input  [31:0] vregs_in_Dout_A;
output   vregs_in_Clk_A;
output   vregs_in_Rst_A;
output  [31:0] vregs_in_Addr_B;
output   vregs_in_EN_B;
output  [3:0] vregs_in_WEN_B;
output  [31:0] vregs_in_Din_B;
input  [31:0] vregs_in_Dout_B;
output   vregs_in_Clk_B;
output   vregs_in_Rst_B;
output  [31:0] vregs_out_Addr_A;
output   vregs_out_EN_A;
output  [3:0] vregs_out_WEN_A;
output  [31:0] vregs_out_Din_A;
input  [31:0] vregs_out_Dout_A;
output   vregs_out_Clk_A;
output   vregs_out_Rst_A;
output  [0:0] halted;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;
input   s_axi_control_r_AWVALID;
output   s_axi_control_r_AWREADY;
input  [C_S_AXI_CONTROL_R_ADDR_WIDTH - 1:0] s_axi_control_r_AWADDR;
input   s_axi_control_r_WVALID;
output   s_axi_control_r_WREADY;
input  [C_S_AXI_CONTROL_R_DATA_WIDTH - 1:0] s_axi_control_r_WDATA;
input  [C_S_AXI_CONTROL_R_WSTRB_WIDTH - 1:0] s_axi_control_r_WSTRB;
input   s_axi_control_r_ARVALID;
output   s_axi_control_r_ARREADY;
input  [C_S_AXI_CONTROL_R_ADDR_WIDTH - 1:0] s_axi_control_r_ARADDR;
output   s_axi_control_r_RVALID;
input   s_axi_control_r_RREADY;
output  [C_S_AXI_CONTROL_R_DATA_WIDTH - 1:0] s_axi_control_r_RDATA;
output  [1:0] s_axi_control_r_RRESP;
output   s_axi_control_r_BVALID;
input   s_axi_control_r_BREADY;
output  [1:0] s_axi_control_r_BRESP;

reg[31:0] vregs_in_Addr_A;
reg vregs_in_EN_A;
reg[31:0] vregs_out_Addr_A;
reg vregs_out_EN_A;
reg[3:0] vregs_out_WEN_A;
reg[31:0] vregs_out_Din_A;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [30:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [63:0] mem;
reg    gmem_blk_n_AR;
wire    ap_CS_fsm_state19;
reg    gmem_blk_n_R;
wire    ap_CS_fsm_state27;
wire    ap_CS_fsm_state28;
wire    ap_CS_fsm_state29;
wire    ap_CS_fsm_state30;
reg    gmem_blk_n_AW;
wire    ap_CS_fsm_state8;
reg    gmem_blk_n_W;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
reg    gmem_blk_n_B;
wire    ap_CS_fsm_state18;
reg   [4:0] reg_509;
wire    ap_CS_fsm_state2;
wire   [6:0] trunc_ln26_fu_527_p1;
wire   [0:0] or_ln36_fu_543_p2;
wire   [0:0] or_ln89_1_fu_599_p2;
wire   [0:0] grp_fu_453_p2;
wire   [0:0] grp_fu_467_p2;
wire   [0:0] grp_fu_481_p2;
reg   [31:0] reg_513;
wire    ap_CS_fsm_state9;
reg    gmem_0_AWVALID;
wire    gmem_0_AWREADY;
wire   [31:0] gmem_0_AWLEN;
reg    gmem_0_WVALID;
wire    gmem_0_WREADY;
reg    gmem_0_ARVALID;
wire    gmem_0_ARREADY;
wire   [31:0] gmem_0_ARLEN;
wire    gmem_0_RVALID;
reg    gmem_0_RREADY;
wire   [31:0] gmem_0_RDATA;
wire   [8:0] gmem_0_RFIFONUM;
wire    gmem_0_BVALID;
reg    gmem_0_BREADY;
reg   [31:0] reg_522;
reg   [6:0] trunc_ln26_reg_1013;
wire   [0:0] is_add_fu_563_p2;
reg   [0:0] is_add_reg_1020;
wire   [0:0] is_sub_fu_575_p2;
reg   [0:0] is_sub_reg_1028;
reg   [0:0] or_ln89_1_reg_1036;
reg   [4:0] tmp_7_reg_1040;
reg   [4:0] tmp_8_reg_1048;
reg   [63:0] gmem_addr_1_reg_1065;
reg   [0:0] icmp_ln62_reg_1074;
reg   [0:0] icmp_ln63_reg_1078;
reg   [0:0] icmp_ln63_1_reg_1082;
reg   [63:0] gmem_addr_reg_1086;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
wire    grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_ap_start;
wire    grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_ap_done;
wire    grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_ap_idle;
wire    grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_ap_ready;
wire   [31:0] grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_vregs_in_Addr_A;
wire    grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_vregs_in_EN_A;
wire   [3:0] grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_vregs_in_WEN_A;
wire   [31:0] grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_vregs_in_Din_A;
wire   [31:0] grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_vregs_out_Addr_A;
wire    grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_vregs_out_EN_A;
wire   [3:0] grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_vregs_out_WEN_A;
wire   [31:0] grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_vregs_out_Din_A;
reg   [0:0] ap_phi_mux_halted_local_2_phi_fu_406_p8;
reg   [0:0] halted_local_2_reg_401;
wire    ap_CS_fsm_state31;
wire    ap_CS_fsm_state7;
reg    grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_ap_start_reg;
wire   [3:0] vregs_out_WEN_A_out;
wire   [63:0] zext_ln92_fu_715_p1;
wire   [63:0] zext_ln93_fu_720_p1;
wire   [63:0] zext_ln92_1_fu_745_p1;
wire   [63:0] zext_ln93_1_fu_757_p1;
wire   [63:0] zext_ln98_fu_733_p1;
wire   [63:0] zext_ln92_2_fu_797_p1;
wire   [63:0] zext_ln93_2_fu_809_p1;
wire   [63:0] zext_ln98_1_fu_785_p1;
wire   [63:0] zext_ln92_3_fu_849_p1;
wire   [63:0] zext_ln93_3_fu_861_p1;
wire   [63:0] zext_ln98_2_fu_837_p1;
wire   [63:0] zext_ln98_3_fu_904_p1;
wire   [63:0] zext_ln79_fu_917_p1;
wire   [63:0] zext_ln79_2_fu_930_p1;
wire   [63:0] zext_ln79_3_fu_943_p1;
wire   [63:0] zext_ln79_4_fu_956_p1;
wire   [63:0] zext_ln69_fu_969_p1;
wire   [63:0] zext_ln69_2_fu_982_p1;
wire   [63:0] zext_ln69_3_fu_995_p1;
wire   [63:0] zext_ln69_4_fu_1008_p1;
wire  signed [63:0] sext_ln81_fu_653_p1;
wire  signed [63:0] sext_ln69_fu_691_p1;
reg    vregs_in_EN_B_local;
wire   [31:0] vregs_in_Addr_B_local;
reg   [31:0] vregs_in_Addr_B_orig;
reg    vregs_in_EN_A_local;
wire   [31:0] vregs_in_Addr_A_local;
reg   [31:0] vregs_in_Addr_A_orig;
reg   [3:0] vregs_out_WEN_A_local;
reg   [31:0] vregs_out_Din_A_local;
wire   [31:0] r_1121420_fu_769_p3;
reg    vregs_out_EN_A_local;
wire   [31:0] vregs_out_Addr_A_local;
reg   [31:0] vregs_out_Addr_A_orig;
wire   [31:0] r_1_11618_fu_821_p3;
wire   [31:0] r_1_222_fu_873_p3;
wire   [31:0] r_3_fu_888_p3;
wire   [2:0] grp_fu_435_p3;
wire   [1:0] grp_fu_459_p3;
wire   [4:0] grp_fu_473_p3;
wire  signed [31:0] grp_fu_497_p0;
wire  signed [31:0] grp_fu_497_p1;
wire  signed [31:0] grp_fu_503_p0;
wire  signed [31:0] grp_fu_503_p1;
wire   [0:0] icmp_ln84_fu_531_p2;
wire   [0:0] icmp_ln36_fu_537_p2;
wire   [5:0] tmp_9_fu_549_p3;
wire   [0:0] icmp_ln86_fu_557_p2;
wire   [0:0] icmp_ln87_fu_569_p2;
wire   [0:0] icmp_ln88_fu_581_p2;
wire   [0:0] is_mul_fu_587_p2;
wire   [0:0] or_ln89_fu_593_p2;
wire   [29:0] grp_fu_487_p4;
wire   [31:0] and_ln1_fu_625_p3;
wire   [63:0] zext_ln79_1_fu_633_p1;
wire   [63:0] add_ln79_fu_637_p2;
wire   [61:0] trunc_ln1_fu_643_p4;
wire   [31:0] and_ln_fu_663_p3;
wire   [63:0] zext_ln69_1_fu_671_p1;
wire   [63:0] add_ln69_fu_675_p2;
wire   [61:0] trunc_ln_fu_681_p4;
wire   [6:0] mul1_fu_701_p3;
wire   [6:0] mul2_fu_708_p3;
wire   [6:0] mul3_fu_725_p3;
wire   [6:0] or_ln_fu_738_p3;
wire   [6:0] or_ln1_fu_750_p3;
wire   [31:0] grp_fu_503_p2;
wire   [31:0] grp_fu_429_p2;
wire   [31:0] grp_fu_497_p2;
wire   [31:0] r_5_fu_762_p3;
wire   [6:0] or_ln2_fu_777_p3;
wire   [6:0] or_ln92_1_fu_790_p3;
wire   [6:0] or_ln93_1_fu_802_p3;
wire   [31:0] r_6_fu_814_p3;
wire   [6:0] or_ln98_1_fu_829_p3;
wire   [6:0] or_ln92_2_fu_842_p3;
wire   [6:0] or_ln93_2_fu_854_p3;
wire   [31:0] r_7_fu_866_p3;
wire   [31:0] r_fu_881_p3;
wire   [6:0] or_ln98_2_fu_896_p3;
wire   [6:0] mul4_fu_909_p3;
wire   [6:0] or_ln4_fu_922_p3;
wire   [6:0] or_ln79_1_fu_935_p3;
wire   [6:0] or_ln79_2_fu_948_p3;
wire   [6:0] mul_fu_961_p3;
wire   [6:0] or_ln3_fu_974_p3;
wire   [6:0] or_ln69_1_fu_987_p3;
wire   [6:0] or_ln69_2_fu_1000_p3;
reg   [30:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
reg    ap_ST_fsm_state18_blk;
reg    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
reg    ap_ST_fsm_state27_blk;
reg    ap_ST_fsm_state28_blk;
reg    ap_ST_fsm_state29_blk;
reg    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 31'd1;
#0 grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_ap_start_reg = 1'b0;
end

rv32_vector_step_rv32_vector_step_Pipeline_VITIS_LOOP_54_1 grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_ap_start),
    .ap_done(grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_ap_done),
    .ap_idle(grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_ap_idle),
    .ap_ready(grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_ap_ready),
    .vregs_in_Addr_A(grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_vregs_in_Addr_A),
    .vregs_in_EN_A(grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_vregs_in_EN_A),
    .vregs_in_WEN_A(grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_vregs_in_WEN_A),
    .vregs_in_Din_A(grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_vregs_in_Din_A),
    .vregs_in_Dout_A(vregs_in_Dout_A),
    .vregs_out_Addr_A(grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_vregs_out_Addr_A),
    .vregs_out_EN_A(grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_vregs_out_EN_A),
    .vregs_out_WEN_A(grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_vregs_out_WEN_A),
    .vregs_out_Din_A(grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_vregs_out_Din_A),
    .vregs_out_Dout_A(32'd0)
);

rv32_vector_step_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

rv32_vector_step_control_r_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_R_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_R_DATA_WIDTH ))
control_r_s_axi_U(
    .AWVALID(s_axi_control_r_AWVALID),
    .AWREADY(s_axi_control_r_AWREADY),
    .AWADDR(s_axi_control_r_AWADDR),
    .WVALID(s_axi_control_r_WVALID),
    .WREADY(s_axi_control_r_WREADY),
    .WDATA(s_axi_control_r_WDATA),
    .WSTRB(s_axi_control_r_WSTRB),
    .ARVALID(s_axi_control_r_ARVALID),
    .ARREADY(s_axi_control_r_ARREADY),
    .ARADDR(s_axi_control_r_ARADDR),
    .RVALID(s_axi_control_r_RVALID),
    .RREADY(s_axi_control_r_RREADY),
    .RDATA(s_axi_control_r_RDATA),
    .RRESP(s_axi_control_r_RRESP),
    .BVALID(s_axi_control_r_BVALID),
    .BREADY(s_axi_control_r_BREADY),
    .BRESP(s_axi_control_r_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .mem(mem)
);

rv32_vector_step_gmem_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 4 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 32 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem_m_axi_U(
    .AWVALID(m_axi_gmem_AWVALID),
    .AWREADY(m_axi_gmem_AWREADY),
    .AWADDR(m_axi_gmem_AWADDR),
    .AWID(m_axi_gmem_AWID),
    .AWLEN(m_axi_gmem_AWLEN),
    .AWSIZE(m_axi_gmem_AWSIZE),
    .AWBURST(m_axi_gmem_AWBURST),
    .AWLOCK(m_axi_gmem_AWLOCK),
    .AWCACHE(m_axi_gmem_AWCACHE),
    .AWPROT(m_axi_gmem_AWPROT),
    .AWQOS(m_axi_gmem_AWQOS),
    .AWREGION(m_axi_gmem_AWREGION),
    .AWUSER(m_axi_gmem_AWUSER),
    .WVALID(m_axi_gmem_WVALID),
    .WREADY(m_axi_gmem_WREADY),
    .WDATA(m_axi_gmem_WDATA),
    .WSTRB(m_axi_gmem_WSTRB),
    .WLAST(m_axi_gmem_WLAST),
    .WID(m_axi_gmem_WID),
    .WUSER(m_axi_gmem_WUSER),
    .ARVALID(m_axi_gmem_ARVALID),
    .ARREADY(m_axi_gmem_ARREADY),
    .ARADDR(m_axi_gmem_ARADDR),
    .ARID(m_axi_gmem_ARID),
    .ARLEN(m_axi_gmem_ARLEN),
    .ARSIZE(m_axi_gmem_ARSIZE),
    .ARBURST(m_axi_gmem_ARBURST),
    .ARLOCK(m_axi_gmem_ARLOCK),
    .ARCACHE(m_axi_gmem_ARCACHE),
    .ARPROT(m_axi_gmem_ARPROT),
    .ARQOS(m_axi_gmem_ARQOS),
    .ARREGION(m_axi_gmem_ARREGION),
    .ARUSER(m_axi_gmem_ARUSER),
    .RVALID(m_axi_gmem_RVALID),
    .RREADY(m_axi_gmem_RREADY),
    .RDATA(m_axi_gmem_RDATA),
    .RLAST(m_axi_gmem_RLAST),
    .RID(m_axi_gmem_RID),
    .RUSER(m_axi_gmem_RUSER),
    .RRESP(m_axi_gmem_RRESP),
    .BVALID(m_axi_gmem_BVALID),
    .BREADY(m_axi_gmem_BREADY),
    .BRESP(m_axi_gmem_BRESP),
    .BID(m_axi_gmem_BID),
    .BUSER(m_axi_gmem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(gmem_0_ARVALID),
    .I_CH0_ARREADY(gmem_0_ARREADY),
    .I_CH0_ARADDR(gmem_addr_reg_1086),
    .I_CH0_ARLEN(gmem_0_ARLEN),
    .I_CH0_RVALID(gmem_0_RVALID),
    .I_CH0_RREADY(gmem_0_RREADY),
    .I_CH0_RDATA(gmem_0_RDATA),
    .I_CH0_RFIFONUM(gmem_0_RFIFONUM),
    .I_CH0_AWVALID(gmem_0_AWVALID),
    .I_CH0_AWREADY(gmem_0_AWREADY),
    .I_CH0_AWADDR(gmem_addr_1_reg_1065),
    .I_CH0_AWLEN(gmem_0_AWLEN),
    .I_CH0_WVALID(gmem_0_WVALID),
    .I_CH0_WREADY(gmem_0_WREADY),
    .I_CH0_WDATA(reg_513),
    .I_CH0_WSTRB(4'd15),
    .I_CH0_BVALID(gmem_0_BVALID),
    .I_CH0_BREADY(gmem_0_BREADY)
);

rv32_vector_step_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U1(
    .din0(vregs_in_Dout_A),
    .din1(vregs_in_Dout_B),
    .dout(grp_fu_429_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_ap_start_reg <= 1'b1;
        end else if ((grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_ap_ready == 1'b1)) begin
            grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2) & ((((((((~(trunc_ln26_fu_527_p1 == 7'd7) & ~(trunc_ln26_fu_527_p1 == 7'd39) & ~(trunc_ln26_fu_527_p1 == 7'd87)) | (~(trunc_ln26_fu_527_p1 == 7'd7) & ~(trunc_ln26_fu_527_p1 == 7'd39) & (or_ln36_fu_543_p2 == 1'd0))) | ((grp_fu_481_p2 == 1'd0) & (trunc_ln26_fu_527_p1 == 7'd39))) | ((grp_fu_467_p2 == 1'd0) & (trunc_ln26_fu_527_p1 == 7'd39))) | ((grp_fu_453_p2 == 1'd0) & (trunc_ln26_fu_527_p1 == 7'd39))) | ((grp_fu_481_p2 == 1'd0) & (trunc_ln26_fu_527_p1 == 7'd7))) | ((grp_fu_467_p2 == 1'd0) & (trunc_ln26_fu_527_p1 == 7'd7))) | ((grp_fu_453_p2 == 1'd0) & (trunc_ln26_fu_527_p1 == 7'd7))))) begin
        halted_local_2_reg_401 <= 1'd1;
    end else if (((1'b1 == ap_CS_fsm_state7) | ((gmem_0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state18)) | ((icmp_ln63_1_reg_1082 == 1'd1) & (icmp_ln63_reg_1078 == 1'd1) & (icmp_ln62_reg_1074 == 1'd1) & (trunc_ln26_reg_1013 == 7'd7) & (1'b1 == ap_CS_fsm_state31)))) begin
        halted_local_2_reg_401 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((((gmem_0_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state12)) | ((gmem_0_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state10)))) begin
        reg_513 <= vregs_in_Dout_B;
    end else if (((1'b1 == ap_CS_fsm_state9) | ((gmem_0_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state11)))) begin
        reg_513 <= vregs_in_Dout_A;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        gmem_addr_1_reg_1065 <= sext_ln81_fu_653_p1;
        gmem_addr_reg_1086 <= sext_ln69_fu_691_p1;
        icmp_ln62_reg_1074 <= grp_fu_453_p2;
        icmp_ln63_1_reg_1082 <= grp_fu_481_p2;
        icmp_ln63_reg_1078 <= grp_fu_467_p2;
        is_add_reg_1020 <= is_add_fu_563_p2;
        is_sub_reg_1028 <= is_sub_fu_575_p2;
        or_ln89_1_reg_1036 <= or_ln89_1_fu_599_p2;
        tmp_7_reg_1040 <= {{instr[24:20]}};
        tmp_8_reg_1048 <= {{instr[19:15]}};
        trunc_ln26_reg_1013 <= trunc_ln26_fu_527_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((((grp_fu_481_p2 == 1'd1) & (grp_fu_467_p2 == 1'd1) & (grp_fu_453_p2 == 1'd1) & (trunc_ln26_fu_527_p1 == 7'd7) & (1'b1 == ap_CS_fsm_state2)) | ((grp_fu_481_p2 == 1'd1) & (grp_fu_467_p2 == 1'd1) & (grp_fu_453_p2 == 1'd1) & (trunc_ln26_fu_527_p1 == 7'd39) & (1'b1 == ap_CS_fsm_state2)) | ((or_ln89_1_fu_599_p2 == 1'd1) & (or_ln36_fu_543_p2 == 1'd1) & (trunc_ln26_fu_527_p1 == 7'd87) & (1'b1 == ap_CS_fsm_state2)))) begin
        reg_509 <= {{instr[11:7]}};
    end
end

always @ (posedge ap_clk) begin
    if ((((gmem_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state30)) | ((gmem_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state29)) | ((gmem_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state28)) | ((gmem_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state27)))) begin
        reg_522 <= gmem_0_RDATA;
    end
end

always @ (*) begin
    if ((gmem_0_WREADY == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem_0_WREADY == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem_0_WREADY == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem_0_WREADY == 1'b0)) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

always @ (*) begin
    if ((gmem_0_BVALID == 1'b0)) begin
        ap_ST_fsm_state18_blk = 1'b1;
    end else begin
        ap_ST_fsm_state18_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem_0_ARREADY == 1'b0)) begin
        ap_ST_fsm_state19_blk = 1'b1;
    end else begin
        ap_ST_fsm_state19_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

always @ (*) begin
    if ((gmem_0_RVALID == 1'b0)) begin
        ap_ST_fsm_state27_blk = 1'b1;
    end else begin
        ap_ST_fsm_state27_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem_0_RVALID == 1'b0)) begin
        ap_ST_fsm_state28_blk = 1'b1;
    end else begin
        ap_ST_fsm_state28_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem_0_RVALID == 1'b0)) begin
        ap_ST_fsm_state29_blk = 1'b1;
    end else begin
        ap_ST_fsm_state29_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem_0_RVALID == 1'b0)) begin
        ap_ST_fsm_state30_blk = 1'b1;
    end else begin
        ap_ST_fsm_state30_blk = 1'b0;
    end
end

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((gmem_0_AWREADY == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state31)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln63_1_reg_1082 == 1'd1) & (icmp_ln63_reg_1078 == 1'd1) & (icmp_ln62_reg_1074 == 1'd1) & (trunc_ln26_reg_1013 == 7'd7) & (1'b1 == ap_CS_fsm_state31))) begin
        ap_phi_mux_halted_local_2_phi_fu_406_p8 = 1'd0;
    end else begin
        ap_phi_mux_halted_local_2_phi_fu_406_p8 = halted_local_2_reg_401;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state31)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        gmem_0_ARVALID = 1'b1;
    end else begin
        gmem_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        gmem_0_AWVALID = 1'b1;
    end else begin
        gmem_0_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
        gmem_0_BREADY = 1'b1;
    end else begin
        gmem_0_BREADY = 1'b0;
    end
end

always @ (*) begin
    if ((((gmem_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state30)) | ((gmem_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state29)) | ((gmem_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state28)) | ((gmem_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state27)))) begin
        gmem_0_RREADY = 1'b1;
    end else begin
        gmem_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((((gmem_0_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state13)) | ((gmem_0_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state12)) | ((gmem_0_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state11)) | ((gmem_0_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state10)))) begin
        gmem_0_WVALID = 1'b1;
    end else begin
        gmem_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        gmem_blk_n_AR = m_axi_gmem_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        gmem_blk_n_AW = m_axi_gmem_AWREADY;
    end else begin
        gmem_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        gmem_blk_n_B = m_axi_gmem_BVALID;
    end else begin
        gmem_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27))) begin
        gmem_blk_n_R = m_axi_gmem_RVALID;
    end else begin
        gmem_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_blk_n_W = m_axi_gmem_WREADY;
    end else begin
        gmem_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        vregs_in_Addr_A = grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_vregs_in_Addr_A;
    end else begin
        vregs_in_Addr_A = vregs_in_Addr_A_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        vregs_in_Addr_A_orig = zext_ln79_3_fu_943_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        vregs_in_Addr_A_orig = zext_ln79_fu_917_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        vregs_in_Addr_A_orig = zext_ln93_3_fu_861_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        vregs_in_Addr_A_orig = zext_ln93_2_fu_809_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        vregs_in_Addr_A_orig = zext_ln93_1_fu_757_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        vregs_in_Addr_A_orig = zext_ln93_fu_720_p1;
    end else begin
        vregs_in_Addr_A_orig = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        vregs_in_Addr_B_orig = zext_ln79_4_fu_956_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        vregs_in_Addr_B_orig = zext_ln79_2_fu_930_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        vregs_in_Addr_B_orig = zext_ln92_3_fu_849_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        vregs_in_Addr_B_orig = zext_ln92_2_fu_797_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        vregs_in_Addr_B_orig = zext_ln92_1_fu_745_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        vregs_in_Addr_B_orig = zext_ln92_fu_715_p1;
    end else begin
        vregs_in_Addr_B_orig = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        vregs_in_EN_A = grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_vregs_in_EN_A;
    end else begin
        vregs_in_EN_A = vregs_in_EN_A_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | ((gmem_0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state8)) | ((gmem_0_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state10)))) begin
        vregs_in_EN_A_local = 1'b1;
    end else begin
        vregs_in_EN_A_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | ((gmem_0_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state11)))) begin
        vregs_in_EN_B_local = 1'b1;
    end else begin
        vregs_in_EN_B_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        vregs_out_Addr_A = grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_vregs_out_Addr_A;
    end else begin
        vregs_out_Addr_A = vregs_out_Addr_A_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state31)) begin
        vregs_out_Addr_A_orig = zext_ln69_4_fu_1008_p1;
    end else if ((1'b1 == ap_CS_fsm_state30)) begin
        vregs_out_Addr_A_orig = zext_ln69_3_fu_995_p1;
    end else if ((1'b1 == ap_CS_fsm_state29)) begin
        vregs_out_Addr_A_orig = zext_ln69_2_fu_982_p1;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        vregs_out_Addr_A_orig = zext_ln69_fu_969_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        vregs_out_Addr_A_orig = zext_ln98_3_fu_904_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        vregs_out_Addr_A_orig = zext_ln98_2_fu_837_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        vregs_out_Addr_A_orig = zext_ln98_1_fu_785_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        vregs_out_Addr_A_orig = zext_ln98_fu_733_p1;
    end else begin
        vregs_out_Addr_A_orig = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        vregs_out_Din_A = grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_vregs_out_Din_A;
    end else begin
        vregs_out_Din_A = vregs_out_Din_A_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28))) begin
        vregs_out_Din_A_local = reg_522;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        vregs_out_Din_A_local = r_3_fu_888_p3;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        vregs_out_Din_A_local = r_1_222_fu_873_p3;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        vregs_out_Din_A_local = r_1_11618_fu_821_p3;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        vregs_out_Din_A_local = r_1121420_fu_769_p3;
    end else begin
        vregs_out_Din_A_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        vregs_out_EN_A = grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_vregs_out_EN_A;
    end else begin
        vregs_out_EN_A = vregs_out_EN_A_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | ((gmem_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state30)) | ((gmem_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state29)) | ((gmem_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state28)))) begin
        vregs_out_EN_A_local = 1'b1;
    end else begin
        vregs_out_EN_A_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        vregs_out_WEN_A = grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_vregs_out_WEN_A;
    end else begin
        vregs_out_WEN_A = (vregs_out_WEN_A_out | 4'd0);
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | ((or_ln89_1_reg_1036 == 1'd1) & (1'b1 == ap_CS_fsm_state7)) | ((icmp_ln63_1_reg_1082 == 1'd1) & (icmp_ln63_reg_1078 == 1'd1) & (icmp_ln62_reg_1074 == 1'd1) & (trunc_ln26_reg_1013 == 7'd7) & (1'b1 == ap_CS_fsm_state31)) | ((gmem_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state30)) | ((gmem_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state29)) | ((gmem_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state28)))) begin
        vregs_out_WEN_A_local = 4'd15;
    end else begin
        vregs_out_WEN_A_local = 4'd0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2) & ((((((((~(trunc_ln26_fu_527_p1 == 7'd7) & ~(trunc_ln26_fu_527_p1 == 7'd39) & ~(trunc_ln26_fu_527_p1 == 7'd87)) | (~(trunc_ln26_fu_527_p1 == 7'd7) & ~(trunc_ln26_fu_527_p1 == 7'd39) & (or_ln36_fu_543_p2 == 1'd0))) | ((grp_fu_481_p2 == 1'd0) & (trunc_ln26_fu_527_p1 == 7'd39))) | ((grp_fu_467_p2 == 1'd0) & (trunc_ln26_fu_527_p1 == 7'd39))) | ((grp_fu_453_p2 == 1'd0) & (trunc_ln26_fu_527_p1 == 7'd39))) | ((grp_fu_481_p2 == 1'd0) & (trunc_ln26_fu_527_p1 == 7'd7))) | ((grp_fu_467_p2 == 1'd0) & (trunc_ln26_fu_527_p1 == 7'd7))) | ((grp_fu_453_p2 == 1'd0) & (trunc_ln26_fu_527_p1 == 7'd7))))) begin
                ap_NS_fsm = ap_ST_fsm_state31;
            end else if (((grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_ap_done == 1'b1) & (grp_fu_481_p2 == 1'd1) & (grp_fu_467_p2 == 1'd1) & (grp_fu_453_p2 == 1'd1) & (trunc_ln26_fu_527_p1 == 7'd7) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else if (((grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_ap_done == 1'b1) & (grp_fu_481_p2 == 1'd1) & (grp_fu_467_p2 == 1'd1) & (grp_fu_453_p2 == 1'd1) & (trunc_ln26_fu_527_p1 == 7'd39) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else if (((grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_ap_done == 1'b1) & (or_ln89_1_fu_599_p2 == 1'd0) & (or_ln36_fu_543_p2 == 1'd1) & (trunc_ln26_fu_527_p1 == 7'd87) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else if (((grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_ap_done == 1'b1) & (or_ln89_1_fu_599_p2 == 1'd1) & (or_ln36_fu_543_p2 == 1'd1) & (trunc_ln26_fu_527_p1 == 7'd87) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state8 : begin
            if (((gmem_0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((gmem_0_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((gmem_0_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            if (((gmem_0_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            if (((gmem_0_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            if (((gmem_0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state31;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state19 : begin
            if (((gmem_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            if (((gmem_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state27))) begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end
        end
        ap_ST_fsm_state28 : begin
            if (((gmem_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state28))) begin
                ap_NS_fsm = ap_ST_fsm_state29;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end
        end
        ap_ST_fsm_state29 : begin
            if (((gmem_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state29))) begin
                ap_NS_fsm = ap_ST_fsm_state30;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state29;
            end
        end
        ap_ST_fsm_state30 : begin
            if (((gmem_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state30))) begin
                ap_NS_fsm = ap_ST_fsm_state31;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state30;
            end
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln69_fu_675_p2 = (zext_ln69_1_fu_671_p1 + mem);

assign add_ln79_fu_637_p2 = (zext_ln79_1_fu_633_p1 + mem);

assign and_ln1_fu_625_p3 = {{grp_fu_487_p4}, {2'd0}};

assign and_ln_fu_663_p3 = {{grp_fu_487_p4}, {2'd0}};

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign gmem_0_ARLEN = 64'd4;

assign gmem_0_AWLEN = 64'd4;

assign grp_fu_435_p3 = {{instr[14:12]}};

assign grp_fu_453_p2 = ((grp_fu_435_p3 == 3'd6) ? 1'b1 : 1'b0);

assign grp_fu_459_p3 = {{instr[27:26]}};

assign grp_fu_467_p2 = ((grp_fu_459_p3 == 2'd0) ? 1'b1 : 1'b0);

assign grp_fu_473_p3 = {{instr[24:20]}};

assign grp_fu_481_p2 = ((grp_fu_473_p3 == 5'd0) ? 1'b1 : 1'b0);

assign grp_fu_487_p4 = {{rs1_val[31:2]}};

assign grp_fu_497_p0 = vregs_in_Dout_A;

assign grp_fu_497_p1 = vregs_in_Dout_B;

assign grp_fu_497_p2 = ($signed(grp_fu_497_p0) + $signed(grp_fu_497_p1));

assign grp_fu_503_p0 = vregs_in_Dout_B;

assign grp_fu_503_p1 = vregs_in_Dout_A;

assign grp_fu_503_p2 = ($signed(grp_fu_503_p0) - $signed(grp_fu_503_p1));

assign grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_ap_start = grp_rv32_vector_step_Pipeline_VITIS_LOOP_54_1_fu_421_ap_start_reg;

assign halted = ap_phi_mux_halted_local_2_phi_fu_406_p8;

assign icmp_ln36_fu_537_p2 = ((grp_fu_435_p3 == 3'd2) ? 1'b1 : 1'b0);

assign icmp_ln84_fu_531_p2 = ((grp_fu_435_p3 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln86_fu_557_p2 = ((tmp_9_fu_549_p3 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln87_fu_569_p2 = ((tmp_9_fu_549_p3 == 6'd2) ? 1'b1 : 1'b0);

assign icmp_ln88_fu_581_p2 = ((tmp_9_fu_549_p3 == 6'd37) ? 1'b1 : 1'b0);

assign is_add_fu_563_p2 = (icmp_ln86_fu_557_p2 & icmp_ln84_fu_531_p2);

assign is_mul_fu_587_p2 = (icmp_ln88_fu_581_p2 & icmp_ln36_fu_537_p2);

assign is_sub_fu_575_p2 = (icmp_ln87_fu_569_p2 & icmp_ln84_fu_531_p2);

assign mul1_fu_701_p3 = {{tmp_7_reg_1040}, {2'd0}};

assign mul2_fu_708_p3 = {{tmp_8_reg_1048}, {2'd0}};

assign mul3_fu_725_p3 = {{reg_509}, {2'd0}};

assign mul4_fu_909_p3 = {{reg_509}, {2'd0}};

assign mul_fu_961_p3 = {{reg_509}, {2'd0}};

assign or_ln1_fu_750_p3 = {{tmp_8_reg_1048}, {2'd1}};

assign or_ln2_fu_777_p3 = {{reg_509}, {2'd1}};

assign or_ln36_fu_543_p2 = (icmp_ln84_fu_531_p2 | icmp_ln36_fu_537_p2);

assign or_ln3_fu_974_p3 = {{reg_509}, {2'd1}};

assign or_ln4_fu_922_p3 = {{reg_509}, {2'd1}};

assign or_ln69_1_fu_987_p3 = {{reg_509}, {2'd2}};

assign or_ln69_2_fu_1000_p3 = {{reg_509}, {2'd3}};

assign or_ln79_1_fu_935_p3 = {{reg_509}, {2'd2}};

assign or_ln79_2_fu_948_p3 = {{reg_509}, {2'd3}};

assign or_ln89_1_fu_599_p2 = (or_ln89_fu_593_p2 | is_add_fu_563_p2);

assign or_ln89_fu_593_p2 = (is_sub_fu_575_p2 | is_mul_fu_587_p2);

assign or_ln92_1_fu_790_p3 = {{tmp_7_reg_1040}, {2'd2}};

assign or_ln92_2_fu_842_p3 = {{tmp_7_reg_1040}, {2'd3}};

assign or_ln93_1_fu_802_p3 = {{tmp_8_reg_1048}, {2'd2}};

assign or_ln93_2_fu_854_p3 = {{tmp_8_reg_1048}, {2'd3}};

assign or_ln98_1_fu_829_p3 = {{reg_509}, {2'd2}};

assign or_ln98_2_fu_896_p3 = {{reg_509}, {2'd3}};

assign or_ln_fu_738_p3 = {{tmp_7_reg_1040}, {2'd1}};

assign r_1121420_fu_769_p3 = ((is_add_reg_1020[0:0] == 1'b1) ? grp_fu_497_p2 : r_5_fu_762_p3);

assign r_1_11618_fu_821_p3 = ((is_add_reg_1020[0:0] == 1'b1) ? grp_fu_497_p2 : r_6_fu_814_p3);

assign r_1_222_fu_873_p3 = ((is_add_reg_1020[0:0] == 1'b1) ? grp_fu_497_p2 : r_7_fu_866_p3);

assign r_3_fu_888_p3 = ((is_add_reg_1020[0:0] == 1'b1) ? grp_fu_497_p2 : r_fu_881_p3);

assign r_5_fu_762_p3 = ((is_sub_reg_1028[0:0] == 1'b1) ? grp_fu_503_p2 : grp_fu_429_p2);

assign r_6_fu_814_p3 = ((is_sub_reg_1028[0:0] == 1'b1) ? grp_fu_503_p2 : grp_fu_429_p2);

assign r_7_fu_866_p3 = ((is_sub_reg_1028[0:0] == 1'b1) ? grp_fu_503_p2 : grp_fu_429_p2);

assign r_fu_881_p3 = ((is_sub_reg_1028[0:0] == 1'b1) ? grp_fu_503_p2 : grp_fu_429_p2);

assign sext_ln69_fu_691_p1 = $signed(trunc_ln_fu_681_p4);

assign sext_ln81_fu_653_p1 = $signed(trunc_ln1_fu_643_p4);

assign tmp_9_fu_549_p3 = {{instr[31:26]}};

assign trunc_ln1_fu_643_p4 = {{add_ln79_fu_637_p2[63:2]}};

assign trunc_ln26_fu_527_p1 = instr[6:0];

assign trunc_ln_fu_681_p4 = {{add_ln69_fu_675_p2[63:2]}};

assign vregs_in_Addr_A_local = vregs_in_Addr_A_orig << 32'd2;

assign vregs_in_Addr_B = vregs_in_Addr_B_local;

assign vregs_in_Addr_B_local = vregs_in_Addr_B_orig << 32'd2;

assign vregs_in_Clk_A = ap_clk;

assign vregs_in_Clk_B = ap_clk;

assign vregs_in_Din_A = 32'd0;

assign vregs_in_Din_B = 32'd0;

assign vregs_in_EN_B = vregs_in_EN_B_local;

assign vregs_in_Rst_A = ap_rst_n_inv;

assign vregs_in_Rst_B = ap_rst_n_inv;

assign vregs_in_WEN_A = 4'd0;

assign vregs_in_WEN_B = 4'd0;

assign vregs_out_Addr_A_local = vregs_out_Addr_A_orig << 32'd2;

assign vregs_out_Clk_A = ap_clk;

assign vregs_out_Rst_A = ap_rst_n_inv;

assign vregs_out_WEN_A_out = vregs_out_WEN_A_local;

assign zext_ln69_1_fu_671_p1 = and_ln_fu_663_p3;

assign zext_ln69_2_fu_982_p1 = or_ln3_fu_974_p3;

assign zext_ln69_3_fu_995_p1 = or_ln69_1_fu_987_p3;

assign zext_ln69_4_fu_1008_p1 = or_ln69_2_fu_1000_p3;

assign zext_ln69_fu_969_p1 = mul_fu_961_p3;

assign zext_ln79_1_fu_633_p1 = and_ln1_fu_625_p3;

assign zext_ln79_2_fu_930_p1 = or_ln4_fu_922_p3;

assign zext_ln79_3_fu_943_p1 = or_ln79_1_fu_935_p3;

assign zext_ln79_4_fu_956_p1 = or_ln79_2_fu_948_p3;

assign zext_ln79_fu_917_p1 = mul4_fu_909_p3;

assign zext_ln92_1_fu_745_p1 = or_ln_fu_738_p3;

assign zext_ln92_2_fu_797_p1 = or_ln92_1_fu_790_p3;

assign zext_ln92_3_fu_849_p1 = or_ln92_2_fu_842_p3;

assign zext_ln92_fu_715_p1 = mul1_fu_701_p3;

assign zext_ln93_1_fu_757_p1 = or_ln1_fu_750_p3;

assign zext_ln93_2_fu_809_p1 = or_ln93_1_fu_802_p3;

assign zext_ln93_3_fu_861_p1 = or_ln93_2_fu_854_p3;

assign zext_ln93_fu_720_p1 = mul2_fu_708_p3;

assign zext_ln98_1_fu_785_p1 = or_ln2_fu_777_p3;

assign zext_ln98_2_fu_837_p1 = or_ln98_1_fu_829_p3;

assign zext_ln98_3_fu_904_p1 = or_ln98_2_fu_896_p3;

assign zext_ln98_fu_733_p1 = mul3_fu_725_p3;

endmodule //rv32_vector_step
