-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity rv32_ooo_tick_expand is
port (
    ap_ready : OUT STD_LOGIC;
    c : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_rst : IN STD_LOGIC );
end;


architecture behav of rv32_ooo_tick_expand is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv8_12 : STD_LOGIC_VECTOR (7 downto 0) := "00010010";
    constant ap_const_lv9_27 : STD_LOGIC_VECTOR (8 downto 0) := "000100111";
    constant ap_const_lv9_23 : STD_LOGIC_VECTOR (8 downto 0) := "000100011";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv7_33 : STD_LOGIC_VECTOR (6 downto 0) := "0110011";
    constant ap_const_lv15_67 : STD_LOGIC_VECTOR (14 downto 0) := "000000001100111";
    constant ap_const_lv15_E7 : STD_LOGIC_VECTOR (14 downto 0) := "000000011100111";
    constant ap_const_lv10_12 : STD_LOGIC_VECTOR (9 downto 0) := "0000010010";
    constant ap_const_lv7_7 : STD_LOGIC_VECTOR (6 downto 0) := "0000111";
    constant ap_const_lv7_3 : STD_LOGIC_VECTOR (6 downto 0) := "0000011";
    constant ap_const_lv7_13 : STD_LOGIC_VECTOR (6 downto 0) := "0010011";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv7_63 : STD_LOGIC_VECTOR (6 downto 0) := "1100011";
    constant ap_const_lv7_6F : STD_LOGIC_VECTOR (6 downto 0) := "1101111";
    constant ap_const_lv5_1D : STD_LOGIC_VECTOR (4 downto 0) := "11101";
    constant ap_const_lv5_15 : STD_LOGIC_VECTOR (4 downto 0) := "10101";
    constant ap_const_lv5_19 : STD_LOGIC_VECTOR (4 downto 0) := "11001";
    constant ap_const_lv5_11 : STD_LOGIC_VECTOR (4 downto 0) := "10001";
    constant ap_const_lv8_81 : STD_LOGIC_VECTOR (7 downto 0) := "10000001";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv24_10113 : STD_LOGIC_VECTOR (23 downto 0) := "000000010000000100010011";
    constant ap_const_lv7_37 : STD_LOGIC_VECTOR (6 downto 0) := "0110111";
    constant ap_const_lv8_EF : STD_LOGIC_VECTOR (7 downto 0) := "11101111";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv5_9 : STD_LOGIC_VECTOR (4 downto 0) := "01001";
    constant ap_const_lv12_41 : STD_LOGIC_VECTOR (11 downto 0) := "000001000001";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal or_ln44_2_fu_1093_p10 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_retval_11_phi_fu_187_p80 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln65_fu_484_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln_fu_488_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal or_ln39_13_cast_fu_514_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln39_10_cast_fu_535_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln35_fu_636_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln264_fu_615_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_310_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln254_fu_540_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln262_fu_582_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln266_fu_602_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln256_fu_571_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_328_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln259_fu_558_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln35_1_fu_657_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln234_fu_676_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln39_7_cast_fu_1140_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln39_3_cast_fu_1169_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln35_5_cast_fu_1194_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln35_2_cast_fu_1219_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln79_fu_1288_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln78_fu_1266_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln44_5_fu_697_p10 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln52_1_fu_732_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln35_10_cast_fu_1014_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln5_fu_1031_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln35_8_cast_fu_1072_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln184_fu_921_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_374_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_fu_384_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal sext_ln152_fu_995_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_280_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln151_fu_977_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln181_fu_852_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln178_fu_875_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln175_fu_898_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln35_17_cast_fu_775_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln32_7_cast_cast_cast_fu_808_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln32_4_cast_fu_829_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln145_fu_964_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln144_fu_942_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_300_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_fu_290_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_318_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal or_ln39_5_fu_498_p7 : STD_LOGIC_VECTOR (27 downto 0);
    signal or_ln39_4_fu_519_p7 : STD_LOGIC_VECTOR (27 downto 0);
    signal or_ln32_8_fu_546_p5 : STD_LOGIC_VECTOR (24 downto 0);
    signal or_ln35_9_fu_563_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal or_ln262_fu_576_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal or_ln32_9_fu_588_p6 : STD_LOGIC_VECTOR (24 downto 0);
    signal or_ln35_s_fu_607_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal grp_fu_334_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_fu_344_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_54_fu_620_p7 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_66_fu_641_p7 : STD_LOGIC_VECTOR (27 downto 0);
    signal or_ln32_3_fu_662_p6 : STD_LOGIC_VECTOR (24 downto 0);
    signal grp_fu_394_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_49_fu_681_p5 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln44_1_fu_693_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_354_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_fu_402_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_44_fu_720_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_fu_420_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_438_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_fu_448_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_fu_412_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_428_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal sext_ln52_1_fu_728_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal or_ln35_6_fu_757_p8 : STD_LOGIC_VECTOR (25 downto 0);
    signal tmp_64_fu_780_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln32_fu_790_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal or_ln32_7_cast_cast_fu_794_p6 : STD_LOGIC_VECTOR (30 downto 0);
    signal or_ln6_fu_813_p7 : STD_LOGIC_VECTOR (24 downto 0);
    signal grp_fu_364_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln181_cast_fu_834_p8 : STD_LOGIC_VECTOR (23 downto 0);
    signal zext_ln178_cast_fu_857_p8 : STD_LOGIC_VECTOR (23 downto 0);
    signal zext_ln175_cast_fu_880_p8 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln184_cast_fu_903_p8 : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_fu_466_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_458_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal imm_1_fu_926_p7 : STD_LOGIC_VECTOR (9 downto 0);
    signal or_ln35_8_fu_948_p7 : STD_LOGIC_VECTOR (29 downto 0);
    signal or_ln3_fu_969_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal or_ln7_fu_983_p5 : STD_LOGIC_VECTOR (17 downto 0);
    signal or_ln35_3_fu_1000_p6 : STD_LOGIC_VECTOR (25 downto 0);
    signal tmp_40_fu_1019_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln52_fu_1027_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal or_ln35_2_fu_1056_p7 : STD_LOGIC_VECTOR (25 downto 0);
    signal tmp_37_fu_1077_p5 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln44_fu_1089_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal or_ln39_3_fu_1116_p11 : STD_LOGIC_VECTOR (26 downto 0);
    signal or_ln39_1_fu_1145_p11 : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_fu_474_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal or_ln35_1_fu_1174_p9 : STD_LOGIC_VECTOR (26 downto 0);
    signal or_ln_fu_1199_p9 : STD_LOGIC_VECTOR (26 downto 0);
    signal tmp_14_fu_1234_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_13_fu_1224_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_15_fu_1244_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal nzuimm_fu_1254_p5 : STD_LOGIC_VECTOR (9 downto 0);
    signal or_ln35_5_fu_1272_p7 : STD_LOGIC_VECTOR (29 downto 0);
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_phi_mux_retval_11_phi_fu_187_p80_assign_proc : process(or_ln44_2_fu_1093_p10, trunc_ln65_fu_484_p1, trunc_ln_fu_488_p4, or_ln39_13_cast_fu_514_p1, or_ln39_10_cast_fu_535_p1, zext_ln35_fu_636_p1, zext_ln264_fu_615_p1, grp_fu_310_p3, icmp_ln254_fu_540_p2, icmp_ln262_fu_582_p2, zext_ln266_fu_602_p1, zext_ln256_fu_571_p1, grp_fu_328_p2, zext_ln259_fu_558_p1, zext_ln35_1_fu_657_p1, zext_ln234_fu_676_p1, or_ln39_7_cast_fu_1140_p1, or_ln39_3_cast_fu_1169_p1, or_ln35_5_cast_fu_1194_p1, or_ln35_2_cast_fu_1219_p1, zext_ln79_fu_1288_p1, icmp_ln78_fu_1266_p2, or_ln44_5_fu_697_p10, or_ln52_1_fu_732_p11, or_ln35_10_cast_fu_1014_p1, or_ln5_fu_1031_p11, or_ln35_8_cast_fu_1072_p1, zext_ln184_fu_921_p1, grp_fu_374_p4, grp_fu_384_p4, sext_ln152_fu_995_p1, grp_fu_280_p4, icmp_ln151_fu_977_p2, zext_ln181_fu_852_p1, zext_ln178_fu_875_p1, zext_ln175_fu_898_p1, or_ln35_17_cast_fu_775_p1, or_ln32_7_cast_cast_cast_fu_808_p1, or_ln32_4_cast_fu_829_p1, sext_ln145_fu_964_p1, icmp_ln144_fu_942_p2)
    begin
        if (((icmp_ln144_fu_942_p2 = ap_const_lv1_0) and (trunc_ln_fu_488_p4 = ap_const_lv3_3) and (grp_fu_280_p4 = ap_const_lv5_2) and (trunc_ln65_fu_484_p1 = ap_const_lv2_1))) then 
            ap_phi_mux_retval_11_phi_fu_187_p80 <= sext_ln145_fu_964_p1;
        elsif (((trunc_ln_fu_488_p4 = ap_const_lv3_4) and (grp_fu_374_p4 = ap_const_lv2_0) and (trunc_ln65_fu_484_p1 = ap_const_lv2_1))) then 
            ap_phi_mux_retval_11_phi_fu_187_p80 <= or_ln32_4_cast_fu_829_p1;
        elsif (((trunc_ln_fu_488_p4 = ap_const_lv3_4) and (grp_fu_374_p4 = ap_const_lv2_1) and (trunc_ln65_fu_484_p1 = ap_const_lv2_1))) then 
            ap_phi_mux_retval_11_phi_fu_187_p80 <= or_ln32_7_cast_cast_cast_fu_808_p1;
        elsif (((trunc_ln_fu_488_p4 = ap_const_lv3_4) and (grp_fu_374_p4 = ap_const_lv2_2) and (trunc_ln65_fu_484_p1 = ap_const_lv2_1))) then 
            ap_phi_mux_retval_11_phi_fu_187_p80 <= or_ln35_17_cast_fu_775_p1;
        elsif (((trunc_ln_fu_488_p4 = ap_const_lv3_4) and (grp_fu_384_p4 = ap_const_lv2_0) and (grp_fu_374_p4 = ap_const_lv2_3) and (trunc_ln65_fu_484_p1 = ap_const_lv2_1))) then 
            ap_phi_mux_retval_11_phi_fu_187_p80 <= zext_ln175_fu_898_p1;
        elsif (((trunc_ln_fu_488_p4 = ap_const_lv3_4) and (grp_fu_384_p4 = ap_const_lv2_1) and (grp_fu_374_p4 = ap_const_lv2_3) and (trunc_ln65_fu_484_p1 = ap_const_lv2_1))) then 
            ap_phi_mux_retval_11_phi_fu_187_p80 <= zext_ln178_fu_875_p1;
        elsif (((trunc_ln_fu_488_p4 = ap_const_lv3_4) and (grp_fu_384_p4 = ap_const_lv2_2) and (grp_fu_374_p4 = ap_const_lv2_3) and (trunc_ln65_fu_484_p1 = ap_const_lv2_1))) then 
            ap_phi_mux_retval_11_phi_fu_187_p80 <= zext_ln181_fu_852_p1;
        elsif ((not((grp_fu_280_p4 = ap_const_lv5_0)) and not((grp_fu_280_p4 = ap_const_lv5_2)) and (trunc_ln_fu_488_p4 = ap_const_lv3_3) and (icmp_ln151_fu_977_p2 = ap_const_lv1_0) and (trunc_ln65_fu_484_p1 = ap_const_lv2_1))) then 
            ap_phi_mux_retval_11_phi_fu_187_p80 <= sext_ln152_fu_995_p1;
        elsif (((trunc_ln_fu_488_p4 = ap_const_lv3_4) and (grp_fu_384_p4 = ap_const_lv2_3) and (grp_fu_374_p4 = ap_const_lv2_3) and (trunc_ln65_fu_484_p1 = ap_const_lv2_1))) then 
            ap_phi_mux_retval_11_phi_fu_187_p80 <= zext_ln184_fu_921_p1;
        elsif (((trunc_ln_fu_488_p4 = ap_const_lv3_0) and (trunc_ln65_fu_484_p1 = ap_const_lv2_1))) then 
            ap_phi_mux_retval_11_phi_fu_187_p80 <= or_ln35_8_cast_fu_1072_p1;
        elsif (((trunc_ln_fu_488_p4 = ap_const_lv3_1) and (trunc_ln65_fu_484_p1 = ap_const_lv2_1))) then 
            ap_phi_mux_retval_11_phi_fu_187_p80 <= or_ln5_fu_1031_p11;
        elsif (((trunc_ln_fu_488_p4 = ap_const_lv3_2) and (trunc_ln65_fu_484_p1 = ap_const_lv2_1))) then 
            ap_phi_mux_retval_11_phi_fu_187_p80 <= or_ln35_10_cast_fu_1014_p1;
        elsif (((trunc_ln_fu_488_p4 = ap_const_lv3_5) and (trunc_ln65_fu_484_p1 = ap_const_lv2_1))) then 
            ap_phi_mux_retval_11_phi_fu_187_p80 <= or_ln52_1_fu_732_p11;
        elsif (((trunc_ln_fu_488_p4 = ap_const_lv3_6) and (trunc_ln65_fu_484_p1 = ap_const_lv2_1))) then 
            ap_phi_mux_retval_11_phi_fu_187_p80 <= or_ln44_5_fu_697_p10;
        elsif (((trunc_ln_fu_488_p4 = ap_const_lv3_0) and (trunc_ln65_fu_484_p1 = ap_const_lv2_0) and (icmp_ln78_fu_1266_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_retval_11_phi_fu_187_p80 <= zext_ln79_fu_1288_p1;
        elsif (((trunc_ln_fu_488_p4 = ap_const_lv3_2) and (trunc_ln65_fu_484_p1 = ap_const_lv2_0))) then 
            ap_phi_mux_retval_11_phi_fu_187_p80 <= or_ln35_2_cast_fu_1219_p1;
        elsif (((trunc_ln_fu_488_p4 = ap_const_lv3_3) and (trunc_ln65_fu_484_p1 = ap_const_lv2_0))) then 
            ap_phi_mux_retval_11_phi_fu_187_p80 <= or_ln35_5_cast_fu_1194_p1;
        elsif (((trunc_ln_fu_488_p4 = ap_const_lv3_6) and (trunc_ln65_fu_484_p1 = ap_const_lv2_0))) then 
            ap_phi_mux_retval_11_phi_fu_187_p80 <= or_ln39_3_cast_fu_1169_p1;
        elsif (((trunc_ln_fu_488_p4 = ap_const_lv3_7) and (trunc_ln65_fu_484_p1 = ap_const_lv2_0))) then 
            ap_phi_mux_retval_11_phi_fu_187_p80 <= or_ln39_7_cast_fu_1140_p1;
        elsif (((grp_fu_328_p2 = ap_const_lv1_0) and (trunc_ln_fu_488_p4 = ap_const_lv3_0) and (trunc_ln65_fu_484_p1 = ap_const_lv2_2))) then 
            ap_phi_mux_retval_11_phi_fu_187_p80 <= zext_ln234_fu_676_p1;
        elsif (((grp_fu_328_p2 = ap_const_lv1_0) and (trunc_ln_fu_488_p4 = ap_const_lv3_2) and (trunc_ln65_fu_484_p1 = ap_const_lv2_2))) then 
            ap_phi_mux_retval_11_phi_fu_187_p80 <= zext_ln35_1_fu_657_p1;
        elsif (((icmp_ln254_fu_540_p2 = ap_const_lv1_0) and (grp_fu_310_p3 = ap_const_lv1_0) and (trunc_ln_fu_488_p4 = ap_const_lv3_4) and (trunc_ln65_fu_484_p1 = ap_const_lv2_2))) then 
            ap_phi_mux_retval_11_phi_fu_187_p80 <= zext_ln259_fu_558_p1;
        elsif (((grp_fu_328_p2 = ap_const_lv1_0) and (icmp_ln254_fu_540_p2 = ap_const_lv1_1) and (grp_fu_310_p3 = ap_const_lv1_0) and (trunc_ln_fu_488_p4 = ap_const_lv3_4) and (trunc_ln65_fu_484_p1 = ap_const_lv2_2))) then 
            ap_phi_mux_retval_11_phi_fu_187_p80 <= zext_ln256_fu_571_p1;
        elsif (((icmp_ln262_fu_582_p2 = ap_const_lv1_0) and (icmp_ln254_fu_540_p2 = ap_const_lv1_0) and (grp_fu_310_p3 = ap_const_lv1_1) and (trunc_ln_fu_488_p4 = ap_const_lv3_4) and (trunc_ln65_fu_484_p1 = ap_const_lv2_2))) then 
            ap_phi_mux_retval_11_phi_fu_187_p80 <= zext_ln266_fu_602_p1;
        elsif (((icmp_ln262_fu_582_p2 = ap_const_lv1_0) and (icmp_ln254_fu_540_p2 = ap_const_lv1_1) and (grp_fu_310_p3 = ap_const_lv1_1) and (trunc_ln_fu_488_p4 = ap_const_lv3_4) and (trunc_ln65_fu_484_p1 = ap_const_lv2_2))) then 
            ap_phi_mux_retval_11_phi_fu_187_p80 <= zext_ln264_fu_615_p1;
        elsif (((trunc_ln_fu_488_p4 = ap_const_lv3_3) and (trunc_ln65_fu_484_p1 = ap_const_lv2_2))) then 
            ap_phi_mux_retval_11_phi_fu_187_p80 <= zext_ln35_fu_636_p1;
        elsif (((trunc_ln_fu_488_p4 = ap_const_lv3_6) and (trunc_ln65_fu_484_p1 = ap_const_lv2_2))) then 
            ap_phi_mux_retval_11_phi_fu_187_p80 <= or_ln39_10_cast_fu_535_p1;
        elsif (((trunc_ln_fu_488_p4 = ap_const_lv3_7) and (trunc_ln65_fu_484_p1 = ap_const_lv2_2))) then 
            ap_phi_mux_retval_11_phi_fu_187_p80 <= or_ln39_13_cast_fu_514_p1;
        elsif (((trunc_ln65_fu_484_p1 = ap_const_lv2_3) or ((trunc_ln_fu_488_p4 = ap_const_lv3_1) and (trunc_ln65_fu_484_p1 = ap_const_lv2_2)) or ((trunc_ln_fu_488_p4 = ap_const_lv3_5) and (trunc_ln65_fu_484_p1 = ap_const_lv2_2)) or (not((trunc_ln_fu_488_p4 = ap_const_lv3_6)) and not((trunc_ln_fu_488_p4 = ap_const_lv3_3)) and not((trunc_ln_fu_488_p4 = ap_const_lv3_2)) and not((trunc_ln_fu_488_p4 = ap_const_lv3_0)) and not((trunc_ln_fu_488_p4 = ap_const_lv3_7)) and (trunc_ln65_fu_484_p1 = ap_const_lv2_0)) or ((trunc_ln_fu_488_p4 = ap_const_lv3_3) and (grp_fu_280_p4 = ap_const_lv5_0) and (trunc_ln65_fu_484_p1 = ap_const_lv2_1)) or ((trunc_ln_fu_488_p4 = ap_const_lv3_0) and (trunc_ln65_fu_484_p1 = ap_const_lv2_0) and (icmp_ln78_fu_1266_p2 = ap_const_lv1_1)) or ((icmp_ln144_fu_942_p2 = ap_const_lv1_1) and (trunc_ln_fu_488_p4 = ap_const_lv3_3) and (grp_fu_280_p4 = ap_const_lv5_2) and (trunc_ln65_fu_484_p1 = ap_const_lv2_1)) or ((icmp_ln262_fu_582_p2 = ap_const_lv1_1) and (grp_fu_310_p3 = ap_const_lv1_1) and (trunc_ln_fu_488_p4 = 
    ap_const_lv3_4) and (trunc_ln65_fu_484_p1 = ap_const_lv2_2)) or ((grp_fu_328_p2 = ap_const_lv1_1) and (icmp_ln254_fu_540_p2 = ap_const_lv1_1) and (grp_fu_310_p3 = ap_const_lv1_0) and (trunc_ln_fu_488_p4 = ap_const_lv3_4) and (trunc_ln65_fu_484_p1 = ap_const_lv2_2)) or ((grp_fu_328_p2 = ap_const_lv1_1) and (trunc_ln_fu_488_p4 = ap_const_lv3_2) and (trunc_ln65_fu_484_p1 = ap_const_lv2_2)) or ((grp_fu_328_p2 = ap_const_lv1_1) and (trunc_ln_fu_488_p4 = ap_const_lv3_0) and (trunc_ln65_fu_484_p1 = ap_const_lv2_2)) or (not((grp_fu_280_p4 = ap_const_lv5_0)) and not((grp_fu_280_p4 = ap_const_lv5_2)) and (trunc_ln_fu_488_p4 = ap_const_lv3_3) and (icmp_ln151_fu_977_p2 = ap_const_lv1_1) and (trunc_ln65_fu_484_p1 = ap_const_lv2_1)))) then 
            ap_phi_mux_retval_11_phi_fu_187_p80 <= ap_const_lv32_FFFFFFFF;
        elsif (((trunc_ln_fu_488_p4 = ap_const_lv3_7) and (trunc_ln65_fu_484_p1 = ap_const_lv2_1))) then 
            ap_phi_mux_retval_11_phi_fu_187_p80 <= or_ln44_2_fu_1093_p10;
        else 
            ap_phi_mux_retval_11_phi_fu_187_p80 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    ap_ready <= ap_const_logic_1;
    ap_return <= ap_phi_mux_retval_11_phi_fu_187_p80;
    grp_fu_280_p4 <= c(11 downto 7);
    grp_fu_290_p4 <= c(6 downto 2);
    grp_fu_300_p4 <= c(8 downto 7);
    grp_fu_310_p3 <= c(12 downto 12);
    grp_fu_318_p4 <= c(11 downto 9);
    grp_fu_328_p2 <= "1" when (grp_fu_280_p4 = ap_const_lv5_0) else "0";
    grp_fu_334_p4 <= c(3 downto 2);
    grp_fu_344_p4 <= c(6 downto 4);
    grp_fu_354_p4 <= c(9 downto 7);
    grp_fu_364_p4 <= c(4 downto 2);
    grp_fu_374_p4 <= c(11 downto 10);
    grp_fu_384_p4 <= c(6 downto 5);
    grp_fu_394_p3 <= c(2 downto 2);
    grp_fu_402_p4 <= c(4 downto 3);
    grp_fu_412_p3 <= c(11 downto 11);
    grp_fu_420_p3 <= c(8 downto 8);
    grp_fu_428_p4 <= c(5 downto 3);
    grp_fu_438_p4 <= c(10 downto 9);
    
    grp_fu_448_p4_proc : process(c)
    variable vlo_cpy : STD_LOGIC_VECTOR(16+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(16+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(16 - 1 downto 0);
    variable grp_fu_448_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(16 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(16 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(16 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(4 - 1 downto 0) := ap_const_lv32_7(4 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(4 - 1 downto 0) := ap_const_lv32_6(4 - 1 downto 0);
        v0_cpy := c;
        if (vlo_cpy(4 - 1 downto 0) > vhi_cpy(4 - 1 downto 0)) then
            vhi_cpy(4-1 downto 0) := std_logic_vector(16-1-unsigned(ap_const_lv32_6(4-1 downto 0)));
            vlo_cpy(4-1 downto 0) := std_logic_vector(16-1-unsigned(ap_const_lv32_7(4-1 downto 0)));
            for grp_fu_448_p4_i in 0 to 16-1 loop
                v0_cpy(grp_fu_448_p4_i) := c(16-1-grp_fu_448_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(4-1 downto 0)))));

        section := (others=>'0');
        section(4-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(4-1 downto 0)) - unsigned(vlo_cpy(4-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(16-1 downto 0)))));
        res_mask := res_mask(16-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        grp_fu_448_p4 <= resvalue(2-1 downto 0);
    end process;

    grp_fu_458_p3 <= c(6 downto 6);
    grp_fu_466_p3 <= c(5 downto 5);
    grp_fu_474_p4 <= c(12 downto 10);
    icmp_ln144_fu_942_p2 <= "1" when (imm_1_fu_926_p7 = ap_const_lv10_0) else "0";
    icmp_ln151_fu_977_p2 <= "1" when (or_ln3_fu_969_p3 = ap_const_lv6_0) else "0";
    icmp_ln254_fu_540_p2 <= "1" when (grp_fu_290_p4 = ap_const_lv5_0) else "0";
    icmp_ln262_fu_582_p2 <= "1" when (or_ln262_fu_576_p2 = ap_const_lv5_0) else "0";
    icmp_ln78_fu_1266_p2 <= "1" when (nzuimm_fu_1254_p5 = ap_const_lv10_0) else "0";
    imm_1_fu_926_p7 <= (((((grp_fu_310_p3 & grp_fu_402_p4) & grp_fu_466_p3) & grp_fu_394_p3) & grp_fu_458_p3) & ap_const_lv4_0);
    nzuimm_fu_1254_p5 <= (((tmp_14_fu_1234_p4 & tmp_13_fu_1224_p4) & tmp_15_fu_1244_p4) & ap_const_lv2_0);
    or_ln262_fu_576_p2 <= (grp_fu_290_p4 or grp_fu_280_p4);
    or_ln32_3_fu_662_p6 <= ((((grp_fu_290_p4 & grp_fu_280_p4) & ap_const_lv3_1) & grp_fu_280_p4) & ap_const_lv7_13);
    or_ln32_4_cast_fu_829_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln6_fu_813_p7),32));
    or_ln32_7_cast_cast_cast_fu_808_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln32_7_cast_cast_fu_794_p6),32));
    or_ln32_7_cast_cast_fu_794_p6 <= ((((ap_const_lv1_1 & zext_ln32_fu_790_p1) & ap_const_lv5_15) & grp_fu_354_p4) & ap_const_lv7_13);
    or_ln32_8_fu_546_p5 <= (((grp_fu_290_p4 & ap_const_lv8_0) & grp_fu_280_p4) & ap_const_lv7_33);
    or_ln32_9_fu_588_p6 <= ((((grp_fu_290_p4 & grp_fu_280_p4) & ap_const_lv3_0) & grp_fu_280_p4) & ap_const_lv7_33);
        or_ln35_10_cast_fu_1014_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(or_ln35_3_fu_1000_p6),32));

        or_ln35_17_cast_fu_775_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(or_ln35_6_fu_757_p8),32));

    or_ln35_1_fu_1174_p9 <= (((((((grp_fu_466_p3 & grp_fu_474_p4) & grp_fu_458_p3) & ap_const_lv4_1) & grp_fu_354_p4) & ap_const_lv5_9) & grp_fu_364_p4) & ap_const_lv7_7);
    or_ln35_2_cast_fu_1219_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln_fu_1199_p9),32));
    or_ln35_2_fu_1056_p7 <= (((((grp_fu_310_p3 & grp_fu_290_p4) & grp_fu_280_p4) & ap_const_lv3_0) & grp_fu_280_p4) & ap_const_lv7_13);
    or_ln35_3_fu_1000_p6 <= ((((grp_fu_310_p3 & grp_fu_290_p4) & ap_const_lv8_0) & grp_fu_280_p4) & ap_const_lv7_13);
    or_ln35_5_cast_fu_1194_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln35_1_fu_1174_p9),32));
    or_ln35_5_fu_1272_p7 <= (((((tmp_14_fu_1234_p4 & tmp_13_fu_1224_p4) & tmp_15_fu_1244_p4) & ap_const_lv12_41) & grp_fu_364_p4) & ap_const_lv7_13);
    or_ln35_6_fu_757_p8 <= ((((((grp_fu_310_p3 & grp_fu_290_p4) & ap_const_lv2_1) & grp_fu_354_p4) & ap_const_lv5_1D) & grp_fu_354_p4) & ap_const_lv7_13);
        or_ln35_8_cast_fu_1072_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(or_ln35_2_fu_1056_p7),32));

    or_ln35_8_fu_948_p7 <= (((((grp_fu_310_p3 & grp_fu_402_p4) & grp_fu_466_p3) & grp_fu_394_p3) & grp_fu_458_p3) & ap_const_lv24_10113);
    or_ln35_9_fu_563_p3 <= (grp_fu_280_p4 & ap_const_lv15_67);
    or_ln35_s_fu_607_p3 <= (grp_fu_280_p4 & ap_const_lv15_E7);
    or_ln39_10_cast_fu_535_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln39_4_fu_519_p7),32));
    or_ln39_13_cast_fu_514_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln39_5_fu_498_p7),32));
    or_ln39_1_fu_1145_p11 <= (((((((((grp_fu_466_p3 & grp_fu_310_p3) & ap_const_lv2_1) & grp_fu_364_p4) & ap_const_lv2_1) & grp_fu_354_p4) & ap_const_lv3_2) & grp_fu_374_p4) & grp_fu_458_p3) & ap_const_lv9_23);
    or_ln39_3_cast_fu_1169_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln39_1_fu_1145_p11),32));
    or_ln39_3_fu_1116_p11 <= (((((((((grp_fu_466_p3 & grp_fu_310_p3) & ap_const_lv2_1) & grp_fu_364_p4) & ap_const_lv2_1) & grp_fu_354_p4) & ap_const_lv3_2) & grp_fu_374_p4) & grp_fu_458_p3) & ap_const_lv9_27);
    or_ln39_4_fu_519_p7 <= (((((grp_fu_300_p4 & grp_fu_310_p3) & grp_fu_290_p4) & ap_const_lv8_12) & grp_fu_318_p4) & ap_const_lv9_23);
    or_ln39_5_fu_498_p7 <= (((((grp_fu_300_p4 & grp_fu_310_p3) & grp_fu_290_p4) & ap_const_lv8_12) & grp_fu_318_p4) & ap_const_lv9_27);
    or_ln39_7_cast_fu_1140_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln39_3_fu_1116_p11),32));
    or_ln3_fu_969_p3 <= (grp_fu_310_p3 & grp_fu_290_p4);
    or_ln44_2_fu_1093_p10 <= ((((((((grp_fu_310_p3 & sext_ln44_fu_1089_p1) & ap_const_lv1_1) & grp_fu_354_p4) & ap_const_lv3_1) & grp_fu_374_p4) & grp_fu_402_p4) & grp_fu_310_p3) & ap_const_lv7_63);
    or_ln44_5_fu_697_p10 <= ((((((((grp_fu_310_p3 & sext_ln44_1_fu_693_p1) & ap_const_lv1_1) & grp_fu_354_p4) & ap_const_lv3_0) & grp_fu_374_p4) & grp_fu_402_p4) & grp_fu_310_p3) & ap_const_lv7_63);
    or_ln52_1_fu_732_p11 <= (((((((((grp_fu_310_p3 & grp_fu_420_p3) & grp_fu_438_p4) & grp_fu_448_p4) & grp_fu_394_p3) & grp_fu_412_p3) & grp_fu_428_p4) & grp_fu_310_p3) & sext_ln52_1_fu_728_p1) & ap_const_lv7_6F);
    or_ln5_fu_1031_p11 <= (((((((((grp_fu_310_p3 & grp_fu_420_p3) & grp_fu_438_p4) & grp_fu_448_p4) & grp_fu_394_p3) & grp_fu_412_p3) & grp_fu_428_p4) & grp_fu_310_p3) & sext_ln52_fu_1027_p1) & ap_const_lv8_EF);
    or_ln6_fu_813_p7 <= (((((grp_fu_290_p4 & ap_const_lv2_1) & grp_fu_354_p4) & ap_const_lv5_15) & grp_fu_354_p4) & ap_const_lv7_13);
    or_ln7_fu_983_p5 <= (((grp_fu_310_p3 & grp_fu_290_p4) & grp_fu_280_p4) & ap_const_lv7_37);
    or_ln_fu_1199_p9 <= (((((((grp_fu_466_p3 & grp_fu_474_p4) & grp_fu_458_p3) & ap_const_lv4_1) & grp_fu_354_p4) & ap_const_lv5_9) & grp_fu_364_p4) & ap_const_lv7_3);
        sext_ln145_fu_964_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(or_ln35_8_fu_948_p7),32));

        sext_ln152_fu_995_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(or_ln7_fu_983_p5),32));

        sext_ln44_1_fu_693_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_49_fu_681_p5),12));

        sext_ln44_fu_1089_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_37_fu_1077_p5),12));

        sext_ln52_1_fu_728_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_44_fu_720_p3),13));

        sext_ln52_fu_1027_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_40_fu_1019_p3),12));

    tmp_13_fu_1224_p4 <= c(12 downto 11);
    tmp_14_fu_1234_p4 <= c(10 downto 7);
    
    tmp_15_fu_1244_p4_proc : process(c)
    variable vlo_cpy : STD_LOGIC_VECTOR(16+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(16+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(16 - 1 downto 0);
    variable tmp_15_fu_1244_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(16 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(16 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(16 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(4 - 1 downto 0) := ap_const_lv32_6(4 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(4 - 1 downto 0) := ap_const_lv32_5(4 - 1 downto 0);
        v0_cpy := c;
        if (vlo_cpy(4 - 1 downto 0) > vhi_cpy(4 - 1 downto 0)) then
            vhi_cpy(4-1 downto 0) := std_logic_vector(16-1-unsigned(ap_const_lv32_5(4-1 downto 0)));
            vlo_cpy(4-1 downto 0) := std_logic_vector(16-1-unsigned(ap_const_lv32_6(4-1 downto 0)));
            for tmp_15_fu_1244_p4_i in 0 to 16-1 loop
                v0_cpy(tmp_15_fu_1244_p4_i) := c(16-1-tmp_15_fu_1244_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(4-1 downto 0)))));

        section := (others=>'0');
        section(4-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(4-1 downto 0)) - unsigned(vlo_cpy(4-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(16-1 downto 0)))));
        res_mask := res_mask(16-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tmp_15_fu_1244_p4 <= resvalue(2-1 downto 0);
    end process;

    tmp_37_fu_1077_p5 <= (((grp_fu_310_p3 & grp_fu_384_p4) & grp_fu_394_p3) & ap_const_lv6_0);
    tmp_40_fu_1019_p3 <= (grp_fu_310_p3 & ap_const_lv4_0);
    tmp_44_fu_720_p3 <= (grp_fu_310_p3 & ap_const_lv5_0);
    tmp_49_fu_681_p5 <= (((grp_fu_310_p3 & grp_fu_384_p4) & grp_fu_394_p3) & ap_const_lv6_0);
    tmp_54_fu_620_p7 <= (((((grp_fu_334_p4 & grp_fu_310_p3) & grp_fu_344_p4) & ap_const_lv10_12) & grp_fu_280_p4) & ap_const_lv7_7);
    tmp_64_fu_780_p4 <= ((grp_fu_290_p4 & ap_const_lv2_1) & grp_fu_354_p4);
    tmp_66_fu_641_p7 <= (((((grp_fu_334_p4 & grp_fu_310_p3) & grp_fu_344_p4) & ap_const_lv10_12) & grp_fu_280_p4) & ap_const_lv7_3);
    trunc_ln65_fu_484_p1 <= c(2 - 1 downto 0);
    trunc_ln_fu_488_p4 <= c(15 downto 13);
    zext_ln175_cast_fu_880_p8 <= ((((((ap_const_lv8_81 & grp_fu_364_p4) & ap_const_lv2_1) & grp_fu_354_p4) & ap_const_lv5_1) & grp_fu_354_p4) & ap_const_lv7_33);
    zext_ln175_fu_898_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln175_cast_fu_880_p8),32));
    zext_ln178_cast_fu_857_p8 <= ((((((ap_const_lv1_1 & grp_fu_364_p4) & ap_const_lv2_1) & grp_fu_354_p4) & ap_const_lv5_11) & grp_fu_354_p4) & ap_const_lv7_33);
    zext_ln178_fu_875_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln178_cast_fu_857_p8),32));
    zext_ln181_cast_fu_834_p8 <= ((((((ap_const_lv1_1 & grp_fu_364_p4) & ap_const_lv2_1) & grp_fu_354_p4) & ap_const_lv5_19) & grp_fu_354_p4) & ap_const_lv7_33);
    zext_ln181_fu_852_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln181_cast_fu_834_p8),32));
    zext_ln184_cast_fu_903_p8 <= ((((((ap_const_lv1_1 & grp_fu_364_p4) & ap_const_lv2_1) & grp_fu_354_p4) & ap_const_lv5_1D) & grp_fu_354_p4) & ap_const_lv7_33);
    zext_ln184_fu_921_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln184_cast_fu_903_p8),32));
    zext_ln234_fu_676_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln32_3_fu_662_p6),32));
    zext_ln256_fu_571_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln35_9_fu_563_p3),32));
    zext_ln259_fu_558_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln32_8_fu_546_p5),32));
    zext_ln264_fu_615_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln35_s_fu_607_p3),32));
    zext_ln266_fu_602_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln32_9_fu_588_p6),32));
    zext_ln32_fu_790_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_64_fu_780_p4),15));
    zext_ln35_1_fu_657_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_66_fu_641_p7),32));
    zext_ln35_fu_636_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_54_fu_620_p7),32));
    zext_ln79_fu_1288_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln35_5_fu_1272_p7),32));
end behav;
