-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity rv32_ooo_tick_cdb_broadcast is
port (
    ap_ready : OUT STD_LOGIC;
    tag : IN STD_LOGIC_VECTOR (2 downto 0);
    value_r : IN STD_LOGIC_VECTOR (31 downto 0);
    alu_rs_busy_0 : IN STD_LOGIC_VECTOR (0 downto 0);
    alu_rs_s1_ready_0_i : IN STD_LOGIC_VECTOR (0 downto 0);
    alu_rs_s1_ready_0_o : OUT STD_LOGIC_VECTOR (0 downto 0);
    alu_rs_s1_ready_0_o_ap_vld : OUT STD_LOGIC;
    alu_rs_s1_tag_0 : IN STD_LOGIC_VECTOR (2 downto 0);
    alu_rs_s1_val_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    alu_rs_s1_val_0_ap_vld : OUT STD_LOGIC;
    alu_rs_s2_ready_0_i : IN STD_LOGIC_VECTOR (0 downto 0);
    alu_rs_s2_ready_0_o : OUT STD_LOGIC_VECTOR (0 downto 0);
    alu_rs_s2_ready_0_o_ap_vld : OUT STD_LOGIC;
    alu_rs_s2_tag_0 : IN STD_LOGIC_VECTOR (2 downto 0);
    alu_rs_s2_val_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    alu_rs_s2_val_0_ap_vld : OUT STD_LOGIC;
    alu_rs_busy_1 : IN STD_LOGIC_VECTOR (0 downto 0);
    md_rs_busy : IN STD_LOGIC_VECTOR (0 downto 0);
    md_rs_s1_ready_i : IN STD_LOGIC_VECTOR (0 downto 0);
    md_rs_s1_ready_o : OUT STD_LOGIC_VECTOR (0 downto 0);
    md_rs_s1_ready_o_ap_vld : OUT STD_LOGIC;
    md_rs_s1_tag : IN STD_LOGIC_VECTOR (2 downto 0);
    md_rs_s1_val : OUT STD_LOGIC_VECTOR (31 downto 0);
    md_rs_s1_val_ap_vld : OUT STD_LOGIC;
    md_rs_s2_ready_i : IN STD_LOGIC_VECTOR (0 downto 0);
    md_rs_s2_ready_o : OUT STD_LOGIC_VECTOR (0 downto 0);
    md_rs_s2_ready_o_ap_vld : OUT STD_LOGIC;
    md_rs_s2_tag : IN STD_LOGIC_VECTOR (2 downto 0);
    md_rs_s2_val : OUT STD_LOGIC_VECTOR (31 downto 0);
    md_rs_s2_val_ap_vld : OUT STD_LOGIC;
    lsu_rs_busy : IN STD_LOGIC_VECTOR (0 downto 0);
    lsu_rs_s1_ready_i : IN STD_LOGIC_VECTOR (0 downto 0);
    lsu_rs_s1_ready_o : OUT STD_LOGIC_VECTOR (0 downto 0);
    lsu_rs_s1_ready_o_ap_vld : OUT STD_LOGIC;
    lsu_rs_s1_tag : IN STD_LOGIC_VECTOR (2 downto 0);
    lsu_rs_s1_val : OUT STD_LOGIC_VECTOR (7 downto 0);
    lsu_rs_s1_val_ap_vld : OUT STD_LOGIC;
    lsu_rs_s2_ready_i : IN STD_LOGIC_VECTOR (0 downto 0);
    lsu_rs_s2_ready_o : OUT STD_LOGIC_VECTOR (0 downto 0);
    lsu_rs_s2_ready_o_ap_vld : OUT STD_LOGIC;
    lsu_rs_s2_tag : IN STD_LOGIC_VECTOR (2 downto 0);
    lsu_rs_s2_val : OUT STD_LOGIC_VECTOR (31 downto 0);
    lsu_rs_s2_val_ap_vld : OUT STD_LOGIC;
    br_rs_busy : IN STD_LOGIC_VECTOR (0 downto 0);
    br_rs_s1_ready_i : IN STD_LOGIC_VECTOR (0 downto 0);
    br_rs_s1_ready_o : OUT STD_LOGIC_VECTOR (0 downto 0);
    br_rs_s1_ready_o_ap_vld : OUT STD_LOGIC;
    br_rs_s1_tag : IN STD_LOGIC_VECTOR (2 downto 0);
    br_rs_s1_val : OUT STD_LOGIC_VECTOR (31 downto 0);
    br_rs_s1_val_ap_vld : OUT STD_LOGIC;
    br_rs_s2_ready_i : IN STD_LOGIC_VECTOR (0 downto 0);
    br_rs_s2_ready_o : OUT STD_LOGIC_VECTOR (0 downto 0);
    br_rs_s2_ready_o_ap_vld : OUT STD_LOGIC;
    br_rs_s2_tag : IN STD_LOGIC_VECTOR (2 downto 0);
    br_rs_s2_val : OUT STD_LOGIC_VECTOR (31 downto 0);
    br_rs_s2_val_ap_vld : OUT STD_LOGIC;
    fpu_rs_busy : IN STD_LOGIC_VECTOR (0 downto 0);
    fpu_rs_s1_ready_i : IN STD_LOGIC_VECTOR (0 downto 0);
    fpu_rs_s1_ready_o : OUT STD_LOGIC_VECTOR (0 downto 0);
    fpu_rs_s1_ready_o_ap_vld : OUT STD_LOGIC;
    fpu_rs_s1_tag : IN STD_LOGIC_VECTOR (2 downto 0);
    fpu_rs_s1_val : OUT STD_LOGIC_VECTOR (31 downto 0);
    fpu_rs_s1_val_ap_vld : OUT STD_LOGIC;
    fpu_rs_s2_ready_i : IN STD_LOGIC_VECTOR (0 downto 0);
    fpu_rs_s2_ready_o : OUT STD_LOGIC_VECTOR (0 downto 0);
    fpu_rs_s2_ready_o_ap_vld : OUT STD_LOGIC;
    fpu_rs_s2_tag : IN STD_LOGIC_VECTOR (2 downto 0);
    fpu_rs_s2_val : OUT STD_LOGIC_VECTOR (31 downto 0);
    fpu_rs_s2_val_ap_vld : OUT STD_LOGIC;
    fpu_rs_s3_ready_i : IN STD_LOGIC_VECTOR (0 downto 0);
    fpu_rs_s3_ready_o : OUT STD_LOGIC_VECTOR (0 downto 0);
    fpu_rs_s3_ready_o_ap_vld : OUT STD_LOGIC;
    fpu_rs_s3_tag : IN STD_LOGIC_VECTOR (2 downto 0);
    fpu_rs_s3_val : OUT STD_LOGIC_VECTOR (31 downto 0);
    fpu_rs_s3_val_ap_vld : OUT STD_LOGIC;
    vec_rs_busy : IN STD_LOGIC_VECTOR (0 downto 0);
    vec_rs_s1_ready_i : IN STD_LOGIC_VECTOR (0 downto 0);
    vec_rs_s1_ready_o : OUT STD_LOGIC_VECTOR (0 downto 0);
    vec_rs_s1_ready_o_ap_vld : OUT STD_LOGIC;
    vec_rs_s1_tag : IN STD_LOGIC_VECTOR (2 downto 0);
    vec_rs_s1_val : OUT STD_LOGIC_VECTOR (7 downto 0);
    vec_rs_s1_val_ap_vld : OUT STD_LOGIC;
    sys_rs_busy : IN STD_LOGIC_VECTOR (0 downto 0);
    sys_rs_s1_ready_i : IN STD_LOGIC_VECTOR (0 downto 0);
    sys_rs_s1_ready_o : OUT STD_LOGIC_VECTOR (0 downto 0);
    sys_rs_s1_ready_o_ap_vld : OUT STD_LOGIC;
    sys_rs_s1_tag : IN STD_LOGIC_VECTOR (2 downto 0);
    sys_rs_s1_val : OUT STD_LOGIC_VECTOR (31 downto 0);
    sys_rs_s1_val_ap_vld : OUT STD_LOGIC;
    alu_rs_s1_ready_1_i : IN STD_LOGIC_VECTOR (0 downto 0);
    alu_rs_s1_ready_1_o : OUT STD_LOGIC_VECTOR (0 downto 0);
    alu_rs_s1_ready_1_o_ap_vld : OUT STD_LOGIC;
    alu_rs_s1_tag_1 : IN STD_LOGIC_VECTOR (2 downto 0);
    alu_rs_s1_val_1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    alu_rs_s1_val_1_ap_vld : OUT STD_LOGIC;
    alu_rs_s2_ready_1_i : IN STD_LOGIC_VECTOR (0 downto 0);
    alu_rs_s2_ready_1_o : OUT STD_LOGIC_VECTOR (0 downto 0);
    alu_rs_s2_ready_1_o_ap_vld : OUT STD_LOGIC;
    alu_rs_s2_tag_1 : IN STD_LOGIC_VECTOR (2 downto 0);
    alu_rs_s2_val_1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    alu_rs_s2_val_1_ap_vld : OUT STD_LOGIC;
    ap_rst : IN STD_LOGIC );
end;


architecture behav of rv32_ooo_tick_cdb_broadcast is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";

attribute shreg_extract : string;
    signal alu_rs_busy_0_load_load_fu_132_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln180_fu_150_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln183_fu_182_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal md_rs_busy_load_load_fu_268_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln187_fu_286_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln190_fu_318_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal lsu_rs_busy_load_load_fu_336_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln193_fu_354_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln177_fu_128_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_ln196_fu_386_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal br_rs_busy_load_load_fu_404_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln199_fu_422_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln202_fu_454_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal fpu_rs_busy_load_load_fu_472_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln205_fu_490_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln208_fu_522_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln211_fu_554_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal vec_rs_busy_load_load_fu_572_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln214_fu_590_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sys_rs_busy_load_load_fu_608_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln217_fu_626_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal alu_rs_busy_1_load_load_fu_200_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln180_1_fu_218_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln183_1_fu_250_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln180_fu_144_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln183_fu_176_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln180_1_fu_212_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln183_1_fu_244_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln187_fu_280_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln190_fu_312_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln193_fu_348_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln196_fu_380_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln199_fu_416_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln202_fu_448_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln205_fu_484_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln208_fu_516_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln211_fu_548_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln214_fu_584_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln217_fu_620_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ce_reg : STD_LOGIC;


begin



    alu_rs_busy_0_load_load_fu_132_p1 <= alu_rs_busy_0;
    alu_rs_busy_1_load_load_fu_200_p1 <= alu_rs_busy_1;

    alu_rs_s1_ready_0_o_assign_proc : process(alu_rs_s1_ready_0_i, alu_rs_busy_0_load_load_fu_132_p1, or_ln180_fu_150_p2)
    begin
        if (((or_ln180_fu_150_p2 = ap_const_lv1_0) and (ap_const_lv1_1 = alu_rs_busy_0_load_load_fu_132_p1))) then 
            alu_rs_s1_ready_0_o <= ap_const_lv1_1;
        else 
            alu_rs_s1_ready_0_o <= alu_rs_s1_ready_0_i;
        end if; 
    end process;


    alu_rs_s1_ready_0_o_ap_vld_assign_proc : process(alu_rs_busy_0_load_load_fu_132_p1, or_ln180_fu_150_p2)
    begin
        if (((or_ln180_fu_150_p2 = ap_const_lv1_0) and (ap_const_lv1_1 = alu_rs_busy_0_load_load_fu_132_p1))) then 
            alu_rs_s1_ready_0_o_ap_vld <= ap_const_logic_1;
        else 
            alu_rs_s1_ready_0_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    alu_rs_s1_ready_1_o_assign_proc : process(alu_rs_s1_ready_1_i, alu_rs_busy_1_load_load_fu_200_p1, or_ln180_1_fu_218_p2)
    begin
        if (((or_ln180_1_fu_218_p2 = ap_const_lv1_0) and (ap_const_lv1_1 = alu_rs_busy_1_load_load_fu_200_p1))) then 
            alu_rs_s1_ready_1_o <= ap_const_lv1_1;
        else 
            alu_rs_s1_ready_1_o <= alu_rs_s1_ready_1_i;
        end if; 
    end process;


    alu_rs_s1_ready_1_o_ap_vld_assign_proc : process(alu_rs_busy_1_load_load_fu_200_p1, or_ln180_1_fu_218_p2)
    begin
        if (((or_ln180_1_fu_218_p2 = ap_const_lv1_0) and (ap_const_lv1_1 = alu_rs_busy_1_load_load_fu_200_p1))) then 
            alu_rs_s1_ready_1_o_ap_vld <= ap_const_logic_1;
        else 
            alu_rs_s1_ready_1_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    alu_rs_s1_val_0 <= value_r;

    alu_rs_s1_val_0_ap_vld_assign_proc : process(alu_rs_busy_0_load_load_fu_132_p1, or_ln180_fu_150_p2)
    begin
        if (((or_ln180_fu_150_p2 = ap_const_lv1_0) and (ap_const_lv1_1 = alu_rs_busy_0_load_load_fu_132_p1))) then 
            alu_rs_s1_val_0_ap_vld <= ap_const_logic_1;
        else 
            alu_rs_s1_val_0_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    alu_rs_s1_val_1 <= value_r;

    alu_rs_s1_val_1_ap_vld_assign_proc : process(alu_rs_busy_1_load_load_fu_200_p1, or_ln180_1_fu_218_p2)
    begin
        if (((or_ln180_1_fu_218_p2 = ap_const_lv1_0) and (ap_const_lv1_1 = alu_rs_busy_1_load_load_fu_200_p1))) then 
            alu_rs_s1_val_1_ap_vld <= ap_const_logic_1;
        else 
            alu_rs_s1_val_1_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    alu_rs_s2_ready_0_o_assign_proc : process(alu_rs_s2_ready_0_i, alu_rs_busy_0_load_load_fu_132_p1, or_ln183_fu_182_p2)
    begin
        if (((or_ln183_fu_182_p2 = ap_const_lv1_0) and (ap_const_lv1_1 = alu_rs_busy_0_load_load_fu_132_p1))) then 
            alu_rs_s2_ready_0_o <= ap_const_lv1_1;
        else 
            alu_rs_s2_ready_0_o <= alu_rs_s2_ready_0_i;
        end if; 
    end process;


    alu_rs_s2_ready_0_o_ap_vld_assign_proc : process(alu_rs_busy_0_load_load_fu_132_p1, or_ln183_fu_182_p2)
    begin
        if (((or_ln183_fu_182_p2 = ap_const_lv1_0) and (ap_const_lv1_1 = alu_rs_busy_0_load_load_fu_132_p1))) then 
            alu_rs_s2_ready_0_o_ap_vld <= ap_const_logic_1;
        else 
            alu_rs_s2_ready_0_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    alu_rs_s2_ready_1_o_assign_proc : process(alu_rs_s2_ready_1_i, alu_rs_busy_1_load_load_fu_200_p1, or_ln183_1_fu_250_p2)
    begin
        if (((or_ln183_1_fu_250_p2 = ap_const_lv1_0) and (ap_const_lv1_1 = alu_rs_busy_1_load_load_fu_200_p1))) then 
            alu_rs_s2_ready_1_o <= ap_const_lv1_1;
        else 
            alu_rs_s2_ready_1_o <= alu_rs_s2_ready_1_i;
        end if; 
    end process;


    alu_rs_s2_ready_1_o_ap_vld_assign_proc : process(alu_rs_busy_1_load_load_fu_200_p1, or_ln183_1_fu_250_p2)
    begin
        if (((or_ln183_1_fu_250_p2 = ap_const_lv1_0) and (ap_const_lv1_1 = alu_rs_busy_1_load_load_fu_200_p1))) then 
            alu_rs_s2_ready_1_o_ap_vld <= ap_const_logic_1;
        else 
            alu_rs_s2_ready_1_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    alu_rs_s2_val_0 <= value_r;

    alu_rs_s2_val_0_ap_vld_assign_proc : process(alu_rs_busy_0_load_load_fu_132_p1, or_ln183_fu_182_p2)
    begin
        if (((or_ln183_fu_182_p2 = ap_const_lv1_0) and (ap_const_lv1_1 = alu_rs_busy_0_load_load_fu_132_p1))) then 
            alu_rs_s2_val_0_ap_vld <= ap_const_logic_1;
        else 
            alu_rs_s2_val_0_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    alu_rs_s2_val_1 <= value_r;

    alu_rs_s2_val_1_ap_vld_assign_proc : process(alu_rs_busy_1_load_load_fu_200_p1, or_ln183_1_fu_250_p2)
    begin
        if (((or_ln183_1_fu_250_p2 = ap_const_lv1_0) and (ap_const_lv1_1 = alu_rs_busy_1_load_load_fu_200_p1))) then 
            alu_rs_s2_val_1_ap_vld <= ap_const_logic_1;
        else 
            alu_rs_s2_val_1_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= ap_const_logic_1;
    br_rs_busy_load_load_fu_404_p1 <= br_rs_busy;

    br_rs_s1_ready_o_assign_proc : process(br_rs_s1_ready_i, br_rs_busy_load_load_fu_404_p1, or_ln199_fu_422_p2)
    begin
        if (((or_ln199_fu_422_p2 = ap_const_lv1_0) and (br_rs_busy_load_load_fu_404_p1 = ap_const_lv1_1))) then 
            br_rs_s1_ready_o <= ap_const_lv1_1;
        else 
            br_rs_s1_ready_o <= br_rs_s1_ready_i;
        end if; 
    end process;


    br_rs_s1_ready_o_ap_vld_assign_proc : process(br_rs_busy_load_load_fu_404_p1, or_ln199_fu_422_p2)
    begin
        if (((or_ln199_fu_422_p2 = ap_const_lv1_0) and (br_rs_busy_load_load_fu_404_p1 = ap_const_lv1_1))) then 
            br_rs_s1_ready_o_ap_vld <= ap_const_logic_1;
        else 
            br_rs_s1_ready_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    br_rs_s1_val <= value_r;

    br_rs_s1_val_ap_vld_assign_proc : process(br_rs_busy_load_load_fu_404_p1, or_ln199_fu_422_p2)
    begin
        if (((or_ln199_fu_422_p2 = ap_const_lv1_0) and (br_rs_busy_load_load_fu_404_p1 = ap_const_lv1_1))) then 
            br_rs_s1_val_ap_vld <= ap_const_logic_1;
        else 
            br_rs_s1_val_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    br_rs_s2_ready_o_assign_proc : process(br_rs_s2_ready_i, br_rs_busy_load_load_fu_404_p1, or_ln202_fu_454_p2)
    begin
        if (((or_ln202_fu_454_p2 = ap_const_lv1_0) and (br_rs_busy_load_load_fu_404_p1 = ap_const_lv1_1))) then 
            br_rs_s2_ready_o <= ap_const_lv1_1;
        else 
            br_rs_s2_ready_o <= br_rs_s2_ready_i;
        end if; 
    end process;


    br_rs_s2_ready_o_ap_vld_assign_proc : process(br_rs_busy_load_load_fu_404_p1, or_ln202_fu_454_p2)
    begin
        if (((or_ln202_fu_454_p2 = ap_const_lv1_0) and (br_rs_busy_load_load_fu_404_p1 = ap_const_lv1_1))) then 
            br_rs_s2_ready_o_ap_vld <= ap_const_logic_1;
        else 
            br_rs_s2_ready_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    br_rs_s2_val <= value_r;

    br_rs_s2_val_ap_vld_assign_proc : process(br_rs_busy_load_load_fu_404_p1, or_ln202_fu_454_p2)
    begin
        if (((or_ln202_fu_454_p2 = ap_const_lv1_0) and (br_rs_busy_load_load_fu_404_p1 = ap_const_lv1_1))) then 
            br_rs_s2_val_ap_vld <= ap_const_logic_1;
        else 
            br_rs_s2_val_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    fpu_rs_busy_load_load_fu_472_p1 <= fpu_rs_busy;

    fpu_rs_s1_ready_o_assign_proc : process(fpu_rs_s1_ready_i, fpu_rs_busy_load_load_fu_472_p1, or_ln205_fu_490_p2)
    begin
        if (((or_ln205_fu_490_p2 = ap_const_lv1_0) and (fpu_rs_busy_load_load_fu_472_p1 = ap_const_lv1_1))) then 
            fpu_rs_s1_ready_o <= ap_const_lv1_1;
        else 
            fpu_rs_s1_ready_o <= fpu_rs_s1_ready_i;
        end if; 
    end process;


    fpu_rs_s1_ready_o_ap_vld_assign_proc : process(fpu_rs_busy_load_load_fu_472_p1, or_ln205_fu_490_p2)
    begin
        if (((or_ln205_fu_490_p2 = ap_const_lv1_0) and (fpu_rs_busy_load_load_fu_472_p1 = ap_const_lv1_1))) then 
            fpu_rs_s1_ready_o_ap_vld <= ap_const_logic_1;
        else 
            fpu_rs_s1_ready_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    fpu_rs_s1_val <= value_r;

    fpu_rs_s1_val_ap_vld_assign_proc : process(fpu_rs_busy_load_load_fu_472_p1, or_ln205_fu_490_p2)
    begin
        if (((or_ln205_fu_490_p2 = ap_const_lv1_0) and (fpu_rs_busy_load_load_fu_472_p1 = ap_const_lv1_1))) then 
            fpu_rs_s1_val_ap_vld <= ap_const_logic_1;
        else 
            fpu_rs_s1_val_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    fpu_rs_s2_ready_o_assign_proc : process(fpu_rs_s2_ready_i, fpu_rs_busy_load_load_fu_472_p1, or_ln208_fu_522_p2)
    begin
        if (((or_ln208_fu_522_p2 = ap_const_lv1_0) and (fpu_rs_busy_load_load_fu_472_p1 = ap_const_lv1_1))) then 
            fpu_rs_s2_ready_o <= ap_const_lv1_1;
        else 
            fpu_rs_s2_ready_o <= fpu_rs_s2_ready_i;
        end if; 
    end process;


    fpu_rs_s2_ready_o_ap_vld_assign_proc : process(fpu_rs_busy_load_load_fu_472_p1, or_ln208_fu_522_p2)
    begin
        if (((or_ln208_fu_522_p2 = ap_const_lv1_0) and (fpu_rs_busy_load_load_fu_472_p1 = ap_const_lv1_1))) then 
            fpu_rs_s2_ready_o_ap_vld <= ap_const_logic_1;
        else 
            fpu_rs_s2_ready_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    fpu_rs_s2_val <= value_r;

    fpu_rs_s2_val_ap_vld_assign_proc : process(fpu_rs_busy_load_load_fu_472_p1, or_ln208_fu_522_p2)
    begin
        if (((or_ln208_fu_522_p2 = ap_const_lv1_0) and (fpu_rs_busy_load_load_fu_472_p1 = ap_const_lv1_1))) then 
            fpu_rs_s2_val_ap_vld <= ap_const_logic_1;
        else 
            fpu_rs_s2_val_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    fpu_rs_s3_ready_o_assign_proc : process(fpu_rs_s3_ready_i, fpu_rs_busy_load_load_fu_472_p1, or_ln211_fu_554_p2)
    begin
        if (((or_ln211_fu_554_p2 = ap_const_lv1_0) and (fpu_rs_busy_load_load_fu_472_p1 = ap_const_lv1_1))) then 
            fpu_rs_s3_ready_o <= ap_const_lv1_1;
        else 
            fpu_rs_s3_ready_o <= fpu_rs_s3_ready_i;
        end if; 
    end process;


    fpu_rs_s3_ready_o_ap_vld_assign_proc : process(fpu_rs_busy_load_load_fu_472_p1, or_ln211_fu_554_p2)
    begin
        if (((or_ln211_fu_554_p2 = ap_const_lv1_0) and (fpu_rs_busy_load_load_fu_472_p1 = ap_const_lv1_1))) then 
            fpu_rs_s3_ready_o_ap_vld <= ap_const_logic_1;
        else 
            fpu_rs_s3_ready_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    fpu_rs_s3_val <= value_r;

    fpu_rs_s3_val_ap_vld_assign_proc : process(fpu_rs_busy_load_load_fu_472_p1, or_ln211_fu_554_p2)
    begin
        if (((or_ln211_fu_554_p2 = ap_const_lv1_0) and (fpu_rs_busy_load_load_fu_472_p1 = ap_const_lv1_1))) then 
            fpu_rs_s3_val_ap_vld <= ap_const_logic_1;
        else 
            fpu_rs_s3_val_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln180_1_fu_212_p2 <= "0" when (alu_rs_s1_tag_1 = tag) else "1";
    icmp_ln180_fu_144_p2 <= "0" when (alu_rs_s1_tag_0 = tag) else "1";
    icmp_ln183_1_fu_244_p2 <= "0" when (alu_rs_s2_tag_1 = tag) else "1";
    icmp_ln183_fu_176_p2 <= "0" when (alu_rs_s2_tag_0 = tag) else "1";
    icmp_ln187_fu_280_p2 <= "0" when (md_rs_s1_tag = tag) else "1";
    icmp_ln190_fu_312_p2 <= "0" when (md_rs_s2_tag = tag) else "1";
    icmp_ln193_fu_348_p2 <= "0" when (lsu_rs_s1_tag = tag) else "1";
    icmp_ln196_fu_380_p2 <= "0" when (lsu_rs_s2_tag = tag) else "1";
    icmp_ln199_fu_416_p2 <= "0" when (br_rs_s1_tag = tag) else "1";
    icmp_ln202_fu_448_p2 <= "0" when (br_rs_s2_tag = tag) else "1";
    icmp_ln205_fu_484_p2 <= "0" when (fpu_rs_s1_tag = tag) else "1";
    icmp_ln208_fu_516_p2 <= "0" when (fpu_rs_s2_tag = tag) else "1";
    icmp_ln211_fu_548_p2 <= "0" when (fpu_rs_s3_tag = tag) else "1";
    icmp_ln214_fu_584_p2 <= "0" when (vec_rs_s1_tag = tag) else "1";
    icmp_ln217_fu_620_p2 <= "0" when (sys_rs_s1_tag = tag) else "1";
    lsu_rs_busy_load_load_fu_336_p1 <= lsu_rs_busy;

    lsu_rs_s1_ready_o_assign_proc : process(lsu_rs_s1_ready_i, lsu_rs_busy_load_load_fu_336_p1, or_ln193_fu_354_p2)
    begin
        if (((or_ln193_fu_354_p2 = ap_const_lv1_0) and (lsu_rs_busy_load_load_fu_336_p1 = ap_const_lv1_1))) then 
            lsu_rs_s1_ready_o <= ap_const_lv1_1;
        else 
            lsu_rs_s1_ready_o <= lsu_rs_s1_ready_i;
        end if; 
    end process;


    lsu_rs_s1_ready_o_ap_vld_assign_proc : process(lsu_rs_busy_load_load_fu_336_p1, or_ln193_fu_354_p2)
    begin
        if (((or_ln193_fu_354_p2 = ap_const_lv1_0) and (lsu_rs_busy_load_load_fu_336_p1 = ap_const_lv1_1))) then 
            lsu_rs_s1_ready_o_ap_vld <= ap_const_logic_1;
        else 
            lsu_rs_s1_ready_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    lsu_rs_s1_val <= trunc_ln177_fu_128_p1;

    lsu_rs_s1_val_ap_vld_assign_proc : process(lsu_rs_busy_load_load_fu_336_p1, or_ln193_fu_354_p2)
    begin
        if (((or_ln193_fu_354_p2 = ap_const_lv1_0) and (lsu_rs_busy_load_load_fu_336_p1 = ap_const_lv1_1))) then 
            lsu_rs_s1_val_ap_vld <= ap_const_logic_1;
        else 
            lsu_rs_s1_val_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    lsu_rs_s2_ready_o_assign_proc : process(lsu_rs_s2_ready_i, lsu_rs_busy_load_load_fu_336_p1, or_ln196_fu_386_p2)
    begin
        if (((or_ln196_fu_386_p2 = ap_const_lv1_0) and (lsu_rs_busy_load_load_fu_336_p1 = ap_const_lv1_1))) then 
            lsu_rs_s2_ready_o <= ap_const_lv1_1;
        else 
            lsu_rs_s2_ready_o <= lsu_rs_s2_ready_i;
        end if; 
    end process;


    lsu_rs_s2_ready_o_ap_vld_assign_proc : process(lsu_rs_busy_load_load_fu_336_p1, or_ln196_fu_386_p2)
    begin
        if (((or_ln196_fu_386_p2 = ap_const_lv1_0) and (lsu_rs_busy_load_load_fu_336_p1 = ap_const_lv1_1))) then 
            lsu_rs_s2_ready_o_ap_vld <= ap_const_logic_1;
        else 
            lsu_rs_s2_ready_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    lsu_rs_s2_val <= value_r;

    lsu_rs_s2_val_ap_vld_assign_proc : process(lsu_rs_busy_load_load_fu_336_p1, or_ln196_fu_386_p2)
    begin
        if (((or_ln196_fu_386_p2 = ap_const_lv1_0) and (lsu_rs_busy_load_load_fu_336_p1 = ap_const_lv1_1))) then 
            lsu_rs_s2_val_ap_vld <= ap_const_logic_1;
        else 
            lsu_rs_s2_val_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    md_rs_busy_load_load_fu_268_p1 <= md_rs_busy;

    md_rs_s1_ready_o_assign_proc : process(md_rs_s1_ready_i, md_rs_busy_load_load_fu_268_p1, or_ln187_fu_286_p2)
    begin
        if (((or_ln187_fu_286_p2 = ap_const_lv1_0) and (md_rs_busy_load_load_fu_268_p1 = ap_const_lv1_1))) then 
            md_rs_s1_ready_o <= ap_const_lv1_1;
        else 
            md_rs_s1_ready_o <= md_rs_s1_ready_i;
        end if; 
    end process;


    md_rs_s1_ready_o_ap_vld_assign_proc : process(md_rs_busy_load_load_fu_268_p1, or_ln187_fu_286_p2)
    begin
        if (((or_ln187_fu_286_p2 = ap_const_lv1_0) and (md_rs_busy_load_load_fu_268_p1 = ap_const_lv1_1))) then 
            md_rs_s1_ready_o_ap_vld <= ap_const_logic_1;
        else 
            md_rs_s1_ready_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    md_rs_s1_val <= value_r;

    md_rs_s1_val_ap_vld_assign_proc : process(md_rs_busy_load_load_fu_268_p1, or_ln187_fu_286_p2)
    begin
        if (((or_ln187_fu_286_p2 = ap_const_lv1_0) and (md_rs_busy_load_load_fu_268_p1 = ap_const_lv1_1))) then 
            md_rs_s1_val_ap_vld <= ap_const_logic_1;
        else 
            md_rs_s1_val_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    md_rs_s2_ready_o_assign_proc : process(md_rs_s2_ready_i, md_rs_busy_load_load_fu_268_p1, or_ln190_fu_318_p2)
    begin
        if (((or_ln190_fu_318_p2 = ap_const_lv1_0) and (md_rs_busy_load_load_fu_268_p1 = ap_const_lv1_1))) then 
            md_rs_s2_ready_o <= ap_const_lv1_1;
        else 
            md_rs_s2_ready_o <= md_rs_s2_ready_i;
        end if; 
    end process;


    md_rs_s2_ready_o_ap_vld_assign_proc : process(md_rs_busy_load_load_fu_268_p1, or_ln190_fu_318_p2)
    begin
        if (((or_ln190_fu_318_p2 = ap_const_lv1_0) and (md_rs_busy_load_load_fu_268_p1 = ap_const_lv1_1))) then 
            md_rs_s2_ready_o_ap_vld <= ap_const_logic_1;
        else 
            md_rs_s2_ready_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    md_rs_s2_val <= value_r;

    md_rs_s2_val_ap_vld_assign_proc : process(md_rs_busy_load_load_fu_268_p1, or_ln190_fu_318_p2)
    begin
        if (((or_ln190_fu_318_p2 = ap_const_lv1_0) and (md_rs_busy_load_load_fu_268_p1 = ap_const_lv1_1))) then 
            md_rs_s2_val_ap_vld <= ap_const_logic_1;
        else 
            md_rs_s2_val_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    or_ln180_1_fu_218_p2 <= (icmp_ln180_1_fu_212_p2 or alu_rs_s1_ready_1_i);
    or_ln180_fu_150_p2 <= (icmp_ln180_fu_144_p2 or alu_rs_s1_ready_0_i);
    or_ln183_1_fu_250_p2 <= (icmp_ln183_1_fu_244_p2 or alu_rs_s2_ready_1_i);
    or_ln183_fu_182_p2 <= (icmp_ln183_fu_176_p2 or alu_rs_s2_ready_0_i);
    or_ln187_fu_286_p2 <= (md_rs_s1_ready_i or icmp_ln187_fu_280_p2);
    or_ln190_fu_318_p2 <= (md_rs_s2_ready_i or icmp_ln190_fu_312_p2);
    or_ln193_fu_354_p2 <= (lsu_rs_s1_ready_i or icmp_ln193_fu_348_p2);
    or_ln196_fu_386_p2 <= (lsu_rs_s2_ready_i or icmp_ln196_fu_380_p2);
    or_ln199_fu_422_p2 <= (icmp_ln199_fu_416_p2 or br_rs_s1_ready_i);
    or_ln202_fu_454_p2 <= (icmp_ln202_fu_448_p2 or br_rs_s2_ready_i);
    or_ln205_fu_490_p2 <= (icmp_ln205_fu_484_p2 or fpu_rs_s1_ready_i);
    or_ln208_fu_522_p2 <= (icmp_ln208_fu_516_p2 or fpu_rs_s2_ready_i);
    or_ln211_fu_554_p2 <= (icmp_ln211_fu_548_p2 or fpu_rs_s3_ready_i);
    or_ln214_fu_590_p2 <= (vec_rs_s1_ready_i or icmp_ln214_fu_584_p2);
    or_ln217_fu_626_p2 <= (sys_rs_s1_ready_i or icmp_ln217_fu_620_p2);
    sys_rs_busy_load_load_fu_608_p1 <= sys_rs_busy;

    sys_rs_s1_ready_o_assign_proc : process(sys_rs_s1_ready_i, sys_rs_busy_load_load_fu_608_p1, or_ln217_fu_626_p2)
    begin
        if (((or_ln217_fu_626_p2 = ap_const_lv1_0) and (sys_rs_busy_load_load_fu_608_p1 = ap_const_lv1_1))) then 
            sys_rs_s1_ready_o <= ap_const_lv1_1;
        else 
            sys_rs_s1_ready_o <= sys_rs_s1_ready_i;
        end if; 
    end process;


    sys_rs_s1_ready_o_ap_vld_assign_proc : process(sys_rs_busy_load_load_fu_608_p1, or_ln217_fu_626_p2)
    begin
        if (((or_ln217_fu_626_p2 = ap_const_lv1_0) and (sys_rs_busy_load_load_fu_608_p1 = ap_const_lv1_1))) then 
            sys_rs_s1_ready_o_ap_vld <= ap_const_logic_1;
        else 
            sys_rs_s1_ready_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    sys_rs_s1_val <= value_r;

    sys_rs_s1_val_ap_vld_assign_proc : process(sys_rs_busy_load_load_fu_608_p1, or_ln217_fu_626_p2)
    begin
        if (((or_ln217_fu_626_p2 = ap_const_lv1_0) and (sys_rs_busy_load_load_fu_608_p1 = ap_const_lv1_1))) then 
            sys_rs_s1_val_ap_vld <= ap_const_logic_1;
        else 
            sys_rs_s1_val_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln177_fu_128_p1 <= value_r(8 - 1 downto 0);
    vec_rs_busy_load_load_fu_572_p1 <= vec_rs_busy;

    vec_rs_s1_ready_o_assign_proc : process(vec_rs_s1_ready_i, vec_rs_busy_load_load_fu_572_p1, or_ln214_fu_590_p2)
    begin
        if (((or_ln214_fu_590_p2 = ap_const_lv1_0) and (vec_rs_busy_load_load_fu_572_p1 = ap_const_lv1_1))) then 
            vec_rs_s1_ready_o <= ap_const_lv1_1;
        else 
            vec_rs_s1_ready_o <= vec_rs_s1_ready_i;
        end if; 
    end process;


    vec_rs_s1_ready_o_ap_vld_assign_proc : process(vec_rs_busy_load_load_fu_572_p1, or_ln214_fu_590_p2)
    begin
        if (((or_ln214_fu_590_p2 = ap_const_lv1_0) and (vec_rs_busy_load_load_fu_572_p1 = ap_const_lv1_1))) then 
            vec_rs_s1_ready_o_ap_vld <= ap_const_logic_1;
        else 
            vec_rs_s1_ready_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    vec_rs_s1_val <= trunc_ln177_fu_128_p1;

    vec_rs_s1_val_ap_vld_assign_proc : process(vec_rs_busy_load_load_fu_572_p1, or_ln214_fu_590_p2)
    begin
        if (((or_ln214_fu_590_p2 = ap_const_lv1_0) and (vec_rs_busy_load_load_fu_572_p1 = ap_const_lv1_1))) then 
            vec_rs_s1_val_ap_vld <= ap_const_logic_1;
        else 
            vec_rs_s1_val_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

end behav;
